package vn.codegym.salesinventory.service;
import java.util.*;import javax.sql.DataSource;import vn.codegym.salesinventory.dao.Sql;
public final class CategoryService {
 private final DataSource source;public CategoryService(DataSource source){this.source=source;}
 public List<Map<String,Object>> tree(){return Sql.transaction(source,c->{var all=Sql.query(c,"SELECT id,code,name,parent_id,version FROM categories ORDER BY name,id");var result=new ArrayList<Map<String,Object>>();visit(all,null,0,result,new HashSet<>());return result;});}
 private void visit(List<Map<String,Object>> all,Long parent,int depth,List<Map<String,Object>> out,Set<Long> seen){for(var row:all){Long p=row.get("parent_id")==null?null:Sql.id(row.get("parent_id"));if(Objects.equals(p,parent)){long id=Sql.id(row.get("id"));if(!seen.add(id))throw new IllegalStateException("Cây nhóm hàng không hợp lệ.");var item=new LinkedHashMap<>(row);item.put("depth",depth);item.put("label","— ".repeat(depth)+row.get("name"));out.add(item);visit(all,id,depth+1,out,seen);}}}
 public long save(long actor,long id,String code,String name,Long parent,long version){new AccessService(source).load(actor).require("PRODUCT_MANAGE");if(!code.matches("[A-Za-z0-9_-]{1,50}")||name.length()<2||name.length()>150)throw new IllegalArgumentException("Mã nhóm hoặc tên nhóm không hợp lệ.");return Sql.transaction(source,c->{
  Sql.one(c,"SELECT name FROM catalog_locks WHERE name='CATEGORY_TREE' FOR UPDATE");Map<String,Object> before=null;if(id!=0){before=Sql.one(c,"SELECT id,code,name,parent_id,version FROM categories WHERE id=? FOR UPDATE",id);if(Sql.id(before.get("version"))!=version)throw new IllegalArgumentException("Nhóm đã thay đổi. Hãy tải lại.");}
  Long ancestor=parent;Set<Long> seen=new HashSet<>();int depth=0;while(ancestor!=null){if(ancestor==id||!seen.add(ancestor))throw new IllegalArgumentException("Không thể tạo vòng lặp trong cây nhóm.");var p=Sql.one(c,"SELECT parent_id FROM categories WHERE id=?",ancestor);ancestor=p.get("parent_id")==null?null:Sql.id(p.get("parent_id"));if(++depth>30)throw new IllegalArgumentException("Cây nhóm tối đa 30 cấp.");}
  if(!Sql.query(c,"SELECT id FROM categories WHERE code=? AND id<>?",code,id).isEmpty())throw new IllegalArgumentException("Mã nhóm đã tồn tại.");long saved=id;if(id==0)saved=Sql.insert(c,"INSERT INTO categories(code,name,parent_id) VALUES(?,?,?)",code,name,parent);else Sql.update(c,"UPDATE categories SET code=?,name=?,parent_id=?,version=version+1 WHERE id=?",code,name,parent,id);
  AuditService.record(c,actor,"CATEGORY_SAVED","CATEGORY",saved,before,Sql.one(c,"SELECT id,code,name,parent_id,version FROM categories WHERE id=?",saved));return saved;});}
 public void delete(long actor,long id){new AccessService(source).load(actor).require("PRODUCT_MANAGE");Sql.transaction(source,c->{Sql.one(c,"SELECT name FROM catalog_locks WHERE name='CATEGORY_TREE' FOR UPDATE");var before=Sql.one(c,"SELECT id,code,name,parent_id FROM categories WHERE id=? FOR UPDATE",id);if(!Sql.query(c,"SELECT id FROM categories WHERE parent_id=? LIMIT 1",id).isEmpty())throw new IllegalArgumentException("Nhóm còn nhóm con, không thể xóa.");
  var tables=Sql.query(c,"SELECT table_name FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='products'");if(!tables.isEmpty()&&!Sql.query(c,"SELECT id FROM products WHERE category_id=? LIMIT 1",id).isEmpty())throw new IllegalArgumentException("Nhóm còn sản phẩm, không thể xóa.");
  Sql.update(c,"DELETE FROM categories WHERE id=?",id);AuditService.record(c,actor,"CATEGORY_DELETED","CATEGORY",id,before,null);return null;});}
}
