package vn.codegym.salesinventory.service;
import java.math.*;
import java.sql.*;
import java.time.LocalDate;
import java.util.*;
import javax.sql.DataSource;
import vn.codegym.salesinventory.dao.Sql;
import vn.codegym.salesinventory.dto.*;
import vn.codegym.salesinventory.validation.*;
public final class DiscountService {
    private final DataSource source;
    public DiscountService(DataSource source){this.source=source;}
    public record TierInput(BigDecimal minimum,BigDecimal value){}
    public record Input(String name,Long product,Long category,Long group,String mode,LocalDate from,LocalDate to,String status,long revision,List<TierInput> tiers){}
    public static Map<String,String> errors(Input in){var errors=new LinkedHashMap<>(PricingService.versionErrors(in.name,in.from,in.to));if((in.product==null)==(in.category==null))errors.put("target","Chọn đúng một SKU hoặc nhóm hàng.");if(in.product!=null&&in.product<=0||in.category!=null&&in.category<=0)errors.put("target","Đối tượng áp dụng không hợp lệ.");if(in.group!=null&&in.group<=0)errors.put("group","Nhóm khách không hợp lệ.");if(!Set.of("PERCENT","FIXED").contains(in.mode==null?"":in.mode))errors.put("mode","Loại chiết khấu không hợp lệ.");if(!Set.of("ACTIVE","DISABLED").contains(in.status==null?"":in.status))errors.put("status","Trạng thái không hợp lệ.");if(in.revision<0)errors.put("form","Phiên bản không hợp lệ.");if(in.tiers==null||in.tiers.isEmpty()||in.tiers.size()>100)errors.put("tiers","Chính sách cần 1–100 bậc.");else{var thresholds=new HashSet<BigDecimal>();for(int i=0;i<in.tiers.size();i++){var tier=in.tiers.get(i);try{var q=CatalogValidation.decimal(tier.minimum,6,false);if(!thresholds.add(q))errors.put("minimum"+i,"Mốc sản lượng bị trùng.");}catch(IllegalArgumentException e){errors.put("minimum"+i,e.getMessage());}try{var amount=CatalogValidation.decimal(tier.value,"FIXED".equals(in.mode)?4:6,false);if("PERCENT".equals(in.mode)&&amount.compareTo(new BigDecimal("100"))>0)errors.put("value"+i,"Phần trăm không vượt 100.");}catch(IllegalArgumentException e){errors.put("value"+i,e.getMessage());}}}return errors;}
    public PageResult<Map<String,Object>> search(long actor,String query,PageRequest request){String q=query==null?"":query.trim();if(q.length()>150)q=q.substring(0,150);final String term="%"+q+"%";return Sql.snapshot(source,c->{DealerService.access(c,actor,"DISCOUNT_READ");long total=Sql.id(Sql.one(c,"SELECT COUNT(*) total FROM discount_policies WHERE name LIKE ?",term).get("total"));var p=request.clamp(total);var rows=Sql.query(c,"SELECT d.*,p.sku,p.name product_name,c.name category_name,g.name group_name FROM discount_policies d LEFT JOIN products p ON p.id=d.product_id LEFT JOIN categories c ON c.id=d.category_id LEFT JOIN customer_groups g ON g.id=d.customer_group_id WHERE d.name LIKE ? ORDER BY d.valid_from DESC,d.id DESC LIMIT ? OFFSET ?",term,p.pageSize(),p.offset());return new PageResult<>(rows,total,p.page(),p.pageSize());});}
    public Map<String,Object> find(long actor,long id){return Sql.transaction(source,c->{DealerService.access(c,actor,"DISCOUNT_READ");var row=Sql.one(c,"SELECT * FROM discount_policies WHERE id=?",id);row.put("tiers",Sql.query(c,"SELECT minimum_quantity,discount_value FROM discount_tiers WHERE policy_id=? AND policy_revision=? ORDER BY minimum_quantity,id",id,row.get("revision")));return row;});}
    public long save(long actor,long id,Input in){var errors=errors(in);if(!errors.isEmpty())throw new FieldValidationException(errors);return Sql.transaction(source,c->{var access=DealerService.access(c,actor,"DISCOUNT_MANAGE");if(!access.roles().contains("SALES_MANAGER"))throw new SecurityException("Chỉ Quản lý kinh doanh quản lý chiết khấu.");Sql.one(c,"SELECT name FROM catalog_locks WHERE name='CATEGORY_TREE' FOR SHARE");Sql.one(c,"SELECT name FROM catalog_locks WHERE name='DISCOUNT_POLICIES' FOR UPDATE");
            Map<String,Object> before=id==0?null:Sql.one(c,"SELECT * FROM discount_policies WHERE id=? FOR UPDATE",id);if(before!=null&&Sql.id(before.get("revision"))!=in.revision)throw FieldValidationException.field("form","Chính sách đã thay đổi. Hãy tải lại.");if(before!=null)before.put("tiers",Sql.query(c,"SELECT minimum_quantity,discount_value FROM discount_tiers WHERE policy_id=? AND policy_revision=? ORDER BY minimum_quantity,id",id,before.get("revision")));
            if(in.product!=null&&Sql.query(c,"SELECT id FROM products WHERE id=?",in.product).isEmpty()||in.category!=null&&Sql.query(c,"SELECT id FROM categories WHERE id=?",in.category).isEmpty())throw FieldValidationException.field("target","Đối tượng không còn tồn tại.");if(in.group!=null&&Sql.query(c,"SELECT id FROM customer_groups WHERE id=?",in.group).isEmpty())throw FieldValidationException.field("group","Nhóm khách không còn tồn tại.");
            if("FIXED".equals(in.mode)){String sql=in.product!=null?"SELECT MIN(i.selling_price) cheapest FROM price_items i JOIN price_versions v ON v.id=i.version_id WHERE i.product_id=? AND (? IS NULL OR v.group_id=?) AND v.valid_from<=? AND v.valid_to>=?":"WITH RECURSIVE subtree AS (SELECT id FROM categories WHERE id=? UNION ALL SELECT c.id FROM categories c JOIN subtree s ON c.parent_id=s.id) SELECT MIN(i.selling_price) cheapest FROM price_items i JOIN price_versions v ON v.id=i.version_id JOIN products p ON p.id=i.product_id JOIN subtree s ON s.id=p.category_id WHERE (? IS NULL OR v.group_id=?) AND v.valid_from<=? AND v.valid_to>=?";var cheapest=(BigDecimal)Sql.one(c,sql,in.product!=null?in.product:in.category,in.group,in.group,in.to,in.from).get("cheapest");if(cheapest!=null)for(int i=0;i<in.tiers.size();i++)if(in.tiers.get(i).value.compareTo(cheapest)>0)throw FieldValidationException.field("value"+i,"Tiền giảm cố định vượt giá bán đang áp dụng trên đối tượng.");}
            long saved=id,revision=before==null?1:Sql.id(before.get("revision"))+1;Object[] args={in.name.trim(),in.product,in.category,in.group,in.mode,in.from,in.to,in.status};if(id==0)saved=Sql.insert(c,"INSERT INTO discount_policies(name,product_id,category_id,customer_group_id,mode,valid_from,valid_to,status) VALUES(?,?,?,?,?,?,?,?)",args);else{var params=new ArrayList<Object>(Arrays.asList(args));params.add(id);Sql.update(c,"UPDATE discount_policies SET name=?,product_id=?,category_id=?,customer_group_id=?,mode=?,valid_from=?,valid_to=?,status=?,revision=revision+1 WHERE id=?",params.toArray());}
            for(var tier:in.tiers)Sql.insert(c,"INSERT INTO discount_tiers(policy_id,policy_revision,minimum_quantity,discount_value) VALUES(?,?,?,?)",saved,revision,CatalogValidation.decimal(tier.minimum,6,false),CatalogValidation.decimal(tier.value,"FIXED".equals(in.mode)?4:6,false));var after=Sql.one(c,"SELECT * FROM discount_policies WHERE id=?",saved);after.put("tiers",Sql.query(c,"SELECT minimum_quantity,discount_value FROM discount_tiers WHERE policy_id=? AND policy_revision=?",saved,revision));AuditService.record(c,actor,"DISCOUNT_POLICY_SAVED","DISCOUNT_POLICY",saved,before,after);return saved;});}
    /** Package-private: order service must establish actor/dealer scope before calling. */
    static DiscountMath.Selection select(Connection c,long product,long group,LocalDate date,List<BigDecimal> baseQuantities,BigDecimal selling)throws SQLException{Sql.one(c,"SELECT name FROM catalog_locks WHERE name='CATEGORY_TREE' FOR SHARE");Sql.one(c,"SELECT name FROM catalog_locks WHERE name='DISCOUNT_POLICIES' FOR SHARE");var rows=Sql.query(c,"WITH RECURSIVE ancestors AS (SELECT c.id,c.parent_id FROM categories c JOIN products p ON p.category_id=c.id WHERE p.id=? UNION ALL SELECT c.id,c.parent_id FROM categories c JOIN ancestors a ON c.id=a.parent_id) SELECT d.id policy_id,d.revision,t.id tier_id,d.name,d.mode,t.minimum_quantity,t.discount_value FROM discount_policies d JOIN discount_tiers t ON t.policy_id=d.id AND t.policy_revision=d.revision WHERE d.status='ACTIVE' AND d.valid_from<=? AND d.valid_to>=? AND (d.customer_group_id IS NULL OR d.customer_group_id=?) AND (d.product_id=? OR d.category_id IN (SELECT id FROM ancestors)) ORDER BY d.id,t.minimum_quantity DESC,t.id",product,date,date,group,product);var tiers=new ArrayList<DiscountMath.Tier>();for(var row:rows)tiers.add(new DiscountMath.Tier(Sql.id(row.get("policy_id")),Sql.id(row.get("revision")),Sql.id(row.get("tier_id")),Sql.text(row.get("name")),Sql.text(row.get("mode")),(BigDecimal)row.get("minimum_quantity"),(BigDecimal)row.get("discount_value")));return DiscountMath.best(baseQuantities,selling,tiers);}
    public DiscountMath.Selection preview(long actor,long product,long group,LocalDate date,List<BigDecimal> baseQuantities){return Sql.transaction(source,c->{var access=DealerService.access(c,actor,"DISCOUNT_READ");var quote=PricingService.quote(c,access,group,product,date);return select(c,product,group,date,baseQuantities,quote.sellingPrice());});}
    static void snapshot(Connection c,String orderReference,long product,DiscountMath.Selection selection)throws SQLException{if(!selection.applied())return;var t=selection.tier();Sql.insert(c,"INSERT INTO discount_order_references(order_reference,product_id,policy_id,policy_revision,tier_id,policy_name,mode,discount_value) VALUES(?,?,?,?,?,?,?,?)",CatalogValidation.text(orderReference,100,"Tham chiếu đơn"),product,t.policyId(),t.revision(),t.tierId(),t.name(),t.mode(),t.value());}
}
