package vn.codegym.salesinventory.service;

import java.sql.*;
import java.time.*;
import java.util.*;
import javax.sql.DataSource;
import vn.codegym.salesinventory.dao.Sql;
import vn.codegym.salesinventory.dto.*;
import vn.codegym.salesinventory.security.Access;

/** Persistent preview, complete-task filters and reports; HTTP sessions only retain a job ID. */
public final class ImportJobService {
    private final DataSource source;private final Clock clock;private final Duration previewAge,reportAge;
    public ImportJobService(DataSource source){this(source,Clock.systemUTC(),Duration.ofMinutes(30),Duration.ofDays(7));}
    public ImportJobService(DataSource source,Clock clock,Duration previewAge,Duration reportAge){this.source=source;this.clock=clock;this.previewAge=previewAge;this.reportAge=reportAge;if(previewAge.isNegative()||previewAge.isZero()||reportAge.isNegative()||reportAge.isZero())throw new IllegalArgumentException("Thời hạn import phải dương.");}
    static String permission(String kind){if(!Set.of("USER","PRODUCT").contains(kind))throw new IllegalArgumentException("Loại nhập không hợp lệ.");return kind.equals("USER")?"USER_MANAGE":"PRODUCT_MANAGE";}
    static Access access(Connection c,long actor,String kind)throws SQLException{var a=DealerService.access(c,actor,permission(kind));if(PortalAccountService.portal(c,actor)||a.roles().contains("DEALER"))throw new SecurityException();return a;}
    static String limited(String text,int limit){if(text==null)return "";return text.codePointCount(0,text.length())>limit?text.substring(0,text.offsetByCodePoints(0,limit)):text;}
    private static String file(String value){String name=value==null?"du-lieu.xlsx":value.replace('\\','/');name=name.substring(name.lastIndexOf('/')+1).replaceAll("[\\p{Cntrl}]","");return name.isBlank()?"du-lieu.xlsx":limited(name,180);}
    private Map<String,Object> owned(Connection c,long actor,String kind,String id)throws SQLException{access(c,actor,kind);var rows=Sql.query(c,"SELECT * FROM import_jobs WHERE id=? AND actor_id=? AND kind=?",id,actor,kind);if(rows.isEmpty())throw new SecurityException("Tác vụ không thuộc người nhập hoặc không còn khả dụng.");var job=rows.get(0);if(job.get("report_expires_at")!=null&&!Sql.instant(job.get("report_expires_at")).isAfter(clock.instant()))throw new IllegalArgumentException("Báo cáo đã hết thời hạn lưu.");return job;}
    public String create(long actor,String kind,String filename,ImportPreview preview){if(!preview.available(actor,clock.instant()))throw new IllegalArgumentException("Xem trước không thuộc người nhập hoặc đã hết hạn.");if(preview.getLines().isEmpty()||preview.getLines().size()>10000)throw new IllegalArgumentException("Tác vụ cần 1–10.000 dòng.");return Sql.transaction(source,c->{var a=access(c,actor,kind);if(preview.hasCostColumn())a.require("COST_WRITE");String id=UUID.randomUUID().toString(),key=UUID.randomUUID().toString();long valid=preview.getLines().stream().filter(ImportPreview.Line::isValid).count();
        Sql.update(c,"INSERT INTO import_jobs(id,kind,actor_id,filename,has_cost,confirm_key,total_rows,valid_rows,preview_expires_at) VALUES(?,?,?,?,?,?,?,?,?)",id,kind,actor,file(filename),preview.hasCostColumn(),key,preview.getLines().size(),valid,Timestamp.from(clock.instant().plus(previewAge)));
        try(var statement=c.prepareStatement("INSERT INTO import_job_rows(job_id,source_row,c0,c1,c2,c3,c4,c5,c6,operation,validation_error,expected_id,expected_version,state) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)")){int pending=0;Set<Integer> numbers=new HashSet<>();for(var row:preview.getLines()){if(row.number()<2||row.number()>10001||!numbers.add(row.number()))throw new IllegalArgumentException("Số dòng dữ liệu không hợp lệ hoặc bị trùng.");statement.setString(1,id);statement.setInt(2,row.number());for(int col=0;col<7;col++)statement.setString(3+col,col<row.cells().size()?row.cells().get(col):"");statement.setString(10,limited(row.operation(),20));statement.setString(11,limited(row.error(),1000));var expected=preview.productState(row.number());statement.setLong(12,expected==null?0:expected.id());statement.setLong(13,expected==null?0:expected.version());statement.setString(14,row.isValid()?"READY":"INVALID");statement.addBatch();if(++pending==200){statement.executeBatch();pending=0;}}if(pending>0)statement.executeBatch();}
        return id;});}
    public Map<String,Object> find(long actor,String kind,String id){return Sql.snapshot(source,c->{var job=owned(c,actor,kind,id);job.putAll(summary(c,id));job.put("available","PREVIEW".equals(job.get("status"))&&Sql.instant(job.get("preview_expires_at")).isAfter(clock.instant()));job.put("headers",headers(job,access(c,actor,kind)));return job;});}
    static Map<String,Object> summary(Connection c,String id)throws SQLException{return Sql.one(c,"SELECT COUNT(*) row_count,COALESCE(SUM(state='SUCCESS'),0) success_count,COALESCE(SUM(state='FAILED'),0) failed_count,COALESCE(SUM(state='INVALID'),0) invalid_count,COALESCE(SUM(state='REVIEW'),0) review_count,COALESCE(SUM(state='SKIPPED'),0) skipped_count,COALESCE(SUM(state IN ('READY','CLAIMED','EMAIL_ATTEMPT')),0) pending_count FROM import_job_rows WHERE job_id=?",id);}
    public Map<String,Object> progress(long actor,String kind,String id){var all=find(actor,kind,id);var dto=new LinkedHashMap<String,Object>();for(String key:List.of("id","status","total_rows","valid_rows","success_count","failed_count","invalid_count","review_count","skipped_count","pending_count","reason"))dto.put(key,all.get(key));return dto;}
    public void confirm(long actor,String kind,String id,long version,String key){Sql.transaction(source,c->{var a=access(c,actor,kind);var rows=Sql.query(c,"SELECT * FROM import_jobs WHERE id=? AND actor_id=? AND kind=? FOR UPDATE",id,actor,kind);if(rows.isEmpty())throw new SecurityException();var job=rows.get(0);if(DealerAddressService.isDefault(job.get("has_cost")))a.require("COST_WRITE");
        if(!Objects.equals(job.get("confirm_key"),key))throw new IllegalArgumentException("Mã xác nhận không hợp lệ.");if(!"PREVIEW".equals(job.get("status")))return null;
        if(Sql.id(job.get("version"))!=version)throw new IllegalArgumentException("Xem trước đã thay đổi.");if(!Sql.instant(job.get("preview_expires_at")).isAfter(clock.instant()))throw new IllegalArgumentException("Xem trước đã hết thời hạn. Hãy tải lại tệp.");
        if(Sql.id(job.get("valid_rows"))==0)throw new IllegalArgumentException("Không có dòng hợp lệ để xử lý.");Sql.update(c,"UPDATE import_jobs SET status='QUEUED',version=version+1 WHERE id=?",id);AuditService.record(c,actor,"IMPORT_JOB_CONFIRMED","IMPORT_JOB",0,null,Map.of("job_id",id,"kind",kind,"valid_rows",job.get("valid_rows")));return null;});}
    static List<String> cells(Map<String,Object> row,boolean costVisible,String kind){int size=kind.equals("USER")||costVisible?7:6;var result=new ArrayList<String>();for(int i=0;i<size;i++)result.add(Sql.text(row.get("c"+i)));return result;}
    private static List<String> headers(Map<String,Object> job,Access a){var headers=new ArrayList<>("USER".equals(job.get("kind"))?UserImportService.HEADERS:ProductImportService.HEADERS);if("PRODUCT".equals(job.get("kind"))&&DealerAddressService.isDefault(job.get("has_cost"))&&a.allows("COST_READ"))headers.add("Giá vốn");return headers;}
    private static String filter(String state){return Set.of("INVALID","READY","CLAIMED","EMAIL_ATTEMPT","SUCCESS","FAILED","REVIEW","SKIPPED").contains(state==null?"":state)?state:"";}
    public PageResult<Map<String,Object>> rows(long actor,String kind,String id,String query,String state,PageRequest request){String q="%"+limited(query==null?"":query.trim(),150)+"%",chosen=filter(state);return Sql.snapshot(source,c->{var job=owned(c,actor,kind,id);var a=access(c,actor,kind);String where=" WHERE job_id=? AND (?='' OR state=?) AND (c0 LIKE ? OR c1 LIKE ? OR c2 LIKE ? OR message LIKE ? OR validation_error LIKE ? OR CAST(source_row AS CHAR) LIKE ?)";Object[] args={id,chosen,chosen,q,q,q,q,q,q};long total=Sql.id(Sql.one(c,"SELECT COUNT(*) total FROM import_job_rows"+where,args).get("total"));var p=request.clamp(total);var params=new ArrayList<Object>(Arrays.asList(args));params.add(p.pageSize());params.add(p.offset());var found=Sql.query(c,"SELECT * FROM import_job_rows"+where+" ORDER BY source_row LIMIT ? OFFSET ?",params.toArray());var visible=new ArrayList<Map<String,Object>>();for(var row:found){var dto=new LinkedHashMap<String,Object>();dto.put("number",row.get("source_row"));dto.put("cells",cells(row,DealerAddressService.isDefault(job.get("has_cost"))&&a.allows("COST_READ"),kind));dto.put("operation",row.get("operation"));dto.put("state",row.get("state"));dto.put("error",Sql.text(row.get("validation_error")).isEmpty()?row.get("message"):row.get("validation_error"));dto.put("label",label(Sql.text(row.get("state"))));visible.add(dto);}return new PageResult<>(visible,total,p.page(),p.pageSize());});}
    public byte[] report(long actor,String kind,String id){return Sql.snapshot(source,c->{var job=owned(c,actor,kind,id);var a=access(c,actor,kind);var heading=new ArrayList<String>();heading.add("Dòng");heading.addAll(headers(job,a));heading.addAll(List.of("Thao tác","Kết quả","Lỗi"));var data=new ArrayList<List<String>>();data.add(heading);for(var row:Sql.query(c,"SELECT * FROM import_job_rows WHERE job_id=? ORDER BY source_row",id)){var values=new ArrayList<String>();values.add(row.get("source_row").toString());values.addAll(cells(row,DealerAddressService.isDefault(job.get("has_cost"))&&a.allows("COST_READ"),kind));values.add(Sql.text(row.get("operation")));values.add(label(Sql.text(row.get("state"))));values.add(Sql.text(row.get("validation_error")).isEmpty()?Sql.text(row.get("message")):Sql.text(row.get("validation_error")));data.add(values);}return Xlsx.write(data);});}
    public static String label(String state){return switch(state){case "INVALID"->"Không hợp lệ";case "READY"->"Chờ xử lý";case "CLAIMED"->"Đang xử lý";case "EMAIL_ATTEMPT"->"Đang gửi email";case "SUCCESS"->"Đã nhập";case "FAILED"->"Thất bại";case "REVIEW"->"Cần kiểm tra email";case "SKIPPED"->"Chưa xử lý do dừng";default->state;};}
    public int cleanup(){return Sql.transaction(source,c->{var now=Timestamp.from(clock.instant());Sql.update(c,"UPDATE import_jobs SET status='EXPIRED',reason='Xem trước đã hết hạn',finished_at=?,report_expires_at=? WHERE status='PREVIEW' AND preview_expires_at<=?",now,Timestamp.from(clock.instant().plus(reportAge)),now);return Sql.update(c,"DELETE FROM import_jobs WHERE status IN ('COMPLETED','STOPPED','EXPIRED') AND report_expires_at<=? AND (lease_until IS NULL OR lease_until<=?) ORDER BY report_expires_at,id LIMIT 1",now,now);});}
}
