package vn.codegym.salesinventory.service;

import java.sql.*;
import java.time.*;
import java.util.*;
import javax.sql.DataSource;
import vn.codegym.salesinventory.dao.*;
import vn.codegym.salesinventory.dto.*;
import vn.codegym.salesinventory.model.UserStatus;
import vn.codegym.salesinventory.security.*;
import vn.codegym.salesinventory.validation.*;

public final class PortalAccountService {
    private final DataSource source;private final ActivationService activation;private final PasswordHasher hasher;private final Clock clock;
    public PortalAccountService(DataSource source,ActivationService activation){this(source,activation,new BCryptPasswordHasher(),Clock.systemUTC());}
    public PortalAccountService(DataSource source,ActivationService activation,PasswordHasher hasher,Clock clock){this.source=source;this.activation=activation;this.hasher=hasher;this.clock=clock;}
    private static Access manager(Connection c,long actor)throws SQLException{var a=DealerService.access(c,actor,"PORTAL_ACCOUNT_MANAGE");if(!a.roles().contains("SALES_MANAGER")||a.roles().contains("DEALER"))throw new SecurityException();return a;}
    public static boolean portal(Connection c,long actor)throws SQLException{return "DEALER".equals(Sql.one(c,"SELECT account_kind FROM users WHERE id=? FOR SHARE",actor).get("account_kind"));}
    public static Access access(Connection c,long actor,String permission)throws SQLException{if(!portal(c,actor))throw new SecurityException("Chỉ tài khoản cổng đại lý.");var a=DealerService.access(c,actor,permission);if(!a.roles().equals(Set.of("DEALER")))throw new SecurityException("Tài khoản cổng không được mang vai trò nội bộ.");return a;}
    static Map<String,Object> scoped(Connection c,long actor,Access a,long dealer,boolean lock)throws SQLException{a.require("PORTAL_ORDER_READ");if(!a.roles().equals(Set.of("DEALER"))||!portal(c,actor))throw new SecurityException();var links=Sql.query(c,"SELECT dealer_id FROM dealer_accounts WHERE user_id=? FOR SHARE",actor);
        if(links.isEmpty()||Sql.id(links.get(0).get("dealer_id"))!=dealer)throw new SecurityException("Dữ liệu không thuộc đại lý đang liên kết.");return Sql.one(c,"SELECT * FROM dealers WHERE id=?"+(lock?" FOR UPDATE":""),dealer);}
    static long linked(Connection c,long actor)throws SQLException{access(c,actor,"PORTAL_ORDER_READ");var rows=Sql.query(c,"SELECT dealer_id FROM dealer_accounts WHERE user_id=? FOR SHARE",actor);if(rows.isEmpty())throw new SecurityException("Tài khoản chưa có liên kết hợp lệ.");return Sql.id(rows.get(0).get("dealer_id"));}
    public Map<String,Object> profile(long actor){return Sql.transaction(source,c->{var a=access(c,actor,"PORTAL_ORDER_READ");var d=scoped(c,actor,a,linked(c,actor),false);return Map.of("id",d.get("id"),"code",d.get("code"),"name",d.get("name"),"phone",d.get("phone"),"status",d.get("status"),"locked",DealerStatusService.locked(d));});}
    private static Map<String,Object> target(Connection c,long user)throws SQLException{var rows=Sql.query(c,"SELECT u.id,u.username,u.username_normalized,u.email,u.full_name,u.status,u.status_before_lock,u.version user_version,a.dealer_id,a.version FROM users u JOIN dealer_accounts a ON a.user_id=u.id WHERE u.id=? AND u.account_kind='DEALER' FOR UPDATE",user);if(rows.isEmpty())throw new SecurityException("Chỉ quản lý tài khoản đại lý qua chức năng này.");return rows.get(0);}
    public PageResult<Map<String,Object>> search(long actor,String query,Long dealer,PageRequest request){String q=query==null?"":query.trim();if(q.length()>150)q=q.substring(0,150);String term="%"+q+"%";return Sql.transaction(source,c->{manager(c,actor);String from=" FROM dealer_accounts a JOIN users u ON u.id=a.user_id JOIN dealers d ON d.id=a.dealer_id WHERE u.account_kind='DEALER' AND (? IS NULL OR a.dealer_id=?) AND (u.username LIKE ? OR u.full_name LIKE ? OR u.email LIKE ? OR d.code LIKE ? OR d.name LIKE ?)";Object[] args={dealer,dealer,term,term,term,term,term};long total=Sql.id(Sql.one(c,"SELECT COUNT(*) total"+from,args).get("total"));var p=request.clamp(total);var params=new ArrayList<Object>(Arrays.asList(args));params.add(p.pageSize());params.add(p.offset());var rows=Sql.query(c,"SELECT u.id,u.username,u.email,u.full_name,u.status,u.version user_version,a.dealer_id,a.version,d.code dealer_code,d.name dealer_name"+from+" ORDER BY u.username,u.id LIMIT ? OFFSET ?",params.toArray());return new PageResult<>(rows,total,p.page(),p.pageSize());});}
    private static void current(Map<String,Object> before,long version){if(Sql.id(before.get("version"))!=version)throw FieldValidationException.field("form","Liên kết tài khoản đã thay đổi. Hãy tải lại.");}
    public void relink(long actor,long user,long version,long dealer,String reason){String why=CatalogValidation.text(reason,1000,"Lý do đổi liên kết");Sql.transaction(source,c->{var a=manager(c,actor);var before=target(c,user);current(before,version);if(Sql.id(before.get("dealer_id"))==dealer)throw FieldValidationException.field("dealer","Tài khoản đã liên kết đại lý này.");for(long id:new TreeSet<>(List.of(Sql.id(before.get("dealer_id")),dealer)))DealerService.scoped(c,actor,a,id,true);
        Sql.update(c,"UPDATE dealer_accounts SET dealer_id=?,version=version+1 WHERE user_id=?",dealer,user);Sql.update(c,"UPDATE users SET version=version+1 WHERE id=?",user);new JdbcSessionRepository().revokeAllForUser(c,user,clock.instant(),"DEALER_LINK_CHANGED");
        Sql.insert(c,"INSERT INTO dealer_account_link_history(user_id,old_dealer_id,new_dealer_id,actor_id,reason,account_version) VALUES(?,?,?,?,?,?)",user,before.get("dealer_id"),dealer,actor,why,version+1);
        AuditService.record(c,actor,"PORTAL_ACCOUNT_RELINKED","PORTAL_ACCOUNT",user,Map.of("dealer_id",before.get("dealer_id")),Map.of("dealer_id",dealer,"reason",why));return null;});}
    public void status(long actor,long user,long version,boolean lock,String reason){String why=CatalogValidation.text(reason,1000,"Lý do khóa / mở tài khoản");Sql.transaction(source,c->{manager(c,actor);var before=target(c,user);current(before,version);String status=Sql.text(before.get("status"));if(lock){if("ADMIN_LOCKED".equals(status))throw FieldValidationException.field("form","Tài khoản đã khóa.");Sql.update(c,"UPDATE users SET status_before_lock=status,status='ADMIN_LOCKED',lock_reason=?,locked_by=?,admin_locked_at=?,version=version+1 WHERE id=?",why,actor,Timestamp.from(clock.instant()),user);}
        else{if(!"ADMIN_LOCKED".equals(status))throw FieldValidationException.field("form","Tài khoản chưa bị khóa.");String restored=Sql.text(before.get("status_before_lock"));if(!Set.of("ACTIVE","DISABLED","PENDING_ACTIVATION").contains(restored))restored="DISABLED";Sql.update(c,"UPDATE users SET status=?,status_before_lock=NULL,lock_reason=NULL,locked_by=NULL,admin_locked_at=NULL,failed_login_count=0,locked_until=NULL,version=version+1 WHERE id=?",restored,user);}
        Sql.update(c,"UPDATE dealer_accounts SET version=version+1 WHERE user_id=?",user);new JdbcSessionRepository().revokeAllForUser(c,user,clock.instant(),"PORTAL_ACCOUNT_STATUS_CHANGED");AuditService.record(c,actor,lock?"PORTAL_ACCOUNT_LOCKED":"PORTAL_ACCOUNT_UNLOCKED","PORTAL_ACCOUNT",user,Map.of("status",status),Map.of("status",Sql.one(c,"SELECT status FROM users WHERE id=?",user).get("status"),"reason",why));return null;});}
    private String beginMail(long actor,long dealer,String username,String operation){return Sql.transaction(source,c->{String id=UUID.randomUUID().toString();try{Sql.update(c,"INSERT INTO portal_mail_attempts(id,actor_id,dealer_id,username_normalized,operation) VALUES(?,?,?,?,?)",id,actor,dealer,username,operation);}catch(SQLException e){if(e.getErrorCode()==1062)throw FieldValidationException.field("email","Lần gửi trước chưa rõ kết quả. Cần kiểm tra SMTP/QA trước khi gửi lại.");throw e;}return id;});}
    private void failedMail(String attempt,Throwable failure){if(attempt!=null)Sql.transaction(source,c->{Sql.update(c,"UPDATE portal_mail_attempts SET state=?,finished_at=? WHERE id=? AND state='STARTED'",MailDeliveryFailure.isDefinitive(failure)?"FAILED":"REVIEW",Timestamp.from(clock.instant()),attempt);return null;});}
    public long create(long actor,long dealer,String username,String email,String name,String phone){var command=new UserAccountCommand(username,email,name,phone,"DEALER",UserStatus.PENDING_ACTIVATION,0);var errors=new UserAccountValidator().validate(command);if(!errors.isEmpty())throw new FieldValidationException(errors);String[] attempt={null};
        try{return Sql.transaction(source,c->{var a=manager(c,actor);DealerService.scoped(c,actor,a,dealer,true);if(activation==null)throw new IllegalStateException("Chưa cấu hình email kích hoạt.");String password=new TemporaryPasswordGenerator().generate();long id;
            try{id=new JdbcUserManagementRepository().create(c,command,hasher.hash(password),clock.instant());}catch(SQLException e){if(e.getErrorCode()==1062)throw FieldValidationException.field("username","Tên đăng nhập, email hoặc điện thoại đã được dùng.");throw e;}
            Sql.update(c,"UPDATE users SET account_kind='DEALER' WHERE id=?",id);Sql.update(c,"INSERT INTO user_roles(user_id,role_id) SELECT ?,id FROM roles WHERE code='DEALER'",id);Sql.update(c,"INSERT INTO dealer_accounts(user_id,dealer_id,issued_by) VALUES(?,?,?)",id,dealer,actor);String token=activation.issue(c,id);
            AuditService.record(c,actor,"PORTAL_ACCOUNT_CREATED","PORTAL_ACCOUNT",id,null,Map.of("username",command.username(),"dealer_id",dealer,"status","PENDING_ACTIVATION"));attempt[0]=beginMail(actor,dealer,command.normalizedUsername(),"CREATE");activation.send(command.email(),command.fullName(),command.username(),password,token);
            Sql.update(c,"UPDATE portal_mail_attempts SET state='SUCCEEDED',user_id=?,finished_at=? WHERE id=?",id,Timestamp.from(clock.instant()),attempt[0]);return id;});}
        catch(RuntimeException e){failedMail(attempt[0],e);if(attempt[0]!=null)throw FieldValidationException.field("email",MailDeliveryFailure.isDefinitive(e)?"SMTP từ chối: chưa tạo tài khoản, có thể thử lại.":"Chưa rõ kết quả gửi. Không tự gửi lại; cần kiểm tra email trước.");throw e;}
    }
    public void resend(long actor,long user,long version){String[] attempt={null};try{Sql.transaction(source,c->{manager(c,actor);var before=target(c,user);current(before,version);if(!"PENDING_ACTIVATION".equals(before.get("status")))throw FieldValidationException.field("form","Chỉ gửi lại cho tài khoản đang chờ kích hoạt.");if(activation==null)throw new IllegalStateException("Chưa cấu hình email kích hoạt.");String password=new TemporaryPasswordGenerator().generate(),token=activation.issue(c,user);Sql.update(c,"UPDATE users SET password_hash=?,must_change_password=TRUE,version=version+1 WHERE id=?",hasher.hash(password),user);Sql.update(c,"UPDATE dealer_accounts SET version=version+1 WHERE user_id=?",user);
        AuditService.record(c,actor,"PORTAL_ACTIVATION_RESENT","PORTAL_ACCOUNT",user,null,Map.of("dealer_id",before.get("dealer_id")));new JdbcSessionRepository().revokeAllForUser(c,user,clock.instant(),"PORTAL_ACTIVATION_RESENT");attempt[0]=beginMail(actor,Sql.id(before.get("dealer_id")),Sql.text(before.get("username_normalized")),"RESEND");activation.send(Sql.text(before.get("email")),Sql.text(before.get("full_name")),Sql.text(before.get("username")),password,token);Sql.update(c,"UPDATE portal_mail_attempts SET state='SUCCEEDED',user_id=?,finished_at=? WHERE id=?",user,Timestamp.from(clock.instant()),attempt[0]);return null;});}catch(RuntimeException e){failedMail(attempt[0],e);if(attempt[0]!=null)throw FieldValidationException.field("email",MailDeliveryFailure.isDefinitive(e)?"SMTP từ chối, mật khẩu/token cũ được giữ.":"Chưa rõ kết quả gửi lại, cần kiểm tra email trước khi thử tiếp.");throw e;}}
    public PageResult<Map<String,Object>> linkHistory(long actor,long user,PageRequest request){return Sql.transaction(source,c->{manager(c,actor);target(c,user);long total=Sql.id(Sql.one(c,"SELECT COUNT(*) total FROM dealer_account_link_history WHERE user_id=?",user).get("total"));var p=request.clamp(total);return new PageResult<>(Sql.query(c,"SELECT h.reason,h.changed_at,h.account_version,d1.code old_code,d1.name old_name,d2.code new_code,d2.name new_name,u.full_name actor_name FROM dealer_account_link_history h JOIN dealers d1 ON d1.id=h.old_dealer_id JOIN dealers d2 ON d2.id=h.new_dealer_id JOIN users u ON u.id=h.actor_id WHERE h.user_id=? ORDER BY h.id DESC LIMIT ? OFFSET ?",user,p.pageSize(),p.offset()),total,p.page(),p.pageSize());});}
}
