package vn.codegym.salesinventory.service;
import java.math.*;import java.time.*;import java.sql.*;import java.util.*;import javax.sql.DataSource;import vn.codegym.salesinventory.dao.Sql;import vn.codegym.salesinventory.validation.CatalogValidation;import vn.codegym.salesinventory.security.Access;
public final class PricingService {
 private final DataSource source;public PricingService(DataSource source){this.source=source;}
 public record Quote(long itemId,long versionId,long productId,BigDecimal sellingPrice,BigDecimal floorPrice,LocalDate date){public boolean requiresApproval(BigDecimal proposed){return proposed.compareTo(floorPrice)<0;}}
 private static void dates(LocalDate from,LocalDate to){if(from==null||to==null||to.isBefore(from))throw new IllegalArgumentException("Ngày kết thúc phải từ ngày bắt đầu trở đi.");}
 public List<Map<String,Object>> groups(){return Sql.transaction(source,c->Sql.query(c,"SELECT id,code,name FROM customer_groups ORDER BY id"));}
 public List<Map<String,Object>> versions(long actor){new AccessService(source).load(actor).require("PRICE_READ");return Sql.transaction(source,c->Sql.query(c,"SELECT v.id,v.group_id,v.name,v.valid_from,v.valid_to,v.parent_id,v.revision,g.name group_name,EXISTS(SELECT 1 FROM price_order_references r WHERE r.version_id=v.id) used FROM price_versions v JOIN customer_groups g ON g.id=v.group_id ORDER BY v.valid_from DESC,v.id DESC"));}
 public List<Map<String,Object>> items(long actor,long version){new AccessService(source).load(actor).require("PRICE_READ");return Sql.transaction(source,c->Sql.query(c,"SELECT i.id,i.product_id,p.sku,p.name,i.selling_price,i.floor_price FROM price_items i JOIN products p ON p.id=i.product_id WHERE version_id=? ORDER BY p.sku",version));}
 private static void lockGroup(Connection c,long group)throws SQLException{Sql.one(c,"SELECT id FROM customer_groups WHERE id=? FOR UPDATE",group);}
 private static void unused(Connection c,long version)throws SQLException{if(!Sql.query(c,"SELECT id FROM price_order_references WHERE version_id=? LIMIT 1 FOR UPDATE",version).isEmpty())throw new IllegalArgumentException("Phiên bản đã được dùng. Hãy kế thừa thành phiên bản mới.");}
 private static void overlap(Connection c,long group,long product,LocalDate from,LocalDate to,long excluded)throws SQLException{if(!Sql.query(c,"SELECT v.id FROM price_versions v JOIN price_items i ON i.version_id=v.id WHERE v.group_id=? AND i.product_id=? AND v.id<>? AND v.valid_from<=? AND v.valid_to>=? LIMIT 1 FOR UPDATE",group,product,excluded,to,from).isEmpty())throw new IllegalArgumentException("Thời gian giá chồng nhau cho cùng nhóm khách và SKU.");}
 public long create(long actor,long group,String name,LocalDate from,LocalDate to,Long parent){new AccessService(source).load(actor).require("PRICE_MANAGE");dates(from,to);CatalogValidation.text(name,150,"Tên bảng giá");return Sql.transaction(source,c->{lockGroup(c,group);if(parent!=null){var base=Sql.one(c,"SELECT group_id FROM price_versions WHERE id=?",parent);if(Sql.id(base.get("group_id"))!=group)throw new IllegalArgumentException("Phiên bản kế thừa phải cùng nhóm khách.");for(var item:Sql.query(c,"SELECT product_id FROM price_items WHERE version_id=? FOR UPDATE",parent))overlap(c,group,Sql.id(item.get("product_id")),from,to,0);}long id=Sql.insert(c,"INSERT INTO price_versions(group_id,name,valid_from,valid_to,parent_id) VALUES(?,?,?,?,?)",group,name,from,to,parent);if(parent!=null)Sql.update(c,"INSERT INTO price_items(version_id,product_id,selling_price,floor_price) SELECT ?,product_id,selling_price,floor_price FROM price_items WHERE version_id=?",id,parent);AuditService.record(c,actor,"PRICE_VERSION_CREATED","PRICE_VERSION",id,null,Map.of("group_id",group,"name",name,"valid_from",from,"valid_to",to,"parent_id",parent==null?"":parent));return id;});}
 public void edit(long actor,long id,long revision,String name,LocalDate from,LocalDate to){new AccessService(source).load(actor).require("PRICE_MANAGE");dates(from,to);CatalogValidation.text(name,150,"Tên bảng giá");Sql.transaction(source,c->{long group=Sql.id(Sql.one(c,"SELECT group_id FROM price_versions WHERE id=?",id).get("group_id"));lockGroup(c,group);var before=Sql.one(c,"SELECT id,name,group_id,valid_from,valid_to,revision FROM price_versions WHERE id=? FOR UPDATE",id);unused(c,id);if(Sql.id(before.get("revision"))!=revision)throw new IllegalArgumentException("Bảng giá đã thay đổi. Hãy tải lại.");for(var item:Sql.query(c,"SELECT product_id FROM price_items WHERE version_id=? FOR UPDATE",id))overlap(c,group,Sql.id(item.get("product_id")),from,to,id);Sql.update(c,"UPDATE price_versions SET name=?,valid_from=?,valid_to=?,revision=revision+1 WHERE id=?",name,from,to,id);AuditService.record(c,actor,"PRICE_VERSION_UPDATED","PRICE_VERSION",id,before,Map.of("name",name,"valid_from",from,"valid_to",to));return null;});}
 public void saveItem(long actor,long version,long product,BigDecimal selling,BigDecimal floor){new AccessService(source).load(actor).require("PRICE_MANAGE");CatalogValidation.decimal(selling.toPlainString(),4,false);CatalogValidation.decimal(floor.toPlainString(),4,false);if(selling.compareTo(floor)<0)throw new IllegalArgumentException("Giá bán bảng giá phải từ giá sàn trở lên.");Sql.transaction(source,c->{long group=Sql.id(Sql.one(c,"SELECT group_id FROM price_versions WHERE id=?",version).get("group_id"));lockGroup(c,group);var v=Sql.one(c,"SELECT valid_from,valid_to FROM price_versions WHERE id=? FOR UPDATE",version);unused(c,version);Sql.one(c,"SELECT id FROM products WHERE id=?",product);overlap(c,group,product,LocalDate.parse(v.get("valid_from").toString()),LocalDate.parse(v.get("valid_to").toString()),version);var found=Sql.query(c,"SELECT id,product_id,selling_price,floor_price FROM price_items WHERE version_id=? AND product_id=? FOR UPDATE",version,product);Map<String,Object> before=found.isEmpty()?null:found.get(0);long item;if(before==null)item=Sql.insert(c,"INSERT INTO price_items(version_id,product_id,selling_price,floor_price) VALUES(?,?,?,?)",version,product,selling,floor);else{item=Sql.id(before.get("id"));Sql.update(c,"UPDATE price_items SET selling_price=?,floor_price=? WHERE id=?",selling,floor,item);}Sql.update(c,"UPDATE price_versions SET revision=revision+1 WHERE id=?",version);AuditService.record(c,actor,"PRICE_ITEM_SAVED","PRICE_ITEM",item,before,Map.of("version_id",version,"product_id",product,"selling_price",selling,"floor_price",floor));return null;});}
 public void deleteItem(long actor,long version,long item){new AccessService(source).load(actor).require("PRICE_MANAGE");Sql.transaction(source,c->{long group=Sql.id(Sql.one(c,"SELECT group_id FROM price_versions WHERE id=?",version).get("group_id"));lockGroup(c,group);unused(c,version);var before=Sql.one(c,"SELECT id,version_id,product_id,selling_price,floor_price FROM price_items WHERE id=? AND version_id=?",item,version);Sql.update(c,"DELETE FROM price_items WHERE id=?",item);Sql.update(c,"UPDATE price_versions SET revision=revision+1 WHERE id=?",version);AuditService.record(c,actor,"PRICE_ITEM_DELETED","PRICE_ITEM",item,before,null);return null;});}
 public Quote quote(long actor,long group,long product,LocalDate date){var a=new AccessService(source).load(actor);a.require("PRICE_READ");return Sql.transaction(source,c->quote(c,a,group,product,date));}
 /** Đơn hàng gọi quote và snapshot trên cùng connection để khóa phiên bản đã dùng. */
 public static Quote quote(Connection c,Access a,long group,long product,LocalDate date)throws SQLException{a.require("PRICE_READ");Sql.one(c,"SELECT id FROM customer_groups WHERE id=? FOR SHARE",group);var row=Sql.one(c,"SELECT i.id,i.version_id,i.selling_price,i.floor_price FROM price_items i JOIN price_versions v ON v.id=i.version_id WHERE v.group_id=? AND i.product_id=? AND v.valid_from<=? AND v.valid_to>=?",group,product,date,date);return new Quote(Sql.id(row.get("id")),Sql.id(row.get("version_id")),product,(BigDecimal)row.get("selling_price"),(BigDecimal)row.get("floor_price"),date);}
 public static long snapshot(Connection c,String orderReference,Quote q)throws SQLException{return Sql.insert(c,"INSERT INTO price_order_references(order_reference,price_item_id,version_id,selling_price,floor_price) VALUES(?,?,?,?,?)",CatalogValidation.text(orderReference,100,"Tham chiếu đơn"),q.itemId,q.versionId,q.sellingPrice,q.floorPrice);}
}

