package vn.codegym.salesinventory.service;
import java.util.*;import java.math.*;import java.sql.*;import javax.sql.DataSource;import vn.codegym.salesinventory.dao.Sql;import vn.codegym.salesinventory.validation.CatalogValidation;import vn.codegym.salesinventory.security.Access;
public final class ProductService {
 private final DataSource source;public ProductService(DataSource source){this.source=source;}
 public record Input(String sku,String name,long category,String baseUnit,String packaging,BigDecimal cost,String imageKey,String status,long version) {}
 public static void validate(Input in){CatalogValidation.code(in.sku,64);CatalogValidation.text(in.name,200,"Tên sản phẩm");CatalogValidation.text(in.baseUnit,50,"Đơn vị cơ sở");if(in.packaging.length()>250)throw new IllegalArgumentException("Quy cách tối đa 250 ký tự.");if(in.cost!=null)CatalogValidation.decimal(in.cost.toPlainString(),4,false);if(!Set.of("ACTIVE","DISCONTINUED").contains(in.status))throw new IllegalArgumentException("Trạng thái sản phẩm không hợp lệ.");if(in.imageKey!=null&&!in.imageKey.matches("[a-f0-9-]{36}"))throw new IllegalArgumentException("Ảnh không hợp lệ.");}
 public static String columns(Access a){return "p.id,p.sku,p.name,p.category_id,p.base_unit,p.packaging,p.image_key,p.status,p.version,c.name category_name"+(a.allows("COST_READ")?",p.cost_price":"");}
 public List<Map<String,Object>> list(long actor,String keyword,Long category,String status,int page){var a=new AccessService(source).load(actor);a.require("CATALOG_READ");if(page<1||page>100000)throw new IllegalArgumentException("Trang không hợp lệ.");return Sql.transaction(source,c->Sql.query(c,"SELECT "+columns(a)+" FROM products p JOIN categories c ON c.id=p.category_id WHERE (p.sku LIKE ? OR p.name LIKE ?) AND (? IS NULL OR p.category_id=?) AND (?='' OR p.status=?) ORDER BY p.sku LIMIT 100 OFFSET ?","%"+keyword+"%","%"+keyword+"%",category,category,status,status,(page-1)*100));}
 public Map<String,Object> find(long actor,long id){var a=new AccessService(source).load(actor);a.require("CATALOG_READ");return Sql.transaction(source,c->Sql.one(c,"SELECT "+columns(a)+" FROM products p JOIN categories c ON c.id=p.category_id WHERE p.id=?",id));}
 public long save(long actor,long id,Input in){var a=new AccessService(source).load(actor);a.require("PRODUCT_MANAGE");if(in.cost!=null)a.require("COST_WRITE");validate(in);return Sql.transaction(source,c->save(c,a,actor,id,in));}
 public static long save(Connection c,Access a,long actor,long id,Input in)throws SQLException {
  a.require("PRODUCT_MANAGE");if(in.cost!=null)a.require("COST_WRITE");validate(in);Sql.one(c,"SELECT name FROM catalog_locks WHERE name='CATEGORY_TREE' FOR UPDATE");Sql.one(c,"SELECT id FROM categories WHERE id=?",in.category);
  Map<String,Object> before=null;BigDecimal cost=in.cost;String image=in.imageKey;
  if(id!=0){before=Sql.one(c,"SELECT id,sku,name,category_id,base_unit,packaging,cost_price,image_key,status,version FROM products WHERE id=? FOR UPDATE",id);if(Sql.id(before.get("version"))!=in.version)throw new IllegalArgumentException("Sản phẩm đã thay đổi. Hãy tải lại.");if(!Sql.text(before.get("base_unit")).equals(in.baseUnit)&&(!Sql.query(c,"SELECT product_id FROM product_transaction_references WHERE product_id=? LIMIT 1",id).isEmpty()||hasAlternateUnits(c,id)))throw new IllegalArgumentException("Sản phẩm đã có quy đổi hoặc giao dịch, không thể thay đơn vị cơ sở.");if(cost==null)cost=(BigDecimal)before.get("cost_price");if(image==null)image=Sql.text(before.get("image_key"));if(image.isEmpty())image=null;}
  if(!Sql.query(c,"SELECT id FROM products WHERE sku=? AND id<>?",in.sku,id).isEmpty())throw new IllegalArgumentException("SKU đã tồn tại.");long saved=id;
  if(id==0)saved=Sql.insert(c,"INSERT INTO products(sku,name,category_id,base_unit,packaging,cost_price,image_key,status) VALUES(?,?,?,?,?,?,?,?)",in.sku,in.name,in.category,in.baseUnit,in.packaging,cost,image,in.status);else Sql.update(c,"UPDATE products SET sku=?,name=?,category_id=?,base_unit=?,packaging=?,cost_price=?,image_key=?,status=?,version=version+1 WHERE id=?",in.sku,in.name,in.category,in.baseUnit,in.packaging,cost,image,in.status,id);
  if(tableExists(c,"product_units")){Sql.update(c,"UPDATE product_units SET name=? WHERE product_id=? AND is_base=1",in.baseUnit,saved);Sql.update(c,"INSERT INTO product_units(product_id,name,factor,is_base,warehouse_id) SELECT ?,?,1,1,NULL WHERE NOT EXISTS(SELECT id FROM product_units WHERE product_id=? AND is_base=1)",saved,in.baseUnit,saved);}
  AuditService.record(c,actor,"PRODUCT_SAVED","PRODUCT",saved,before,Sql.one(c,"SELECT id,sku,name,category_id,base_unit,packaging,cost_price,status,version FROM products WHERE id=?",saved));return saved;
 }
 private static boolean tableExists(Connection c,String table)throws SQLException{return !Sql.query(c,"SELECT table_name FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?",table).isEmpty();}
 private static boolean hasAlternateUnits(Connection c,long id)throws SQLException{return tableExists(c,"product_units")&&!Sql.query(c,"SELECT id FROM product_units WHERE product_id=? AND is_base=0 LIMIT 1",id).isEmpty();}
 public void delete(long actor,long id){new AccessService(source).load(actor).require("PRODUCT_MANAGE");Sql.transaction(source,c->{Sql.one(c,"SELECT name FROM catalog_locks WHERE name='CATEGORY_TREE' FOR UPDATE");var before=Sql.one(c,"SELECT id,sku,name,cost_price FROM products WHERE id=? FOR UPDATE",id);if(!Sql.query(c,"SELECT product_id FROM product_transaction_references WHERE product_id=? LIMIT 1",id).isEmpty())throw new IllegalArgumentException("Sản phẩm đã phát sinh giao dịch. Hãy ngừng kinh doanh.");if(tableExists(c,"price_items")&&!Sql.query(c,"SELECT id FROM price_items WHERE product_id=? LIMIT 1",id).isEmpty())throw new IllegalArgumentException("Sản phẩm đang có bảng giá. Hãy ngừng kinh doanh.");if(tableExists(c,"product_units"))Sql.update(c,"DELETE FROM product_units WHERE product_id=?",id);Sql.update(c,"DELETE FROM products WHERE id=?",id);AuditService.record(c,actor,"PRODUCT_DELETED","PRODUCT",id,before,null);return null;});}
}
