package vn.codegym.salesinventory.service;
import java.util.*;import java.time.*;import java.math.*;import javax.sql.DataSource;import vn.codegym.salesinventory.dao.Sql;import vn.codegym.salesinventory.security.Access;import vn.codegym.salesinventory.validation.CatalogValidation;
public final class ProductImportService {
 public static final List<String> HEADERS=List.of("SKU","Tên sản phẩm","Mã nhóm","Đơn vị cơ sở","Quy cách","Trạng thái");
 private final DataSource source;public ProductImportService(DataSource source){this.source=source;}
 public static List<String> headers(Access a){var h=new ArrayList<>(HEADERS);if(a.allows("COST_WRITE"))h.add("Giá vốn");return h;}
 private static String cell(List<String> row,int col){return col<row.size()?row.get(col):"";}
 private static ProductService.Input input(List<String> row,long category,long version){return new ProductService.Input(cell(row,0),cell(row,1),category,cell(row,3),cell(row,4),cell(row,6).isEmpty()?null:CatalogValidation.decimal(cell(row,6),4,false),null,cell(row,5),version);}
 public ImportPreview preview(long actor,byte[] bytes){var access=new AccessService(source).load(actor);access.require("PRODUCT_MANAGE");var rows=Xlsx.read(bytes);if(rows.isEmpty())throw new IllegalArgumentException("Tệp trống.");var header=rows.get(0).cells();if(header.contains("Giá vốn")&&!access.allows("COST_WRITE"))throw new SecurityException();if(!header.equals(headers(access)))throw new IllegalArgumentException("Tiêu đề phải đúng tệp mẫu theo quyền của bạn.");
  return Sql.transaction(source,c->{Map<String,Long> categories=new HashMap<>();for(var cat:Sql.query(c,"SELECT id,code FROM categories"))categories.put(Sql.text(cat.get("code")).toLowerCase(Locale.ROOT),Sql.id(cat.get("id")));Set<String> existing=new HashSet<>();for(var p:Sql.query(c,"SELECT sku FROM products"))existing.add(Sql.text(p.get("sku")).toLowerCase(Locale.ROOT));Set<String> seen=new HashSet<>();var lines=new ArrayList<ImportPreview.Line>();for(var row:rows.subList(1,rows.size())){if(row.cells().stream().allMatch(String::isBlank))continue;String sku=cell(row.cells(),0).toLowerCase(Locale.ROOT),error=row.error();try{if(!error.isEmpty())throw new IllegalArgumentException(error);if(row.cells().size()>header.size())throw new IllegalArgumentException("Dòng có cột ngoài tệp mẫu.");Long category=categories.get(cell(row.cells(),2).toLowerCase(Locale.ROOT));if(category==null)throw new IllegalArgumentException("Mã nhóm không tồn tại.");var in=input(row.cells(),category,0);ProductService.validate(in);if(!seen.add(sku))throw new IllegalArgumentException("SKU trùng trong tệp.");}catch(IllegalArgumentException e){error=e.getMessage();}lines.add(new ImportPreview.Line(row.number(),row.cells(),existing.contains(sku)?"Cập nhật":"Tạo mới",error));}return new ImportPreview(actor,lines,Instant.now());});
 }
 public List<ImportPreview.Line> confirm(long actor,ImportPreview preview,String token){var a=new AccessService(source).load(actor);a.require("PRODUCT_MANAGE");boolean hasCost=preview.getLines().stream().anyMatch(row->row.cells().size()>6);if(hasCost)a.require("COST_WRITE");preview.claim(actor,token,Instant.now());var result=new ArrayList<ImportPreview.Line>();for(var row:preview.getLines()){if(!row.isValid()){result.add(row);continue;}String error="";try{var fresh=new AccessService(source).load(actor);fresh.require("PRODUCT_MANAGE");if(hasCost)fresh.require("COST_WRITE");Sql.transaction(source,c->{long category=Sql.id(Sql.one(c,"SELECT id FROM categories WHERE code=?",cell(row.cells(),2)).get("id"));var found=Sql.query(c,"SELECT id,version FROM products WHERE sku=? FOR UPDATE",cell(row.cells(),0));boolean update=!found.isEmpty();if(update!=row.operation().equals("Cập nhật"))throw new IllegalArgumentException("SKU đã thay đổi sau xem trước. Hãy tải lại tệp.");long id=update?Sql.id(found.get(0).get("id")):0,version=update?Sql.id(found.get(0).get("version")):0;ProductService.save(c,fresh,actor,id,input(row.cells(),category,version));return null;});}catch(RuntimeException e){error=e instanceof IllegalArgumentException?e.getMessage():e instanceof SecurityException?"Quyền nhập đã bị thu hồi.":"Không thể lưu dòng này; dữ liệu đã được hoàn tác.";}result.add(new ImportPreview.Line(row.number(),row.cells(),row.operation(),error));}if(hasCost)new AccessService(source).load(actor).require("COST_READ");return result;}
}
