package vn.codegym.salesinventory.service;
import java.util.*;import javax.sql.DataSource;import vn.codegym.salesinventory.dao.Sql;import vn.codegym.salesinventory.validation.*;
public final class SupplierService {
 private final DataSource source;public SupplierService(DataSource source){this.source=source;}
 public record Input(String code,String name,String taxCode,String contact,String phone,String terms,long warehouse,String status,long version) {}
 public List<Map<String,Object>> list(long actor,String query){var a=new AccessService(source).load(actor);a.require("CATALOG_READ");return Sql.transaction(source,c->Sql.query(c,"SELECT s.id,s.code,s.name,s.tax_code,s.contact_name,s.contact_phone,s.payment_terms,s.warehouse_id,s.status,s.version,w.name warehouse_name FROM suppliers s JOIN warehouses w ON w.id=s.warehouse_id WHERE (s.code LIKE ? OR s.name LIKE ?)"+(a.allows("WAREHOUSE_MANAGE")?" AND EXISTS(SELECT 1 FROM user_warehouses uw WHERE uw.user_id=? AND uw.warehouse_id=s.warehouse_id)":"")+" ORDER BY s.name LIMIT 1000",a.allows("WAREHOUSE_MANAGE")?new Object[]{"%"+query+"%","%"+query+"%",actor}:new Object[]{"%"+query+"%","%"+query+"%"}));}
 public long save(long actor,long id,Input in){var a=new AccessService(source).load(actor);a.require("WAREHOUSE_MANAGE");if(!a.managesWarehouse(in.warehouse))throw new SecurityException();CatalogValidation.code(in.code,50);CatalogValidation.text(in.name,200,"Tên nhà cung cấp");CatalogValidation.text(in.contact,150,"Người liên hệ");CatalogValidation.text(in.terms,250,"Điều khoản thanh toán");String phone=PhoneNumber.normalize(in.phone);if(!in.taxCode.matches("[0-9]{10}(-?[0-9]{3})?"))throw new IllegalArgumentException("Mã số thuế gồm 10 hoặc 13 chữ số.");if(!Set.of("ACTIVE","DISCONTINUED").contains(in.status))throw new IllegalArgumentException("Trạng thái không hợp lệ.");return Sql.transaction(source,c->{Map<String,Object> before=null;if(id!=0){before=Sql.one(c,"SELECT id,code,name,tax_code,contact_name,contact_phone,payment_terms,warehouse_id,status,version FROM suppliers WHERE id=? FOR UPDATE",id);if(!a.managesWarehouse(Sql.id(before.get("warehouse_id"))))throw new SecurityException();if(Sql.id(before.get("version"))!=in.version)throw new IllegalArgumentException("Nhà cung cấp đã thay đổi. Hãy tải lại.");}if(!Sql.query(c,"SELECT id FROM suppliers WHERE code=? AND id<>?",in.code,id).isEmpty())throw new IllegalArgumentException("Mã nhà cung cấp đã tồn tại.");long saved=id;if(id==0)saved=Sql.insert(c,"INSERT INTO suppliers(code,name,tax_code,contact_name,contact_phone,payment_terms,warehouse_id,status) VALUES(?,?,?,?,?,?,?,?)",in.code,in.name,in.taxCode,in.contact,phone,in.terms,in.warehouse,in.status);else Sql.update(c,"UPDATE suppliers SET code=?,name=?,tax_code=?,contact_name=?,contact_phone=?,payment_terms=?,warehouse_id=?,status=?,version=version+1 WHERE id=?",in.code,in.name,in.taxCode,in.contact,phone,in.terms,in.warehouse,in.status,id);AuditService.record(c,actor,"SUPPLIER_SAVED","SUPPLIER",saved,before,Sql.one(c,"SELECT id,code,name,tax_code,contact_name,contact_phone,payment_terms,warehouse_id,status,version FROM suppliers WHERE id=?",saved));return saved;});}
 public void delete(long actor,long id){var a=new AccessService(source).load(actor);a.require("WAREHOUSE_MANAGE");Sql.transaction(source,c->{var before=Sql.one(c,"SELECT id,code,name,warehouse_id,status FROM suppliers WHERE id=? FOR UPDATE",id);if(!a.managesWarehouse(Sql.id(before.get("warehouse_id"))))throw new SecurityException();if(!Sql.query(c,"SELECT supplier_id FROM supplier_receipt_references WHERE supplier_id=? LIMIT 1",id).isEmpty())throw new IllegalArgumentException("Nhà cung cấp đã có phiếu nhập. Hãy ngừng giao dịch.");Sql.update(c,"DELETE FROM suppliers WHERE id=?",id);AuditService.record(c,actor,"SUPPLIER_DELETED","SUPPLIER",id,before,null);return null;});}
}
