package vn.codegym.salesinventory.service;
import java.math.*;import java.sql.*;import java.util.*;import javax.sql.DataSource;import vn.codegym.salesinventory.dao.Sql;import vn.codegym.salesinventory.validation.CatalogValidation;import vn.codegym.salesinventory.security.Access;
public final class UnitService {
 private final DataSource source;public UnitService(DataSource source){this.source=source;}
 public record Conversion(long productId,long unitId,String unitName,BigDecimal quantity,BigDecimal factor,long version,BigDecimal baseQuantity) {}
 public List<Map<String,Object>> list(long actor,long product){var a=new AccessService(source).load(actor);a.require("CATALOG_READ");return Sql.transaction(source,c->{var rows=Sql.query(c,"SELECT u.id,u.product_id,u.name,u.factor,u.version,u.is_base,u.warehouse_id,w.name warehouse_name FROM product_units u LEFT JOIN warehouses w ON w.id=u.warehouse_id WHERE product_id=? ORDER BY is_base DESC,u.name",product);return rows.stream().filter(row->!a.allows("WAREHOUSE_MANAGE")||row.get("warehouse_id")==null||a.managesWarehouse(Sql.id(row.get("warehouse_id")))).toList();});}
 public long save(long actor,long id,long product,String name,BigDecimal factor,long warehouse,long version){var a=new AccessService(source).load(actor);a.require("WAREHOUSE_MANAGE");if(!a.managesWarehouse(warehouse))throw new SecurityException();CatalogValidation.text(name,50,"Đơn vị");CatalogValidation.decimal(factor.toPlainString(),6,true);return Sql.transaction(source,c->{Sql.one(c,"SELECT id FROM products WHERE id=? FOR UPDATE",product);Map<String,Object> before=null;if(id!=0){before=Sql.one(c,"SELECT id,product_id,name,factor,version,is_base,warehouse_id FROM product_units WHERE id=? FOR UPDATE",id);if(Boolean.TRUE.equals(before.get("is_base"))||"1".equals(String.valueOf(before.get("is_base"))))throw new IllegalArgumentException("Đơn vị cơ sở luôn có hệ số 1 và không thể sửa.");if(!a.managesWarehouse(Sql.id(before.get("warehouse_id"))))throw new SecurityException();if(Sql.id(before.get("version"))!=version||Sql.id(before.get("product_id"))!=product)throw new IllegalArgumentException("Đơn vị đã thay đổi.");}if(!Sql.query(c,"SELECT id FROM product_units WHERE product_id=? AND name=? AND id<>?",product,name,id).isEmpty())throw new IllegalArgumentException("Đơn vị đã tồn tại trên SKU.");long saved=id;if(id==0)saved=Sql.insert(c,"INSERT INTO product_units(product_id,name,factor,warehouse_id) VALUES(?,?,?,?)",product,name,factor,warehouse);else Sql.update(c,"UPDATE product_units SET name=?,factor=?,warehouse_id=?,version=version+1 WHERE id=?",name,factor,warehouse,id);AuditService.record(c,actor,"UNIT_SAVED","UNIT",saved,before,Map.of("product_id",product,"name",name,"factor",factor,"warehouse_id",warehouse));return saved;});}
 public Conversion convert(long actor,long unit,BigDecimal quantity){var a=new AccessService(source).load(actor);a.require("CATALOG_READ");CatalogValidation.decimal(quantity.toPlainString(),6,false);return Sql.transaction(source,c->convert(c,a,unit,quantity));}
 public static Conversion convert(Connection c,Access a,long unit,BigDecimal quantity)throws SQLException{var u=Sql.one(c,"SELECT id,product_id,name,factor,version,warehouse_id FROM product_units WHERE id=? FOR SHARE",unit);if(a.allows("WAREHOUSE_MANAGE")&&u.get("warehouse_id")!=null&&!a.managesWarehouse(Sql.id(u.get("warehouse_id"))))throw new SecurityException();BigDecimal factor=(BigDecimal)u.get("factor");return new Conversion(Sql.id(u.get("product_id")),unit,Sql.text(u.get("name")),quantity,factor,Sql.id(u.get("version")),quantity.multiply(factor));}
 /** Module giao dịch gọi trong cùng connection của đơn hàng/phiếu kho. */
 public static long snapshot(Connection c,String reference,Conversion value)throws SQLException{return Sql.insert(c,"INSERT INTO conversion_snapshots(reference_id,unit_id,product_id,unit_name,factor,unit_version,quantity,base_quantity) VALUES(?,?,?,?,?,?,?,?)",CatalogValidation.text(reference,100,"Tham chiếu"),value.unitId,value.productId,value.unitName,value.factor,value.version,value.quantity,value.baseQuantity);}
 public void delete(long actor,long id){var a=new AccessService(source).load(actor);a.require("WAREHOUSE_MANAGE");Sql.transaction(source,c->{var u=Sql.one(c,"SELECT id,name,factor,warehouse_id FROM product_units WHERE id=? FOR UPDATE",id);if(u.get("warehouse_id")==null)throw new IllegalArgumentException("Không thể xóa đơn vị cơ sở.");if(!a.managesWarehouse(Sql.id(u.get("warehouse_id"))))throw new SecurityException();if(!Sql.query(c,"SELECT id FROM conversion_snapshots WHERE unit_id=? LIMIT 1",id).isEmpty())throw new IllegalArgumentException("Đơn vị đã được tham chiếu, không thể xóa.");Sql.update(c,"DELETE FROM product_units WHERE id=?",id);AuditService.record(c,actor,"UNIT_DELETED","UNIT",id,u,null);return null;});}
}
