<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html><html lang="vi"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Điểm giao hàng</title><%@ include file="../fragments/assets.jspf" %></head><body class="app-page"><%@ include file="../fragments/sidebar.jspf" %><%@ include file="../fragments/topbar.jspf" %><main class="page-body app-content catalog-page">
<div class="page-heading"><div><h1>Điểm giao hàng</h1><p><c:out value="${dealer.code}"/> — <c:out value="${dealer.name}"/></p></div><a class="button button-secondary" href="${pageContext.request.contextPath}/dealers">Danh sách đại lý</a></div>
<c:if test="${param.notice == 'saved'}"><p class="alert alert-success" role="status">Đã lưu điểm giao hàng.</p></c:if><c:if test="${not empty errors.form}"><p class="alert alert-error" role="alert"><c:out value="${errors.form}"/></p></c:if>
<form method="get" class="filter-form"><input type="hidden" name="dealer" value="${dealer.id}"><label>Tìm địa chỉ, người nhận, điện thoại <input name="q" value="<c:out value='${param.q}'/>" maxlength="150"></label><button class="button button-primary">Tìm</button></form>
<c:if test="${access.allows('DEALER_ADDRESS_MANAGE')}"><details id="editor" class="content-panel disclosure editor" ${not empty edit or not empty errors or param['new']=='1' ? 'open' : ''}><summary>${empty edit.id ? 'Thêm điểm giao hàng' : 'Sửa điểm giao hàng'}</summary><form method="post" class="account-form dealer-profile-form">
<input type="hidden" name="_csrf" value="<c:out value='${csrfToken}'/>"><input type="hidden" name="dealer" value="${dealer.id}"><input type="hidden" name="dealerVersion" value="${dealer.version}"><input type="hidden" name="id" value="<c:out value='${edit.id}'/>"><input type="hidden" name="version" value="<c:out value='${edit.version}'/>">
<label class="field">Địa chỉ giao hàng <input name="address" required maxlength="500" value="<c:out value='${edit.address}'/>" aria-invalid="${not empty errors.address}"><span class="field-error"><c:out value="${errors.address}"/></span></label>
<label class="field">Người nhận <input name="recipient" required maxlength="150" value="<c:out value='${edit.recipient}'/>" aria-invalid="${not empty errors.recipient}"><span class="field-error"><c:out value="${errors.recipient}"/></span></label>
<label class="field">Điện thoại <input name="phone" type="tel" required maxlength="30" value="<c:out value='${edit.phone}'/>" aria-invalid="${not empty errors.phone}"><span class="field-error"><c:out value="${errors.phone}"/></span></label>
<label class="field">Ghi chú đường đi <input name="directions" maxlength="1000" value="<c:out value='${edit.directions}'/>" aria-invalid="${not empty errors.directions}"><span class="field-error"><c:out value="${errors.directions}"/></span></label>
<label class="field">Trạng thái <select name="status"><option value="ACTIVE">Đang sử dụng</option><option value="DISCONTINUED" ${edit.status=='DISCONTINUED' ? 'selected' : ''}>Ngừng sử dụng</option></select><span class="field-error"><c:out value="${errors.status}"/></span></label>
<label class="checkbox-field"><input type="checkbox" name="is_default" value="1" ${edit.is_default ? 'checked' : ''}>Điểm mặc định <span class="field-error"><c:out value="${errors.defaultPoint}"/></span><small>Điểm đầu tiên đang sử dụng tự trở thành mặc định.</small></label>
<div class="form-actions"><button class="button button-primary">Lưu điểm giao</button><a class="button button-secondary" href="?dealer=${dealer.id}">Hủy</a></div></form></details></c:if>
<div class="table-wrap"><table><thead><tr><th>Địa chỉ / ghi chú</th><th>Người nhận</th><th>Điện thoại</th><th>Mặc định</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><c:forEach items="${addresses}" var="a"><tr><td><c:out value="${a.address}"/><br><small><c:out value="${a.directions}"/></small></td><td><c:out value="${a.recipient}"/></td><td><c:out value="${a.phone}"/></td><td>${a.is_default ? 'Mặc định' : '—'}</td><td>${a.status=='ACTIVE' ? 'Đang sử dụng' : 'Ngừng sử dụng'}</td><td><c:if test="${access.allows('DEALER_ADDRESS_MANAGE')}"><a href="?dealer=${dealer.id}&amp;id=${a.id}#editor">Sửa / đổi mặc định</a></c:if></td></tr></c:forEach><c:if test="${empty addresses}"><tr><td colspan="6" class="empty-state">Chưa có điểm giao phù hợp. Hãy thêm điểm giao trước khi gửi đơn.</td></tr></c:if></tbody></table></div><%@ include file="../fragments/pagination.jspf" %></main></body></html>
