<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html><html lang="vi"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hồ sơ đại lý</title><%@ include file="../fragments/assets.jspf" %></head><body class="app-page"><%@ include file="../fragments/sidebar.jspf" %><%@ include file="../fragments/topbar.jspf" %>
<main class="page-body app-content catalog-page"><div class="page-heading"><div><h1>Hồ sơ đại lý</h1><p>Danh sách khách hàng chuẩn, nhóm bảng giá và phụ trách chính.</p></div><c:if test="${access.allows('DEALER_MANAGE')}"><a class="button button-primary" href="?new=1#editor" data-editor="editor">＋ Thêm đại lý</a></c:if></div>
<c:if test="${param.notice == 'saved'}"><p class="alert alert-success" role="status">Đã lưu thay đổi.</p></c:if>
<c:if test="${not empty errors.form}"><p class="alert alert-error" role="alert"><c:out value="${errors.form}"/></p></c:if>
<form method="get" class="filter-form"><label>Tìm mã, tên, mã số thuế, điện thoại <input name="q" maxlength="150" value="<c:out value='${param.q}'/>"></label><input type="hidden" name="pageSize" value="${pagination.pageSize}"><button class="button button-primary">Tìm</button><a class="button button-secondary" href="${pageContext.request.contextPath}/dealers">Bỏ bộ lọc</a></form>
<c:if test="${access.allows('DEALER_MANAGE')}"><details id="editor" class="content-panel disclosure editor" ${not empty edit.id or not empty errors or param['new']=='1' ? 'open' : ''}><summary>${empty edit.id ? 'Thêm đại lý' : 'Sửa hồ sơ đại lý'}</summary>
<form method="post" class="account-form dealer-profile-form"><input type="hidden" name="_csrf" value="<c:out value='${csrfToken}'/>"><input type="hidden" name="id" value="<c:out value='${edit.id}'/>"><input type="hidden" name="version" value="<c:out value='${edit.version}'/>"><input type="hidden" name="q" value="<c:out value='${param.q}'/>"><input type="hidden" name="page" value="${pagination.page}"><input type="hidden" name="pageSize" value="${pagination.pageSize}">
<label class="field">Mã đại lý <input name="code" required maxlength="50" value="<c:out value='${edit.code}'/>" aria-invalid="${not empty errors.code}" aria-describedby="code-error"><span id="code-error" class="field-error"><c:out value="${errors.code}"/></span></label>
<label class="field">Tên đại lý <input name="name" required maxlength="200" value="<c:out value='${edit.name}'/>" aria-invalid="${not empty errors.name}" aria-describedby="name-error"><span id="name-error" class="field-error"><c:out value="${errors.name}"/></span></label>
<label class="field">Mã số thuế <input name="taxCode" maxlength="14" value="<c:out value='${edit.tax_code}'/>" aria-invalid="${not empty errors.taxCode}" aria-describedby="taxCode-error"><span id="taxCode-error" class="field-error"><c:out value="${errors.taxCode}"/></span></label>
<label class="field">Điện thoại <input name="phone" type="tel" required maxlength="30" value="<c:out value='${edit.phone}'/>" aria-invalid="${not empty errors.phone}" aria-describedby="phone-error"><span id="phone-error" class="field-error"><c:out value="${errors.phone}"/></span></label>
<label class="field">Nhóm bảng giá <select name="group" required aria-invalid="${not empty errors.group}"><option value="">Chọn nhóm</option><c:forEach items="${groups}" var="g"><option value="${g.id}" ${edit.group_id == g.id.toString() ? 'selected' : ''}><c:out value="${g.name}"/></option></c:forEach></select><span class="field-error"><c:out value="${errors.group}"/></span></label>
<label class="field">Khu vực <select name="territory" required aria-invalid="${not empty errors.territory}"><option value="">Chọn khu vực</option><c:forEach items="${territories}" var="t"><option value="${t.id}" ${edit.territory_id == t.id.toString() ? 'selected' : ''}><c:out value="${t.code}"/> — <c:out value="${t.name}"/></option></c:forEach></select><span class="field-error"><c:out value="${errors.territory}"/></span></label>
<label class="field">Phụ trách chính <select name="staff" required aria-invalid="${not empty errors.staff}"><option value="">Chọn nhân viên kinh doanh</option><c:forEach items="${staff}" var="u"><option value="${u.id}" ${edit.primary_staff_id == u.id.toString() ? 'selected' : ''}><c:out value="${u.code}"/> — <c:out value="${u.name}"/></option></c:forEach></select><span class="field-error"><c:out value="${errors.staff}"/></span><c:if test="${not empty edit.id}"><small>Đổi phụ trách qua chức năng bàn giao.</small></c:if></label>
<label class="field">Kho phục vụ <select name="warehouse" aria-invalid="${not empty errors.warehouse}"><option value="">Chưa chọn kho</option><c:forEach items="${warehouses}" var="w"><option value="${w.id}" ${edit.warehouse_id == w.id.toString() ? 'selected' : ''}><c:out value="${w.name}"/> — <c:out value="${w.address}"/></option></c:forEach></select><span class="field-error"><c:out value="${errors.warehouse}"/></span><small>Chưa có kho vẫn lưu nháp; không thể gửi đơn.</small></label>
<label class="field">Trạng thái hồ sơ <select name="status"><option value="ACTIVE">Đang giao dịch</option><option value="DISCONTINUED" ${edit.status == 'DISCONTINUED' ? 'selected' : ''}>Ngừng giao dịch</option></select><span class="field-error"><c:out value="${errors.status}"/></span></label>
<div class="form-actions"><button class="button button-primary">Lưu hồ sơ</button><a class="button button-secondary" href="${pageContext.request.contextPath}/dealers">Hủy</a></div></form></details></c:if>
<div class="table-wrap"><table><thead><tr><th>Mã / đại lý</th><th>Liên hệ</th><th>Nhóm bảng giá</th><th>Khu vực</th><th>Phụ trách / kho</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><c:forEach items="${dealers}" var="d"><tr>
<td><strong><c:out value="${d.code}"/></strong><br><c:out value="${d.name}"/></td><td><c:out value="${d.phone}"/><br>MST: <c:out value="${d.tax_code}"/></td><td><c:out value="${d.group_name}"/></td><td><c:out value="${d.territory_name}"/></td><td><c:out value="${d.staff_name}"/><br><c:out value="${d.warehouse_name}" default="Chưa chọn kho"/></td><td>${d.status == 'ACTIVE' ? 'Đang giao dịch' : 'Ngừng giao dịch'}</td><td>
<a href="${pageContext.request.contextPath}/dealers/addresses?dealer=${d.id}">Điểm giao hàng</a><br><c:if test="${access.allows('DEALER_MANAGE')}"><c:url var="editUrl" value="/dealers"><c:param name="id" value="${d.id}"/><c:param name="q" value="${param.q}"/><c:param name="page" value="${pagination.page}"/><c:param name="pageSize" value="${pagination.pageSize}"/></c:url><a href="${editUrl}#editor">Sửa hồ sơ</a><form method="post" data-confirm="Xóa hồ sơ chưa phát sinh giao dịch?"><input type="hidden" name="_csrf" value="<c:out value='${csrfToken}'/>"><input type="hidden" name="id" value="${d.id}"><input type="hidden" name="version" value="${d.version}"><input type="hidden" name="action" value="delete"><button class="button button-plain">Xóa</button></form></c:if></td></tr></c:forEach><c:if test="${empty dealers}"><tr><td colspan="7" class="empty-state">Không có đại lý phù hợp trong phạm vi của bạn.</td></tr></c:if></tbody></table></div><%@ include file="../fragments/pagination.jspf" %>
</main></body></html>
