<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %><fmt:setLocale value="vi_VN"/>
<!doctype html><html lang="vi"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bảng giá</title><%@ include file="../fragments/assets.jspf" %></head><body class="app-page"><%@ include file="../fragments/sidebar.jspf" %>
<%@ include file="../fragments/topbar.jspf" %>
<main class="page-body app-content catalog-page"><div class="page-heading"><div><h1>Bảng giá</h1><p>Giá bán theo nhóm khách hàng và thời gian hiệu lực.</p></div><c:if test="${access.allows('PRICE_MANAGE')}"><a class="button button-primary" href="?new=1#price-editor" data-editor="price-editor">＋ Tạo bảng giá</a></c:if></div>
<c:if test="${param.notice == 'saved'}"><p class="alert alert-success" role="status">Đã lưu bảng giá.</p></c:if>
<c:if test="${not empty errors.form}"><p class="alert alert-error" role="alert"><c:out value="${errors.form}"/></p></c:if>
<c:if test="${not empty errors.id or not empty errors.revision}"><p class="alert alert-error" role="alert"><c:out value="${errors.id}"/><c:out value="${errors.revision}"/></p></c:if>
<c:if test="${access.allows('PRICE_MANAGE')}"><details id="price-editor" class="content-panel disclosure editor" ${param['new'] == '1' or form.action == 'create' and not empty errors ? 'open' : ''}><summary>Tạo / kế thừa phiên bản</summary>
<form method="post" class="account-form form-grid"><input type="hidden" name="_csrf" value="<c:out value="${csrfToken}"/>"><input type="hidden" name="action" value="create">
<label class="field">Tên <input name="name" type="text" value="<c:out value="${form.action == 'create' ? form.name : ''}"/>" required maxlength="150" aria-describedby="create-name-error" aria-invalid="${not empty errors.name}"><span id="create-name-error" class="field-error"><c:out value="${errors.name}"/></span></label>
<label class="field">Nhóm khách <select name="group"><c:forEach items="${groups}" var="g"><option value="${g.id}" ${(form.action == 'create' ? form.group : '') == g.id.toString() ? 'selected' : ''}><c:out value="${g.name}"/></option></c:forEach></select><span id="create-group-error" class="field-error"><c:out value="${errors.group}"/></span></label>
<label class="field">Từ ngày <input name="from" type="date" value="<c:out value="${form.action == 'create' ? form.from : today}"/>" required  aria-describedby="create-from-error" aria-invalid="${not empty errors.from}"><span id="create-from-error" class="field-error"><c:out value="${errors.from}"/></span></label>
<label class="field">Đến ngày <input name="to" type="date" value="<c:out value="${form.action == 'create' ? form.to : ''}"/>" required  aria-describedby="create-to-error" aria-invalid="${not empty errors.to}"><span id="create-to-error" class="field-error"><c:out value="${errors.to}"/></span></label>
<label class="field">Kế thừa <select name="parent"><option value="">Bảng giá trống</option><c:forEach items="${versions}" var="v"><option value="${v.id}" ${(form.action == 'create' ? form.parent : param.parent) == v.id.toString() ? 'selected' : ''}><c:out value="${v.group_name}"/> / <c:out value="${v.name}"/> (#${v.id})</option></c:forEach></select><span id="create-parent-error" class="field-error"><c:out value="${errors.parent}"/></span></label>
<button class="button button-primary">Tạo phiên bản</button><a class="button button-secondary" href="${pageContext.request.contextPath}/pricing/lists">Hủy</a></form></details></c:if>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Nhóm khách hàng</th><th>Phiên bản</th><th>Thời gian hiệu lực</th><th>Trạng thái</th><th>Sử dụng</th></tr></thead><tbody>
<c:forEach items="${versions}" var="v"><tr><td><c:out value="${v.group_name}"/></td><td><a href="?id=${v.id}#price-detail"><span class="badge badge-neutral">#${v.id}</span> <c:out value="${v.name}"/></a></td><td><c:out value="${v.display_from}"/> – <c:out value="${v.display_to}"/></td><td><span class="badge ${v.effective_state == 'ACTIVE' ? 'badge-success' : v.effective_state == 'UPCOMING' ? 'badge-warning' : 'badge-neutral'}"><c:out value="${v.effective_label}"/></span></td><td>${v.used == 1 ? 'Đã được sử dụng' : 'Chưa được sử dụng'}</td></tr></c:forEach>
<c:if test="${empty versions}"><tr><td colspan="5" class="empty-state">Chưa có bảng giá.</td></tr></c:if>
</tbody></table></div>
<c:if test="${not empty edit}"><div class="section-heading" id="price-detail"><div><h2><c:out value="${edit.group_name}"/> · <c:out value="${edit.name}"/> (#${edit.id})</h2><p class="muted">Có hiệu lực từ <c:out value="${edit.display_from}"/> đến <c:out value="${edit.display_to}"/> · Lần cập nhật ${edit.revision}</p></div><c:if test="${access.allows('PRICE_MANAGE')}"><a class="button button-primary" href="?id=${edit.id}&amp;new=1&amp;parent=${edit.id}#price-editor">＋ Tạo phiên bản mới</a></c:if></div>
<c:if test="${edit.used == 1}"><div class="alert alert-warning"><strong>Phiên bản này đã được sử dụng</strong>Tạo phiên bản mới để thay đổi giá. Phiên bản hiện tại được giữ nguyên cho các tham chiếu giao dịch đã ghi nhận.</div></c:if>
<c:if test="${access.allows('PRICE_MANAGE') and edit.used == 0}">
<details class="content-panel disclosure" ${form.action == 'edit' and not empty errors ? 'open' : ''}><summary>Sửa tên và thời gian hiệu lực</summary><form method="post" class="account-form form-grid"><input type="hidden" name="_csrf" value="<c:out value="${csrfToken}"/>"><input type="hidden" name="action" value="edit"><input type="hidden" name="id" value="${edit.id}"><input type="hidden" name="revision" value="<c:out value="${form.action == 'edit' ? form.revision : edit.revision}"/>">
<label class="field">Tên <input name="name" type="text" value="<c:out value="${form.action == 'edit' ? form.name : edit.name}"/>" required maxlength="150" aria-describedby="edit-name-error" aria-invalid="${not empty errors.name}"><span id="edit-name-error" class="field-error"><c:out value="${errors.name}"/></span></label>
<label class="field">Từ <input name="from" type="date" value="<c:out value="${form.action == 'edit' ? form.from : edit.valid_from}"/>" required  aria-describedby="edit-from-error" aria-invalid="${not empty errors.from}"><span id="edit-from-error" class="field-error"><c:out value="${errors.from}"/></span></label>
<label class="field">Đến <input name="to" type="date" value="<c:out value="${form.action == 'edit' ? form.to : edit.valid_to}"/>" required  aria-describedby="edit-to-error" aria-invalid="${not empty errors.to}"><span id="edit-to-error" class="field-error"><c:out value="${errors.to}"/></span></label>
<div class="form-actions form-full"><button class="button button-primary">Lưu hiệu lực</button></div></form></details>
<details class="content-panel disclosure" ${form.action == 'item' and not empty errors or not empty param.q ? 'open' : ''}><summary>Thêm / cập nhật giá sản phẩm</summary><form method="get" class="account-form filter-form"><input type="hidden" name="id" value="${edit.id}"><label>Tìm SKU <input name="q" value="<c:out value="${param.q}"/>"></label><button class="button">Tìm sản phẩm</button></form>
<form method="post" class="account-form form-grid"><input type="hidden" name="_csrf" value="<c:out value="${csrfToken}"/>"><input type="hidden" name="action" value="item"><input type="hidden" name="id" value="${edit.id}"><input type="hidden" name="revision" value="<c:out value="${form.action == 'item' ? form.revision : edit.revision}"/>">
<label class="field">SKU <select name="product"><c:forEach items="${products}" var="p"><option value="${p.id}" ${form.action == 'item' and form.product == p.id.toString() ? 'selected' : ''}><c:out value="${p.sku}"/> / <c:out value="${p.name}"/></option></c:forEach></select><span id="item-product-error" class="field-error"><c:out value="${errors.product}"/></span></label>
<label class="field">Giá bán <input name="selling" type="text" value="<c:out value="${form.action == 'item' ? form.selling : ''}"/>" required inputmode="decimal" maxlength="128" aria-describedby="item-selling-error" aria-invalid="${not empty errors.selling}"><span id="item-selling-error" class="field-error"><c:out value="${errors.selling}"/></span></label>
<label class="field">Giá sàn <input name="floor" type="text" value="<c:out value="${form.action == 'item' ? form.floor : ''}"/>" required inputmode="decimal" maxlength="128" aria-describedby="item-floor-error" aria-invalid="${not empty errors.floor}"><span id="item-floor-error" class="field-error"><c:out value="${errors.floor}"/></span></label>
<button class="button button-primary">Lưu giá sản phẩm</button></form></details></c:if>
<div class="table-wrap"><table><thead><tr><th>SKU</th><th>Sản phẩm</th><th>Đơn vị tính giá</th><th>Giá bán</th><th>Giá sàn</th><th>Thao tác</th></tr></thead><tbody>
<c:forEach items="${items}" var="i"><tr><td><c:out value="${i.sku}"/></td><td><c:out value="${i.name}"/></td><td><c:out value="${i.base_unit}"/></td><td class="money"><fmt:formatNumber value="${i.selling_price}" pattern="#,##0.####"/> đ</td><td class="money"><fmt:formatNumber value="${i.floor_price}" pattern="#,##0.####"/> đ</td><td><c:if test="${access.allows('PRICE_MANAGE') and edit.used == 0}"><form method="post" data-confirm="Bạn có chắc muốn xóa giá sản phẩm này?"><input type="hidden" name="_csrf" value="<c:out value="${csrfToken}"/>"><input type="hidden" name="action" value="deleteItem"><input type="hidden" name="id" value="${edit.id}"><input type="hidden" name="revision" value="${edit.revision}"><input type="hidden" name="item" value="${i.id}"><button class="button">Xóa giá SKU</button></form></c:if></td></tr></c:forEach><c:if test="${empty items}"><tr><td colspan="6" class="empty-state">Phiên bản chưa có giá sản phẩm.</td></tr></c:if></tbody></table></div><p class="muted">Giá được tính trên đơn vị cơ sở của mỗi sản phẩm.</p></c:if>
<details class="content-panel disclosure" ${param.action == 'quote' ? 'open' : ''}><summary>Tra giá theo ngày</summary><c:if test="${not empty quote}"><div class="alert" role="status"><c:out value="${quote}"/></div></c:if>
<form method="get" class="account-form form-grid"><input type="hidden" name="action" value="quote">
<label class="field">Nhóm khách <select name="group"><c:forEach items="${groups}" var="g"><option value="${g.id}" ${(param.action == 'quote' ? param.group : '') == g.id.toString() ? 'selected' : ''}><c:out value="${g.name}"/></option></c:forEach></select><span id="quote-group-error" class="field-error"><c:out value="${errors.group}"/></span></label>
<label class="field">SKU <select name="product"><c:forEach items="${products}" var="p"><option value="${p.id}" ${param.action == 'quote' and param.product == p.id.toString() ? 'selected' : ''}><c:out value="${p.sku}"/></option></c:forEach></select></label>
<label class="field">Ngày <input name="date" type="date" value="<c:out value="${param.action == 'quote' ? param.date : today}"/>" required  aria-describedby="quote-date-error" aria-invalid="${not empty errors.date}"><span id="quote-date-error" class="field-error"><c:out value="${errors.date}"/></span></label>
<button class="button button-primary">Tra giá</button></form></details></main></body></html>
