<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html><html lang="vi"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bảng giá</title><%@ include file="../fragments/assets.jspf" %></head><body class="app-page"><%@ include file="../fragments/sidebar.jspf" %>
<%@ include file="../fragments/topbar.jspf" %>
<main class="page-body app-content catalog-page"><h1>Bảng giá theo nhóm khách hàng</h1>
<c:if test="${param.notice == 'saved'}"><p class="alert alert-success" role="status">Đã lưu bảng giá.</p></c:if>
<c:if test="${not empty errors.form}"><p class="alert alert-error" role="alert"><c:out value="${errors.form}"/></p></c:if>
<c:if test="${not empty errors.id or not empty errors.revision}"><p class="alert alert-error" role="alert"><c:out value="${errors.id}"/><c:out value="${errors.revision}"/></p></c:if>
<c:if test="${access.allows('PRICE_MANAGE')}"><section class="content-panel"><h2>Tạo / kế thừa phiên bản</h2>
<form method="post" class="account-form"><input type="hidden" name="_csrf" value="<c:out value="${csrfToken}"/>"><input type="hidden" name="action" value="create">
<label class="field">Tên <input name="name" type="text" value="<c:out value="${form.action == 'create' ? form.name : ''}"/>" required maxlength="150" aria-describedby="create-name-error" aria-invalid="${not empty errors.name}"><span id="create-name-error" class="field-error"><c:out value="${errors.name}"/></span></label>
<label class="field">Nhóm khách <select name="group"><c:forEach items="${groups}" var="g"><option value="${g.id}" ${(form.action == 'create' ? form.group : '') == g.id.toString() ? 'selected' : ''}><c:out value="${g.name}"/></option></c:forEach></select><span id="create-group-error" class="field-error"><c:out value="${errors.group}"/></span></label>
<label class="field">Từ ngày <input name="from" type="date" value="<c:out value="${form.action == 'create' ? form.from : today}"/>" required  aria-describedby="create-from-error" aria-invalid="${not empty errors.from}"><span id="create-from-error" class="field-error"><c:out value="${errors.from}"/></span></label>
<label class="field">Đến ngày <input name="to" type="date" value="<c:out value="${form.action == 'create' ? form.to : ''}"/>" required  aria-describedby="create-to-error" aria-invalid="${not empty errors.to}"><span id="create-to-error" class="field-error"><c:out value="${errors.to}"/></span></label>
<label class="field">Kế thừa <select name="parent"><option value="">Bảng giá trống</option><c:forEach items="${versions}" var="v"><option value="${v.id}" ${form.action == 'create' and form.parent == v.id.toString() ? 'selected' : ''}><c:out value="${v.group_name}"/> / <c:out value="${v.name}"/> (#${v.id})</option></c:forEach></select><span id="create-parent-error" class="field-error"><c:out value="${errors.parent}"/></span></label>
<button class="button button-primary">Tạo phiên bản</button></form></section></c:if>
<div class="table-wrap"><table><thead><tr><th>Phiên bản</th><th>Nhóm</th><th>Hiệu lực</th><th>Trạng thái</th></tr></thead><tbody>
<c:forEach items="${versions}" var="v"><tr><td><a href="?id=${v.id}"><c:out value="${v.name}"/> (#${v.id})</a></td><td><c:out value="${v.group_name}"/></td><td><c:out value="${v.valid_from}"/> / <c:out value="${v.valid_to}"/></td><td>${v.used == 1 ? 'Đã dùng: chỉ kế thừa' : 'Có thể sửa'}</td></tr></c:forEach>
</tbody></table></div>
<c:if test="${not empty edit}"><h2><c:out value="${edit.name}"/></h2>
<c:if test="${access.allows('PRICE_MANAGE') and edit.used == 0}">
<form method="post" class="account-form"><input type="hidden" name="_csrf" value="<c:out value="${csrfToken}"/>"><input type="hidden" name="action" value="edit"><input type="hidden" name="id" value="${edit.id}"><input type="hidden" name="revision" value="<c:out value="${form.action == 'edit' ? form.revision : edit.revision}"/>">
<label class="field">Tên <input name="name" type="text" value="<c:out value="${form.action == 'edit' ? form.name : edit.name}"/>" required maxlength="150" aria-describedby="edit-name-error" aria-invalid="${not empty errors.name}"><span id="edit-name-error" class="field-error"><c:out value="${errors.name}"/></span></label>
<label class="field">Từ <input name="from" type="date" value="<c:out value="${form.action == 'edit' ? form.from : edit.valid_from}"/>" required  aria-describedby="edit-from-error" aria-invalid="${not empty errors.from}"><span id="edit-from-error" class="field-error"><c:out value="${errors.from}"/></span></label>
<label class="field">Đến <input name="to" type="date" value="<c:out value="${form.action == 'edit' ? form.to : edit.valid_to}"/>" required  aria-describedby="edit-to-error" aria-invalid="${not empty errors.to}"><span id="edit-to-error" class="field-error"><c:out value="${errors.to}"/></span></label>
<button class="button">Sửa hiệu lực</button></form>
<form method="get"><input type="hidden" name="id" value="${edit.id}"><label>Tìm SKU <input name="q" value="<c:out value="${param.q}"/>"></label><button class="button">Tìm sản phẩm</button></form>
<form method="post" class="account-form"><input type="hidden" name="_csrf" value="<c:out value="${csrfToken}"/>"><input type="hidden" name="action" value="item"><input type="hidden" name="id" value="${edit.id}"><input type="hidden" name="revision" value="<c:out value="${form.action == 'item' ? form.revision : edit.revision}"/>">
<label class="field">SKU <select name="product"><c:forEach items="${products}" var="p"><option value="${p.id}" ${form.action == 'item' and form.product == p.id.toString() ? 'selected' : ''}><c:out value="${p.sku}"/> / <c:out value="${p.name}"/></option></c:forEach></select><span id="item-product-error" class="field-error"><c:out value="${errors.product}"/></span></label>
<label class="field">Giá bán <input name="selling" type="text" value="<c:out value="${form.action == 'item' ? form.selling : ''}"/>" required inputmode="decimal" maxlength="128" aria-describedby="item-selling-error" aria-invalid="${not empty errors.selling}"><span id="item-selling-error" class="field-error"><c:out value="${errors.selling}"/></span></label>
<label class="field">Giá sàn <input name="floor" type="text" value="<c:out value="${form.action == 'item' ? form.floor : ''}"/>" required inputmode="decimal" maxlength="128" aria-describedby="item-floor-error" aria-invalid="${not empty errors.floor}"><span id="item-floor-error" class="field-error"><c:out value="${errors.floor}"/></span></label>
<button class="button button-primary">Thêm / cập nhật giá SKU</button></form></c:if>
<div class="table-wrap"><table><thead><tr><th>SKU</th><th>Tên</th><th>Giá bán</th><th>Giá sàn</th><th>Thao tác</th></tr></thead><tbody>
<c:forEach items="${items}" var="i"><tr><td><c:out value="${i.sku}"/></td><td><c:out value="${i.name}"/></td><td><c:out value="${i.selling_price}"/></td><td><c:out value="${i.floor_price}"/></td><td><c:if test="${access.allows('PRICE_MANAGE') and edit.used == 0}"><form method="post"><input type="hidden" name="_csrf" value="<c:out value="${csrfToken}"/>"><input type="hidden" name="action" value="deleteItem"><input type="hidden" name="id" value="${edit.id}"><input type="hidden" name="revision" value="${edit.revision}"><input type="hidden" name="item" value="${i.id}"><button class="button">Xóa giá SKU</button></form></c:if></td></tr></c:forEach></tbody></table></div></c:if>
<h2>Tra giá theo ngày</h2><c:if test="${not empty quote}"><div class="alert" role="status"><c:out value="${quote}"/></div></c:if>
<form method="get" class="account-form"><input type="hidden" name="action" value="quote">
<label class="field">Nhóm khách <select name="group"><c:forEach items="${groups}" var="g"><option value="${g.id}" ${(param.action == 'quote' ? param.group : '') == g.id.toString() ? 'selected' : ''}><c:out value="${g.name}"/></option></c:forEach></select><span id="quote-group-error" class="field-error"><c:out value="${errors.group}"/></span></label>
<label class="field">SKU <select name="product"><c:forEach items="${products}" var="p"><option value="${p.id}" ${param.action == 'quote' and param.product == p.id.toString() ? 'selected' : ''}><c:out value="${p.sku}"/></option></c:forEach></select></label>
<label class="field">Ngày <input name="date" type="date" value="<c:out value="${param.action == 'quote' ? param.date : today}"/>" required  aria-describedby="quote-date-error" aria-invalid="${not empty errors.date}"><span id="quote-date-error" class="field-error"><c:out value="${errors.date}"/></span></label>
<button class="button">Tra giá</button></form></main></body></html>


