package vn.codegym.salesinventory.service;
import jakarta.mail.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import vn.codegym.salesinventory.config.AppConfig;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
class SmtpMailServiceTest {
    AppConfig.MailSettings gmail(){return new AppConfig.MailSettings("smtp.gmail.com",587,"sender@test.local","sender@test.local","application-secret",true,true,true);}
    @Test void authenticatedMailRequiresTlsCertificateVerificationAndTimeouts(){var p=new SmtpMailService(gmail()).transportProperties();assertThat(p).containsEntry("mail.smtp.auth","true").containsEntry("mail.smtp.starttls.enable","true").containsEntry("mail.smtp.starttls.required","true").containsEntry("mail.smtp.ssl.checkserveridentity","true").containsEntry("mail.smtp.connectiontimeout","5000").containsEntry("mail.smtp.timeout","5000").containsEntry("mail.smtp.writetimeout","5000");assertThat(p.toString()).doesNotContain("application-secret");assertThat(gmail().toString()).doesNotContain("application-secret","sender@test.local");}
    @Test void authenticatedSendUsesExplicitCredentialsAndSingleDesignatedRecipient()throws Exception{try(var transport=mockStatic(Transport.class)){var messages=new ArrayList<Message>();transport.when(()->Transport.send(any(Message.class),eq("sender@test.local"),eq("application-secret"))).thenAnswer(call->{messages.add(call.getArgument(0));return null;});var mail=new SmtpMailService(gmail());mail.sendPasswordReset("recipient@test.local","Tên Việt","https://hethong.nvdo.id.vn/reset-password?token=single-use",30);mail.sendActivation("recipient@test.local","Tên Việt","user","temporary","https://hethong.nvdo.id.vn/account/activate?token=one");assertThat(messages).hasSize(2);for(var m:messages){assertThat(m.getAllRecipients()).hasSize(1);assertThat(m.getAllRecipients()[0].toString()).isEqualTo("recipient@test.local");assertThat(m.getContent().toString()).contains("https://hethong.nvdo.id.vn/");}transport.verify(()->Transport.send(any(Message.class)),never());}}
    @Test void legacyConstructorStillUsesUnauthenticatedIsolatedSmtp(){try(var transport=mockStatic(Transport.class)){var mail=new SmtpMailService("localhost",1025,"test@test.local");mail.sendPasswordReset("recipient@test.local","Tên","http://localhost/reset",30);transport.verify(()->Transport.send(any(Message.class)));assertThat(mail.transportProperties()).containsEntry("mail.smtp.auth","false").containsEntry("mail.smtp.starttls.required","false");}}
    @Test void authenticationOrDeliveryFailureIsSystemError(){try(var transport=mockStatic(Transport.class)){transport.when(()->Transport.send(any(Message.class),anyString(),anyString())).thenThrow(new AuthenticationFailedException("denied"));assertThatThrownBy(()->new SmtpMailService(gmail()).sendPasswordReset("recipient@test.local","Tên","https://test/reset",30)).isInstanceOf(IllegalStateException.class).hasCauseInstanceOf(AuthenticationFailedException.class);}}
    @Test void invalidConfigurationFailsClosed(){assertThatThrownBy(()->new AppConfig.MailSettings("smtp.gmail.com",587,"sender@test.local","","",true,true,true)).isInstanceOf(IllegalStateException.class);assertThatThrownBy(()->new AppConfig.MailSettings("smtp.gmail.com",587,"sender@test.local","user","secret",true,false,true)).isInstanceOf(IllegalStateException.class);}
}
