package vn.codegym.salesinventory.service;
import jakarta.mail.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.eclipse.angus.mail.smtp.SMTPSendFailedException;
import org.eclipse.angus.mail.smtp.SMTPAddressFailedException;
import jakarta.mail.internet.InternetAddress;
import vn.codegym.salesinventory.config.AppConfig;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
class SmtpMailServiceTest {
    AppConfig.MailSettings gmail(){return new AppConfig.MailSettings("smtp.gmail.com",587,"sender@test.local","sender@test.local","application-secret",true,true,true);}
    @Test void authenticatedMailRequiresTlsCertificateVerificationAndTimeouts(){var p=new SmtpMailService(gmail()).transportProperties();assertThat(p).containsEntry("mail.smtp.auth","true").containsEntry("mail.smtp.starttls.enable","true").containsEntry("mail.smtp.starttls.required","true").containsEntry("mail.smtp.ssl.checkserveridentity","true").containsEntry("mail.smtp.connectiontimeout","5000").containsEntry("mail.smtp.timeout","5000").containsEntry("mail.smtp.writetimeout","5000");assertThat(p.toString()).doesNotContain("application-secret");assertThat(gmail().toString()).doesNotContain("application-secret","sender@test.local");}
    @Test void authenticatedSendUsesExplicitCredentialsAndSingleDesignatedRecipient()throws Exception{var transport=mock(Transport.class);var mail=new SmtpMailService(gmail(),session->transport);mail.sendPasswordReset("recipient@test.local","Tên Việt","https://qa.local/reset?token=test",30);mail.sendActivation("recipient@test.local","Tên Việt","user","temporary","https://qa.local/activate?token=test");var messages=ArgumentCaptor.forClass(Message.class);verify(transport,times(2)).connect("smtp.gmail.com",587,"sender@test.local","application-secret");verify(transport,times(2)).sendMessage(messages.capture(),any(Address[].class));for(var m:messages.getAllValues()){assertThat(m.getAllRecipients()).hasSize(1);assertThat(m.getAllRecipients()[0].toString()).isEqualTo("recipient@test.local");assertThat(m.getContent().toString()).contains("https://qa.local/");}}
    @Test void legacyConstructorStillUsesUnauthenticatedIsolatedSmtp()throws Exception{var legacy=new SmtpMailService("localhost",1025,"test@test.local");assertThat(legacy.transportProperties()).containsEntry("mail.smtp.auth","false").containsEntry("mail.smtp.starttls.required","false");var transport=mock(Transport.class);new SmtpMailService(new AppConfig.MailSettings("localhost",1025,"test@test.local","","",false,false,false),session->transport).sendPasswordReset("recipient@test.local","Tên","http://qa.local/reset",30);verify(transport).connect("localhost",1025,null,null);}
    @Test void authenticationOrDeliveryFailureIsSystemError()throws Exception{var transport=mock(Transport.class);doThrow(new AuthenticationFailedException("denied")).when(transport).connect(anyString(),anyInt(),anyString(),anyString());assertThatThrownBy(()->new SmtpMailService(gmail(),s->transport).sendPasswordReset("recipient@test.local","Tên","https://qa.local/reset",30)).isInstanceOfSatisfying(MailDeliveryFailure.class,e->assertThat(e.definitive()).isTrue()).hasCauseInstanceOf(AuthenticationFailedException.class);}
    @Test void explicitSmtpRejectionIsDefinitiveButDataTimeoutNeedsReview()throws Exception{var transport=mock(Transport.class);doThrow(new SMTPSendFailedException("DATA",550,"rejected",null,null,null,null)).when(transport).sendMessage(any(Message.class),any(Address[].class));assertThatThrownBy(()->new SmtpMailService(gmail(),s->transport).sendPasswordReset("recipient@test.local","Tên","https://qa.local/reset",30)).isInstanceOfSatisfying(MailDeliveryFailure.class,e->assertThat(e.definitive()).isTrue());reset(transport);doThrow(new MessagingException("timeout",new java.net.SocketTimeoutException())).when(transport).sendMessage(any(Message.class),any(Address[].class));assertThatThrownBy(()->new SmtpMailService(gmail(),s->transport).sendPasswordReset("recipient@test.local","Tên","https://qa.local/reset",30)).isInstanceOfSatisfying(MailDeliveryFailure.class,e->assertThat(e.definitive()).isFalse());}
    @Test void quitTimeoutDoesNotResendAnAcceptedEmail()throws Exception{var transport=mock(Transport.class);doThrow(new MessagingException("quit timeout")).when(transport).close();new SmtpMailService(gmail(),s->transport).sendPasswordReset("recipient@test.local","Tên","https://qa.local/reset",30);verify(transport,times(1)).sendMessage(any(Message.class),any(Address[].class));}
    @Test void recipientRejectionIsDefinitiveButPartialAcceptanceMustNotRetry()throws Exception{var transport=mock(Transport.class);var recipient=new InternetAddress("recipient@test.local");var rejected=new SMTPAddressFailedException(recipient,"RCPT TO",550,"denied");doThrow(new SendFailedException("invalid",rejected,null,null,new Address[]{recipient})).when(transport).sendMessage(any(Message.class),any(Address[].class));assertThatThrownBy(()->new SmtpMailService(gmail(),s->transport).sendPasswordReset("recipient@test.local","Tên","https://qa.local/reset",30)).isInstanceOfSatisfying(MailDeliveryFailure.class,e->assertThat(e.definitive()).isTrue());reset(transport);doThrow(new SendFailedException("partial",rejected,new Address[]{recipient},null,null)).when(transport).sendMessage(any(Message.class),any(Address[].class));assertThatThrownBy(()->new SmtpMailService(gmail(),s->transport).sendPasswordReset("recipient@test.local","Tên","https://qa.local/reset",30)).isInstanceOfSatisfying(MailDeliveryFailure.class,e->assertThat(e.definitive()).isFalse());}
    @Test void invalidConfigurationFailsClosed(){assertThatThrownBy(()->new AppConfig.MailSettings("smtp.gmail.com",587,"sender@test.local","","",true,true,true)).isInstanceOf(IllegalStateException.class);assertThatThrownBy(()->new AppConfig.MailSettings("smtp.gmail.com",587,"sender@test.local","user","secret",true,false,true)).isInstanceOf(IllegalStateException.class);}
}
