package vn.codegym.salesinventory.service;
import org.junit.jupiter.api.Test;import java.util.*;import java.time.*;import static org.assertj.core.api.Assertions.*;
class XlsxTest {
 @Test void roundTripPreservesPhoneUnicodeAndFiveThousandRows(){List<List<String>> rows=new ArrayList<>();rows.add(List.of("SKU","Tên","Điện thoại"));for(int i=0;i<5000;i++)rows.add(List.of("SP"+i,"Hàng <&> Việt","0901234567"));var result=Xlsx.read(Xlsx.write(rows));assertThat(result).hasSize(5001);assertThat(result.get(5000).cells()).containsExactly("SP4999","Hàng <&> Việt","0901234567");}
 @Test void refusesNonWorkbookAndOversize(){assertThatThrownBy(()->Xlsx.read("text".getBytes())).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->Xlsx.read(new byte[Xlsx.MAX_BYTES+1])).isInstanceOf(IllegalArgumentException.class);}
 @Test void previewBoundToOwnerExpiryAndOneConfirmation(){var now=Instant.now();var p=new ImportPreview(1,List.of(),now);assertThatThrownBy(()->p.claim(2,p.getToken(),now)).isInstanceOf(IllegalArgumentException.class);p.claim(1,p.getToken(),now);assertThatThrownBy(()->p.claim(1,p.getToken(),now)).isInstanceOf(IllegalArgumentException.class);var expired=new ImportPreview(1,List.of(),now);assertThatThrownBy(()->expired.claim(1,expired.getToken(),now.plusSeconds(1800))).isInstanceOf(IllegalArgumentException.class);}

 private byte[] replaceSheet(String xml)throws Exception{byte[] source=Xlsx.write(List.of(List.of("SKU"),List.of("SP1")));var out=new java.io.ByteArrayOutputStream();try(var input=new java.util.zip.ZipInputStream(new java.io.ByteArrayInputStream(source));var zip=new java.util.zip.ZipOutputStream(out)){java.util.zip.ZipEntry entry;while((entry=input.getNextEntry())!=null){zip.putNextEntry(new java.util.zip.ZipEntry(entry.getName()));zip.write(entry.getName().equals("xl/worksheets/sheet1.xml")?xml.getBytes(java.nio.charset.StandardCharsets.UTF_8):input.readAllBytes());zip.closeEntry();}}return out.toByteArray();}
 @Test void rejectsExternalEntitiesAndMarksFormulasAsLineErrors()throws Exception{var malicious=replaceSheet("<!DOCTYPE worksheet [<!ENTITY external SYSTEM 'file:///sensitive'>]><worksheet><sheetData><row><c><v>&external;</v></c></row></sheetData></worksheet>");assertThatThrownBy(()->Xlsx.read(malicious)).isInstanceOf(IllegalArgumentException.class);var formula=replaceSheet("<worksheet><sheetData><row r='1'><c><f>1+1</f><v>2</v></c></row></sheetData></worksheet>");assertThat(Xlsx.read(formula).get(0).error()).contains("công thức");}
 @Test void refusesMoreThanTenThousandDataRows(){var rows=new ArrayList<List<String>>();for(int i=0;i<10002;i++)rows.add(List.of("SP"+i));assertThatThrownBy(()->Xlsx.read(Xlsx.write(rows))).isInstanceOf(IllegalArgumentException.class);}
}
