<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:choose><c:when test="${importStep == 1}"><jsp:include page="import.jsp"/></c:when><c:otherwise>
<!doctype html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><c:out value="${title}"/> | Quản lý bán hàng</title><%@ include file="../fragments/assets.jspf" %>
<link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/import-jobs.css?v=s3-1">
<script src="${pageContext.request.contextPath}/assets/js/import-jobs.js?v=s3-1" defer></script></head>
<body class="app-page"><%@ include file="../fragments/sidebar.jspf" %><%@ include file="../fragments/topbar.jspf" %>
<main class="page-body app-content import-page" data-import-job data-job-id="<c:out value='${job.id}'/>" data-job-status="<c:out value='${job.status}'/>">
<c:set var="listPath" value="${userImportPage ? '/admin/users' : '/catalog/products'}"/>
<c:set var="activeJob" value="${job.status == 'QUEUED' or job.status == 'RUNNING'}"/>
<c:set var="processed" value="${job.success_count + job.failed_count + job.review_count}"/>
<div class="page-heading"><div><h1>${importStep == 2 ? 'Kiểm tra dữ liệu trước khi nhập' : 'Tiến độ và kết quả nhập Excel'}</h1><p><c:out value="${job.filename}"/> · <c:out value="${job.total_rows}"/> dòng dữ liệu</p></div><a class="button button-secondary" href="?new=1">Chọn tệp khác</a></div>
<ol class="import-steps" aria-label="Tiến trình nhập Excel"><li class="complete"><span class="step-number">1</span><div><strong>Chọn tệp</strong><small>Đã xong</small></div></li><li class="${importStep == 2 ? 'current' : 'complete'}"><span class="step-number">2</span><div><strong>Kiểm tra dữ liệu</strong><small>${importStep == 2 ? 'Đang thực hiện' : 'Đã xác nhận'}</small></div></li><li class="${importStep == 3 ? 'current' : ''}"><span class="step-number">3</span><div><strong>Xử lý và báo cáo</strong><small data-job-step>${activeJob ? 'Đang xử lý' : importStep == 3 ? 'Đã kết thúc' : 'Chưa thực hiện'}</small></div></li></ol>
<c:if test="${not empty errors.preview}"><div class="alert alert-error" role="alert"><c:out value="${errors.preview}"/></div></c:if>
<section class="content-panel import-job-summary" aria-label="Trạng thái tác vụ">
<h2 data-job-title><c:choose><c:when test="${job.status == 'PREVIEW'}">Xem trước dữ liệu</c:when><c:when test="${activeJob}">Đang xử lý tác vụ</c:when><c:when test="${job.status == 'STOPPED'}">Tác vụ đã dừng</c:when><c:when test="${job.status == 'EXPIRED'}">Xem trước đã hết hạn</c:when><c:otherwise>Tác vụ đã xử lý xong</c:otherwise></c:choose></h2>
<p class="muted">Xác nhận xử lý toàn bộ <strong><c:out value="${job.valid_rows}"/></strong> dòng hợp lệ, không chỉ trang đang xem. Đóng tab hoặc tải lại trang không hủy tác vụ.</p>
<div class="import-job-counts"><span>Đã nhập <strong data-job-count="success_count"><c:out value="${job.success_count}"/></strong></span><span>Thất bại <strong data-job-count="failed_count"><c:out value="${job.failed_count}"/></strong></span><span>Không hợp lệ <strong data-job-count="invalid_count"><c:out value="${job.invalid_count}"/></strong></span><span>Cần kiểm tra <strong data-job-count="review_count"><c:out value="${job.review_count}"/></strong></span><span>Chờ xử lý <strong data-job-count="pending_count"><c:out value="${job.pending_count}"/></strong></span><span>Chưa xử lý do dừng <strong data-job-count="skipped_count"><c:out value="${job.skipped_count}"/></strong></span></div>
<div class="job-progress"><label for="job-progress">Đã xử lý <strong data-job-processed><c:out value="${processed}"/></strong> / <c:out value="${job.valid_rows}"/> dòng hợp lệ</label><progress id="job-progress" max="${job.valid_rows > 0 ? job.valid_rows : 1}" value="${processed}"></progress></div>
<p class="alert alert-warning" data-job-review ${job.review_count == 0 ? 'hidden' : ''}>Có dòng chưa rõ kết quả gửi email. Không tự nhập/gửi lại các dòng này; cần kiểm tra Mailpit/SMTP và dữ liệu tài khoản trước.</p>
<p class="alert alert-warning" data-job-reason ${empty job.reason ? 'hidden' : ''}><c:out value="${job.reason}"/></p>
<p class="field-error" role="status" data-job-poll-error hidden></p>
<div class="page-actions"><c:url var="reportUrl" value="${importPath}"><c:param name="job" value="${job.id}"/><c:param name="report" value="1"/></c:url><a class="button button-secondary" href="<c:out value='${reportUrl}'/>" download>Tải báo cáo toàn tác vụ</a><a class="button button-secondary" href="${pageContext.request.contextPath}${listPath}">Xem danh sách ${userImportPage ? 'người dùng' : 'sản phẩm'}</a><a class="button button-plain" href="">Tải lại kết quả</a></div>
<p class="muted">Xem trước hết hạn theo thời hạn hệ thống. Báo cáo lưu theo cấu hình; tác vụ đang chạy không bị dọn. Quyền và dữ liệu được kiểm tra lại trước từng dòng.</p><noscript><p class="alert alert-warning">JavaScript đang tắt. Dùng “Tải lại kết quả” để xem tiến độ mới nhất; tác vụ vẫn chạy ở máy chủ.</p></noscript>
</section>
<form method="get" class="filter-bar import-job-filters"><input type="hidden" name="job" value="<c:out value='${job.id}'/>"><input type="hidden" name="pageSize" value="${pagination.pageSize}"><label>Tìm trong toàn tác vụ<input name="q" maxlength="150" value="<c:out value='${param.q}'/>" placeholder="Mã, tên, số dòng hoặc thông báo"></label><label>Trạng thái<select name="state"><option value="">Tất cả dòng</option><c:forEach var="state" items="${['INVALID','READY','CLAIMED','EMAIL_ATTEMPT','SUCCESS','FAILED','REVIEW','SKIPPED']}"><option value="${state}" ${param.state == state ? 'selected' : ''}><c:choose><c:when test="${state == 'INVALID'}">Không hợp lệ</c:when><c:when test="${state == 'READY'}">Chờ xử lý</c:when><c:when test="${state == 'CLAIMED'}">Đang xử lý</c:when><c:when test="${state == 'EMAIL_ATTEMPT'}">Đang gửi email</c:when><c:when test="${state == 'SUCCESS'}">Đã nhập</c:when><c:when test="${state == 'FAILED'}">Thất bại</c:when><c:when test="${state == 'REVIEW'}">Cần kiểm tra email</c:when><c:otherwise>Chưa xử lý do dừng</c:otherwise></c:choose></option></c:forEach></select></label><button class="button button-primary">Lọc dữ liệu</button><c:url var="clearUrl" value="${importPath}"><c:param name="job" value="${job.id}"/></c:url><a class="button button-plain" href="<c:out value='${clearUrl}'/>">Xóa bộ lọc</a></form>
<div hidden><c:forEach var="header" items="${headers}"><span data-job-column><c:out value="${header}"/></span></c:forEach></div>
<div class="table-wrap import-table" role="region" aria-label="Dữ liệu toàn tác vụ đã phân trang"><table class="data-table"><thead><tr><th>Dòng</th><th>${userImportPage ? 'Tên đăng nhập' : 'SKU'}</th><th>${userImportPage ? 'Họ tên' : 'Tên sản phẩm'}</th><th>Thao tác</th><th>Kết quả và thông tin</th></tr></thead><tbody data-job-rows><c:forEach var="line" items="${rows}"><tr><td><c:out value="${line.number}"/></td><td><c:out value="${line.cells[0]}"/></td><td><c:out value="${line.cells[userImportPage ? 2 : 1]}"/></td><td><c:out value="${line.operation}"/></td><td><span class="badge ${line.state == 'SUCCESS' ? 'badge-success' : line.state == 'INVALID' or line.state == 'FAILED' or line.state == 'REVIEW' ? 'badge-danger' : ''}"><c:out value="${line.label}"/></span><p class="field-error"><c:out value="${line.error}"/></p><details class="row-details"><summary>Thông tin dòng</summary><dl><c:forEach var="header" items="${headers}" varStatus="column"><div><dt><c:out value="${header}"/></dt><dd><c:out value="${line.cells[column.index]}"/></dd></div></c:forEach></dl></details></td></tr></c:forEach><c:if test="${empty rows}"><tr><td colspan="5" class="empty-state">Không có dòng khớp bộ lọc.</td></tr></c:if></tbody></table></div>
<%@ include file="../fragments/pagination.jspf" %>
<c:if test="${job.status == 'PREVIEW'}"><form method="post" class="import-footer import-confirm"><input type="hidden" name="_csrf" value="<c:out value='${csrfToken}'/>"><input type="hidden" name="action" value="confirm"><input type="hidden" name="job" value="<c:out value='${job.id}'/>"><input type="hidden" name="version" value="${job.version}"><input type="hidden" name="token" value="<c:out value='${job.confirm_key}'/>"><c:forEach var="filter" items="${['q','state','page','pageSize']}"><input type="hidden" name="${filter}" value="<c:out value='${param[filter]}'/>"></c:forEach><p class="muted"><c:out value="${job.invalid_count}"/> dòng lỗi sẽ không được nhập. Giá trị được kiểm tra lại khi xử lý.</p><button class="button button-primary" ${not job.available or job.valid_rows == 0 ? 'disabled' : ''}>Nhập tất cả <c:out value="${job.valid_rows}"/> dòng hợp lệ</button></form></c:if>
</main></body></html>
</c:otherwise></c:choose>
