package vn.codegym.salesinventory.dao;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import vn.codegym.salesinventory.dto.PageRequest;
import vn.codegym.salesinventory.service.*;
import static org.assertj.core.api.Assertions.*;
class DealerHandoverAcceptanceIT extends StoryDatabaseSupport {
    long manager,from,to,territory,group;DealerHandoverService handover;DealerService dealers;
    @BeforeEach void fixture(){manager=user("SALES_MANAGER");from=user("SALES");to=user("SALES");group=Sql.id(one("SELECT id FROM customer_groups LIMIT 1").get("id"));territory=insert("INSERT INTO territories(code,name) VALUES(?,'Khu vực QA')","T-"+UUID.randomUUID());handover=new DealerHandoverService(source);dealers=new DealerService(source);}
    long dealer(){return dealers.save(manager,0,new DealerService.Input("D-"+UUID.randomUUID(),"Khách QA","","0912345678",group,territory,from,null,"ACTIVE",0));}
    String preview(){return handover.preview(manager,from,to,territory,"Nhân viên nghỉ / bàn giao tuyến");}
    @Test void singleDealerHandoverLeavesOtherDealersAssigned(){long one=dealer(),other=dealer();String key=handover.preview(manager,from,to,null,"Đổi người chăm sóc",one);assertThat(handover.confirm(manager,key)).isEqualTo(1);assertThat(Sql.id(dealers.find(manager,one).get("primary_staff_id"))).isEqualTo(to);assertThat(Sql.id(dealers.find(manager,other).get("primary_staff_id"))).isEqualTo(from);}
    @Test void previewPagesButConfirmProcessesWholeScopeAndIsIdempotent(){for(int i=0;i<21;i++)dealer();String key=preview();assertThat(handover.rows(manager,key,new PageRequest(1,20)).items()).hasSize(20);assertThat(handover.rows(manager,key,new PageRequest(999,20)).items()).hasSize(1);assertThat(handover.confirm(manager,key)).isEqualTo(21);assertThat(handover.confirm(manager,key)).isEqualTo(21);assertThat(dealers.search(from,"",new PageRequest(1,100)).totalItems()).isZero();assertThat(dealers.search(to,"",new PageRequest(1,100)).totalItems()).isEqualTo(21);assertThat(count("SELECT COUNT(*) n FROM audit_logs WHERE event_type='DEALER_HANDED_OVER' AND actor_user_id=?",manager)).isEqualTo(21);assertThat(handover.batch(user("SALES_MANAGER"),key)).containsEntry("status","CONFIRMED");}
    @Test void cannotConfirmAnotherManagersPreviewAndCannotUseReadOnlyRole(){dealer();String key=preview();assertThatThrownBy(()->handover.confirm(user("SALES_MANAGER"),key)).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->handover.preview(from,from,to,null,"Lý do")).isInstanceOf(SecurityException.class);assertThatThrownBy(()->handover.confirm(user("ACCOUNTANT"),key)).isInstanceOf(SecurityException.class);}
    @Test void previewBecomesStaleWhenProfileOrSelectionChanges(){long id=dealer();String key=preview();var row=dealers.find(manager,id);dealers.save(manager,id,new DealerService.Input(Sql.text(row.get("code")),"Tên đã sửa","","0912345678",group,territory,from,null,"ACTIVE",1));assertThatThrownBy(()->handover.confirm(manager,key)).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("đã thay đổi");String newer=preview();dealer();assertThatThrownBy(()->handover.confirm(manager,newer)).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("Phạm vi");assertThat(dealers.search(to,"",new PageRequest(1,20)).totalItems()).isZero();}
    @Test void revokedPermissionLockedTargetAndExpiredPreviewFailClosed(){dealer();String key=preview();update("UPDATE users SET status='ADMIN_LOCKED' WHERE id=?",to);assertThatThrownBy(()->handover.confirm(manager,key)).isInstanceOf(IllegalArgumentException.class);update("UPDATE users SET status='ACTIVE' WHERE id=?",to);update("UPDATE dealer_handover_batches SET expires_at=DATE_SUB(CURRENT_TIMESTAMP,INTERVAL 1 HOUR) WHERE batch_key=?",key);assertThatThrownBy(()->handover.confirm(manager,key)).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("hết hạn");String next=preview();update("DELETE FROM user_roles WHERE user_id=?",manager);assertThatThrownBy(()->handover.confirm(manager,next)).isInstanceOf(SecurityException.class);}
    @Test void auditFailureRollsBackEveryDealerAndBatch(){long first=dealer(),second=dealer();String key=preview();failAudit();assertThatThrownBy(()->handover.confirm(manager,key)).isInstanceOf(IllegalStateException.class);assertThat(Sql.id(dealers.find(manager,first).get("primary_staff_id"))).isEqualTo(from);assertThat(Sql.id(dealers.find(manager,second).get("primary_staff_id"))).isEqualTo(from);assertThat(handover.batch(manager,key)).containsEntry("status","PREVIEW");assertThat(count("SELECT COUNT(*) n FROM dealer_staff_references WHERE user_id=?",to)).isZero();}
    @Test void lockingEmployeeCreatesWarningsWhichHandoverResolves(){long id=dealer();new AccountStatusService(source).change(1,from,true,"Nghỉ việc");assertThat(count("SELECT COUNT(*) n FROM handover_warnings WHERE user_id=? AND resolved_at IS NULL",from)).isEqualTo(1);String key=preview();handover.confirm(manager,key);assertThat(count("SELECT COUNT(*) n FROM handover_warnings WHERE user_id=? AND resolved_at IS NULL",from)).isZero();assertThat(dealers.find(to,id)).containsKey("code");assertThatThrownBy(()->dealers.find(from,id)).isInstanceOf(SecurityException.class);}
    @Test void simultaneousConfirmHasOneSetOfAudits()throws Exception{dealer();String key=preview();var pool=Executors.newFixedThreadPool(2);var gate=new CountDownLatch(1);try{List<Future<Integer>> tasks=new ArrayList<>();for(int i=0;i<2;i++)tasks.add(pool.submit(()->{gate.await();return handover.confirm(manager,key);}));gate.countDown();for(var task:tasks)assertThat(task.get(30,TimeUnit.SECONDS)).isEqualTo(1);assertThat(count("SELECT COUNT(*) n FROM audit_logs WHERE event_type='DEALER_HANDED_OVER' AND actor_user_id=?",manager)).isEqualTo(1);}finally{pool.shutdownNow();}}
}
