package vn.codegym.salesinventory.dao;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import vn.codegym.salesinventory.dto.PageRequest;
import vn.codegym.salesinventory.service.*;
import vn.codegym.salesinventory.validation.FieldValidationException;
import static org.assertj.core.api.Assertions.*;
class DealerStatusAcceptanceIT extends StoryDatabaseSupport {
    long manager,sales,dealer;DealerStatusService service;DealerService profiles;
    @BeforeEach void fixture(){manager=user("SALES_MANAGER");sales=user("SALES");long group=Sql.id(one("SELECT id FROM customer_groups LIMIT 1").get("id")),territory=insert("INSERT INTO territories(code,name) VALUES(?,'Khu vực QA')","T-"+UUID.randomUUID());profiles=new DealerService(source);dealer=profiles.save(manager,0,new DealerService.Input("D-"+UUID.randomUUID(),"Khách QA","","0912345678",group,territory,sales,null,"ACTIVE",0));service=new DealerStatusService(source);}
    @Test void lockHasReasonHistoryAndBlocksNewOrderGuardWithoutBlockingExistingRead(){DealerStatusService.requireNewOrderAllowed(profiles.find(sales,dealer));service.change(user("ACCOUNTANT"),dealer,1,true,"Rà soát khả năng thanh toán");var d=profiles.find(sales,dealer);assertThat(DealerStatusService.locked(d)).isTrue();assertThat(d).containsEntry("transaction_lock_reason","Rà soát khả năng thanh toán");assertThatThrownBy(()->DealerStatusService.requireNewOrderAllowed(d)).isInstanceOf(FieldValidationException.class).hasMessageContaining("đơn mới");assertThat(service.history(sales,dealer,new PageRequest(1,20)).totalItems()).isEqualTo(1);service.change(manager,dealer,2,false,"Hoàn tất rà soát");assertThat(DealerStatusService.locked(profiles.find(sales,dealer))).isFalse();DealerStatusService.requireNewOrderAllowed(profiles.find(sales,dealer));assertThat(service.history(manager,dealer,new PageRequest(1,20)).totalItems()).isEqualTo(2);}
    @Test void lockedFilterCountAndDataAgree(){service.change(manager,dealer,1,true,"Khóa thử");String code=Sql.text(profiles.find(manager,dealer).get("code"));assertThat(profiles.search(manager,new DealerService.Filter(code,null,null,null,"LOCKED"),new PageRequest(1,20)).totalItems()).isEqualTo(1);assertThat(profiles.search(manager,new DealerService.Filter(code,null,null,null,"ACTIVE"),new PageRequest(1,20)).totalItems()).isZero();assertThatThrownBy(()->service.history(user("SALES"),dealer,new PageRequest(1,20))).isInstanceOf(SecurityException.class);}
    @Test void rolesReasonsStaleVersionsAndAuditFailureAreEnforced(){assertThatThrownBy(()->service.change(sales,dealer,1,true,"Lý do")).isInstanceOf(SecurityException.class);assertThatThrownBy(()->service.change(user("ADMIN"),dealer,1,true,"Lý do")).isInstanceOf(SecurityException.class);assertThatThrownBy(()->service.change(manager,dealer,1,true,"")).isInstanceOf(FieldValidationException.class);assertThatThrownBy(()->service.change(manager,dealer,0,true,"Lý do")).isInstanceOf(FieldValidationException.class);failAudit();assertThatThrownBy(()->service.change(manager,dealer,1,true,"Rollback")).isInstanceOf(IllegalStateException.class);assertThat(DealerStatusService.locked(profiles.find(manager,dealer))).isFalse();assertThat(service.history(manager,dealer,new PageRequest(1,20)).totalItems()).isZero();}
    @Test void simultaneousLockHasOneWinnerAndOneHistory()throws Exception{var pool=Executors.newFixedThreadPool(2);var gate=new CountDownLatch(1);try{List<Future<Boolean>> tasks=new ArrayList<>();for(int i=0;i<2;i++)tasks.add(pool.submit(()->{gate.await();try{service.change(manager,dealer,1,true,"Đồng thời");return true;}catch(FieldValidationException e){return false;}}));gate.countDown();int wins=0;for(var t:tasks)if(t.get(30,TimeUnit.SECONDS))wins++;assertThat(wins).isEqualTo(1);assertThat(service.history(manager,dealer,new PageRequest(1,20)).totalItems()).isEqualTo(1);}finally{pool.shutdownNow();}}
}
