package vn.codegym.salesinventory.dao;
import java.math.BigDecimal;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import vn.codegym.salesinventory.dto.PageRequest;
import vn.codegym.salesinventory.service.*;
import vn.codegym.salesinventory.validation.FieldValidationException;
import static org.assertj.core.api.Assertions.*;
class DealerCreditAcceptanceIT extends StoryDatabaseSupport {
    long manager,sales,dealer;DealerCreditService service;
    @BeforeEach void fixture(){manager=user("SALES_MANAGER");sales=user("SALES");long group=Sql.id(one("SELECT id FROM customer_groups LIMIT 1").get("id")),territory=insert("INSERT INTO territories(code,name) VALUES(?,'Khu vực QA')","T-"+UUID.randomUUID());dealer=new DealerService(source).save(manager,0,new DealerService.Input("DL-"+UUID.randomUUID(),"Khách QA","","0912345678",group,territory,sales,null,"ACTIVE",0));service=new DealerCreditService(source);}
    @Test void defaultsAreZeroAndAccountingWritesHistoryWithExactDecimals(){var d=new DealerService(source).find(sales,dealer);assertThat((BigDecimal)d.get("credit_limit")).isZero();assertThat(Sql.id(d.get("debt_days"))).isZero();long accountant=user("ACCOUNTANT");service.save(accountant,dealer,1,"123456.7891","30","Đánh giá tín dụng ban đầu");var h=service.history(sales,dealer,new PageRequest(1,20));assertThat(h.totalItems()).isEqualTo(1);assertThat((BigDecimal)h.items().get(0).get("new_limit")).isEqualByComparingTo("123456.7891");assertThat(h.items().get(0)).containsEntry("reason","Đánh giá tín dụng ban đầu");service.save(manager,dealer,2,"0","0","Thu hồi bán chịu");assertThat((BigDecimal)new DealerService(source).find(manager,dealer).get("credit_limit")).isZero();assertThat(service.history(manager,dealer,new PageRequest(1,20)).totalItems()).isEqualTo(2);}
    @Test void unauthorizedRolesAndForeignHistoryDenied(){for(String role:List.of("ADMIN","SALES","DIRECTOR","WAREHOUSE","WAREHOUSE_MANAGER")){long actor=user(role);assertThatThrownBy(()->service.save(actor,dealer,1,"100","1","Lý do")).isInstanceOf(SecurityException.class);}assertThatThrownBy(()->service.history(user("SALES"),dealer,new PageRequest(1,20))).isInstanceOf(SecurityException.class);}
    @Test void negativeOverflowFractionalDaysAndMissingReasonRejected(){assertThatThrownBy(()->service.save(manager,dealer,1,"-1","30","Lý do")).isInstanceOfSatisfying(FieldValidationException.class,e->assertThat(e.errors()).containsKey("limit"));assertThatThrownBy(()->service.save(manager,dealer,1,"1.00001","1.5","")).isInstanceOfSatisfying(FieldValidationException.class,e->assertThat(e.errors()).containsKeys("limit","days","reason"));assertThatThrownBy(()->service.save(manager,dealer,1,"1e1000","2147483648","Lý do")).isInstanceOf(FieldValidationException.class);assertThat(service.history(manager,dealer,new PageRequest(1,20)).totalItems()).isZero();}
    @Test void auditFailureAndStaleVersionPreserveConfiguration(){service.save(manager,dealer,1,"100","10","Ban đầu");assertThatThrownBy(()->service.save(manager,dealer,1,"200","20","Cũ")).isInstanceOf(FieldValidationException.class);failAudit();assertThatThrownBy(()->service.save(manager,dealer,2,"300","30","Không commit")).isInstanceOf(IllegalStateException.class);assertThat((BigDecimal)new DealerService(source).find(manager,dealer).get("credit_limit")).isEqualByComparingTo("100");assertThat(service.history(manager,dealer,new PageRequest(1,20)).totalItems()).isEqualTo(1);}
    @Test void concurrentCreditEditorsHaveOneWinner()throws Exception{var pool=Executors.newFixedThreadPool(2);var gate=new CountDownLatch(1);try{List<Future<Boolean>> tasks=new ArrayList<>();for(int i=0;i<2;i++)tasks.add(pool.submit(()->{gate.await();try{service.save(manager,dealer,1,"100","30","Đồng thời");return true;}catch(FieldValidationException e){return false;}}));gate.countDown();int wins=0;for(var task:tasks)if(task.get(30,TimeUnit.SECONDS))wins++;assertThat(wins).isEqualTo(1);assertThat(service.history(manager,dealer,new PageRequest(1,20)).totalItems()).isEqualTo(1);}finally{pool.shutdownNow();}}
}
