package vn.codegym.salesinventory.dao;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import vn.codegym.salesinventory.dto.PageRequest;
import vn.codegym.salesinventory.service.*;
import static org.assertj.core.api.Assertions.*;
class DealerAddressAcceptanceIT extends StoryDatabaseSupport {
    long manager,sales,dealer;DealerAddressService service;
    @BeforeEach void fixture(){manager=user("SALES_MANAGER");sales=user("SALES");long territory=insert("INSERT INTO territories(code,name) VALUES(?,'Khu vực QA')","T-"+UUID.randomUUID());long group=Sql.id(one("SELECT id FROM customer_groups LIMIT 1").get("id"));dealer=new DealerService(source).save(manager,0,new DealerService.Input("D-"+UUID.randomUUID(),"Đại lý","","0912345678",group,territory,sales,null,"ACTIVE",0));service=new DealerAddressService(source);}
    long parentVersion(){return Sql.id(one("SELECT version FROM dealers WHERE id=?",dealer).get("version"));}
    DealerAddressService.Input input(boolean defaultPoint,String status,long version,long parentVersion){return new DealerAddressService.Input("12 Đường QA","Người nhận QA","0912345678","Cổng phụ",defaultPoint,status,version,parentVersion);}
    long address(){return service.save(sales,dealer,0,input(false,"ACTIVE",0,parentVersion()));}
    @Test void firstPointBecomesDefaultAndSwitchIsAtomicAudited(){long first=address(),second=address();assertThat(DealerAddressService.isDefault(service.find(sales,dealer,first).get("is_default"))).isTrue();service.save(sales,dealer,second,input(true,"ACTIVE",1,parentVersion()));assertThat(DealerAddressService.isDefault(service.find(sales,dealer,first).get("is_default"))).isFalse();assertThat(count("SELECT COUNT(*) n FROM dealer_addresses WHERE dealer_id=? AND is_default=1",dealer)).isEqualTo(1);assertThat(count("SELECT COUNT(*) n FROM audit_logs WHERE object_type='DEALER_ADDRESS' AND object_id=?",first)).isEqualTo(2);}
    @Test void wrongDealerForeignScopeAndAccountingWritesAreDenied(){long id=address(),otherSales=user("SALES"),accountant=user("ACCOUNTANT");assertThatThrownBy(()->service.find(otherSales,dealer,id)).isInstanceOf(SecurityException.class);assertThatThrownBy(()->service.save(accountant,dealer,id,input(true,"ACTIVE",1,parentVersion()))).isInstanceOf(SecurityException.class);assertThat(service.list(accountant,dealer,"Cổng",new PageRequest(1,20)).totalItems()).isZero();long other=dealer+100000;assertThatThrownBy(()->Sql.transaction(source,c->DealerAddressService.belonging(c,other,id,false))).isInstanceOf(SecurityException.class);}
    @Test void disabledDefaultMustBeReplacedAndPointsAreNotDeleted(){long first=address();assertThatThrownBy(()->service.save(sales,dealer,first,input(false,"DISCONTINUED",1,parentVersion()))).isInstanceOf(IllegalArgumentException.class);long second=address();service.save(sales,dealer,second,input(true,"ACTIVE",1,parentVersion()));service.save(sales,dealer,first,input(false,"DISCONTINUED",2,parentVersion()));assertThat(service.find(sales,dealer,first)).containsEntry("status","DISCONTINUED");assertThatThrownBy(()->new DealerService(source).delete(manager,dealer,parentVersion())).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("điểm giao");}
    @Test void failedAuditRollsBackBothDefaultsAndDealerVersion(){long first=address(),second=address(),version=parentVersion();failAudit();assertThatThrownBy(()->service.save(sales,dealer,second,input(true,"ACTIVE",1,version))).isInstanceOf(IllegalStateException.class);assertThat(parentVersion()).isEqualTo(version);assertThat(DealerAddressService.isDefault(service.find(sales,dealer,first).get("is_default"))).isTrue();assertThat(DealerAddressService.isDefault(service.find(sales,dealer,second).get("is_default"))).isFalse();}
    @Test void simultaneousDefaultSwitchRequiresReload()throws Exception{long first=address(),second=address(),third=address(),version=parentVersion();var gate=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(2);try{var tasks=List.of(pool.submit(()->switchPoint(second,version,gate)),pool.submit(()->switchPoint(third,version,gate)));gate.countDown();int wins=0;for(var f:tasks)if(f.get(30,TimeUnit.SECONDS))wins++;assertThat(wins).isEqualTo(1);assertThat(count("SELECT COUNT(*) n FROM dealer_addresses WHERE dealer_id=? AND is_default=1",dealer)).isEqualTo(1);}finally{pool.shutdownNow();}}
    boolean switchPoint(long id,long version,CountDownLatch gate)throws InterruptedException{gate.await();try{service.save(sales,dealer,id,input(true,"ACTIVE",1,version));return true;}catch(IllegalArgumentException e){return false;}}
}
