package vn.codegym.salesinventory.dao;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.*;
import org.junit.jupiter.api.*;
import vn.codegym.salesinventory.dto.PageRequest;
import vn.codegym.salesinventory.service.*;
import vn.codegym.salesinventory.validation.FieldValidationException;
import static org.assertj.core.api.Assertions.*;
class DiscountAcceptanceIT extends StoryDatabaseSupport {
    long manager,group,product,category,priceVersion;DiscountService service;LocalDate date=LocalDate.of(2030,1,1);
    @BeforeEach void fixture(){manager=user("SALES_MANAGER");group=Sql.id(one("SELECT id FROM customer_groups LIMIT 1").get("id"));product=product(manager);category=Sql.id(one("SELECT category_id FROM products WHERE id=?",product).get("category_id"));var prices=new PricingService(source);priceVersion=prices.create(manager,group,"Giá QA",date,date,null);prices.saveItem(manager,priceVersion,product,new BigDecimal("100"),new BigDecimal("50"));service=new DiscountService(source);}
    DiscountService.Input input(Long sku,Long category,String mode,String value,long revision){return new DiscountService.Input("Ưu đãi QA",sku,category,group,mode,date,date,"ACTIVE",revision,List.of(new DiscountService.TierInput(new BigDecimal("24"),new BigDecimal(value))));}
    @Test void multiplePoliciesChooseHighestMoneyWithoutStacking(){long percent=service.save(manager,0,input(product,null,"PERCENT","10",0)),fixed=service.save(manager,0,input(product,null,"FIXED","12",0));var q=service.preview(manager,product,group,date,List.of(new BigDecimal("12"),new BigDecimal("12")));assertThat(q.tier().policyId()).isEqualTo(fixed);assertThat(q.totalDiscount()).isEqualByComparingTo("288");assertThat(service.preview(manager,product,group,date,List.of(new BigDecimal("23.999999"))).applied()).isFalse();assertThat(service.find(manager,percent)).containsKey("tiers");}
    @Test void categoryIncludesDescendantsButNeverAddsQuantitiesAcrossSkus(){long child=new CategoryService(source).save(manager,0,"C-"+UUID.randomUUID(),"Nhóm con",category,0);long second=new ProductService(source).save(manager,0,new ProductService.Input("P-"+UUID.randomUUID(),"SKU con",child,"Lon","",null,null,"ACTIVE",0));new PricingService(source).saveItem(manager,priceVersion,second,new BigDecimal("100"),new BigDecimal("50"));service.save(manager,0,input(null,category,"PERCENT","15",0));assertThat(service.preview(manager,second,group,date,List.of(new BigDecimal("24"))).totalDiscount()).isEqualByComparingTo("360");assertThat(service.preview(manager,second,group,date,List.of(new BigDecimal("12"))).applied()).isFalse();assertThat(service.preview(manager,product,group,date,List.of(new BigDecimal("12"))).applied()).isFalse();}
    @Test void revisionsKeepOldTiersAndAuditRollbackRetainsOldPolicy(){long id=service.save(manager,0,input(product,null,"PERCENT","10",0));service.save(manager,id,input(product,null,"PERCENT","12",1));assertThat(count("SELECT COUNT(*) n FROM discount_tiers WHERE policy_id=?",id)).isEqualTo(2);assertThat(service.preview(manager,product,group,date,List.of(new BigDecimal("24"))).tier().revision()).isEqualTo(2);assertThatThrownBy(()->service.save(manager,id,input(product,null,"PERCENT","14",1))).isInstanceOf(FieldValidationException.class);failAudit();assertThatThrownBy(()->service.save(manager,id,input(product,null,"PERCENT","20",2))).isInstanceOf(IllegalStateException.class);assertThat(service.preview(manager,product,group,date,List.of(new BigDecimal("24"))).tier().revision()).isEqualTo(2);}
    @Test void fixedDiscountCannotExceedApplicablePriceAndRolesCannotManage(){assertThatThrownBy(()->service.save(manager,0,input(product,null,"FIXED","101",0))).isInstanceOf(FieldValidationException.class);assertThatThrownBy(()->service.save(user("SALES"),0,input(product,null,"PERCENT","10",0))).isInstanceOf(SecurityException.class);assertThatThrownBy(()->service.search(user("ADMIN"),"",new PageRequest(1,20))).isInstanceOf(SecurityException.class);service.save(manager,0,input(product,null,"FIXED","90",0));new PricingService(source).saveItem(manager,priceVersion,product,new BigDecimal("80"),new BigDecimal("50"));assertThatThrownBy(()->service.preview(manager,product,group,date,List.of(new BigDecimal("24")))).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("vượt giá bán");}
    @Test void duplicateThresholdsAndPercentOver100AreFieldErrors(){var bad=new DiscountService.Input("QA",product,null,group,"PERCENT",date,date,"ACTIVE",0,List.of(new DiscountService.TierInput(BigDecimal.ONE,new BigDecimal("101")),new DiscountService.TierInput(new BigDecimal("1.000000"),BigDecimal.TEN)));assertThat(DiscountService.errors(bad)).containsKeys("value0","minimum1");}
}
