package vn.codegym.salesinventory.dao;

import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import vn.codegym.salesinventory.dto.PageRequest;
import vn.codegym.salesinventory.service.*;
import vn.codegym.salesinventory.validation.FieldValidationException;
import static org.assertj.core.api.Assertions.*;

class OrderAcceptanceIT extends StoryDatabaseSupport {
    long manager,sales,dealer,address,group,warehouse,product,unit,priceVersion;OrderService service;
    final LocalDate date=LocalDate.of(2030,1,1);
    @BeforeEach void fixture(){manager=user("SALES_MANAGER");sales=user("SALES");warehouse=warehouse(manager);group=Sql.id(one("SELECT id FROM customer_groups LIMIT 1").get("id"));long territory=insert("INSERT INTO territories(code,name) VALUES(?,'Khu vực QA')","T-"+UUID.randomUUID());
        dealer=new DealerService(source).save(manager,0,new DealerService.Input("DL-"+UUID.randomUUID(),"Đại lý QA","","0912345678",group,territory,sales,warehouse,"ACTIVE",0));
        address=new DealerAddressService(source).save(manager,dealer,0,new DealerAddressService.Input("123 Đường QA","Người nhận","0912345678","",true,"ACTIVE",0,1));
        product=product(manager);unit=Sql.id(one("SELECT id FROM product_units WHERE product_id=? AND is_base=1",product).get("id"));
        var pricing=new PricingService(source);priceVersion=pricing.create(manager,group,"Giá QA",date,date.plusDays(1),null);pricing.saveItem(manager,priceVersion,product,new BigDecimal("100"),new BigDecimal("50"));
        service=new OrderService(source,Clock.fixed(Instant.parse("2029-12-31T18:00:00Z"),ZoneOffset.UTC));
    }
    OrderService.Input input(long version,OrderService.LineInput... lines){return new OrderService.Input(dealer,address,date.plusDays(2),version,UUID.randomUUID().toString(),List.of(lines));}
    OrderService.LineInput line(String quantity){return new OrderService.LineInput(product,unit,new BigDecimal(quantity));}
    long draft(){return service.save(sales,0,input(0,line("2")));}
    void price(String selling,String floor){new PricingService(source).saveItem(manager,priceVersion,product,new BigDecimal(selling),new BigDecimal(floor));}
    @Test void draftReopensAndSubmitSnapshotsEverythingAtomically(){long id=draft();assertThat(service.find(sales,id)).containsEntry("status","DRAFT");var q=service.quote(sales,id);assertThat(q.date()).isEqualTo(date);assertThat(q.net()).isEqualByComparingTo("200");assertThat(q.display().toString()).doesNotContain("floorPrice","cost_price","owner_id");
        assertThat(service.submit(sales,id,1,q.token(),UUID.randomUUID().toString(),false).submitted()).isTrue();var order=service.find(sales,id);assertThat(order).containsEntry("status","SUBMITTED").containsEntry("address_snapshot","123 Đường QA");assertThat(count("SELECT COUNT(*) n FROM conversion_snapshots WHERE reference_id LIKE ?","ORDER:"+id+":%")).isEqualTo(1);assertThat(count("SELECT COUNT(*) n FROM price_order_references WHERE order_reference=?","ORDER:"+id)).isEqualTo(1);
        assertThatThrownBy(()->service.save(sales,id,input(2,line("3")))).isInstanceOf(FieldValidationException.class);
    }
    @Test void sameSkuAcrossUnitsAndLinesReachesTierButOtherSkuDoesNot(){long box=insert("INSERT INTO product_units(product_id,name,factor,warehouse_id) VALUES(?,'Thùng',12,?)",product,warehouse);
        new DiscountService(source).save(manager,0,new DiscountService.Input("Giảm QA",product,null,group,"PERCENT",date,date,"ACTIVE",0,List.of(new DiscountService.TierInput(new BigDecimal("24"),BigDecimal.TEN))));
        long id=service.save(sales,0,input(0,new OrderService.LineInput(product,box,BigDecimal.ONE),line("12")));var q=service.quote(sales,id);assertThat(q.gross()).isEqualByComparingTo("2400");assertThat(q.discount()).isEqualByComparingTo("240");assertThat(q.lines()).hasSize(2);assertThat(q.lines().get(0).conversion().baseQuantity()).isEqualByComparingTo("12");
        assertThat(service.submit(sales,id,1,q.token(),UUID.randomUUID().toString(),false).submitted()).isTrue();assertThat(count("SELECT COUNT(*) n FROM discount_order_references WHERE order_reference=?","ORDER:"+id)).isEqualTo(1);
    }
    @Test void changedPriceRequiresAcknowledgementAndFinalConfirmationRechecks(){long id=draft();var q=service.quote(sales,id);price("110","50");var changed=service.submit(sales,id,1,q.token(),UUID.randomUUID().toString(),false);assertThat(changed.submitted()).isFalse();assertThat(changed.quote().confirmation()).isTrue();assertThat(changed.quote().net()).isEqualByComparingTo("220");
        assertThat(service.submit(sales,id,1,changed.quote().token(),UUID.randomUUID().toString(),false).submitted()).isFalse();price("120","50");var changedAgain=service.submit(sales,id,1,changed.quote().token(),UUID.randomUUID().toString(),true);assertThat(changedAgain.submitted()).isFalse();assertThat(changedAgain.quote().net()).isEqualByComparingTo("240");assertThat(service.submit(sales,id,1,changedAgain.quote().token(),UUID.randomUUID().toString(),true).submitted()).isTrue();}
    @Test void submitIsIdempotentAcrossRetriesAndTwoTabs(){long id=draft();var q=service.quote(sales,id);String key=UUID.randomUUID().toString();service.submit(sales,id,1,q.token(),key,false);assertThat(service.submit(sales,id,1,q.token(),key,false).order()).isEqualTo(id);assertThat(service.submit(sales,id,1,q.token(),UUID.randomUUID().toString(),false).submitted()).isTrue();assertThat(count("SELECT COUNT(*) n FROM audit_logs WHERE object_type='ORDER' AND object_id=? AND event_type='ORDER_SUBMITTED'",id)).isEqualTo(1);}
    @Test void concurrentSubmissionHasOneSnapshotSet()throws Exception{long id=draft();var q=service.quote(sales,id);var pool=Executors.newFixedThreadPool(2);try{var gate=new CountDownLatch(1);List<Future<Boolean>> tasks=new ArrayList<>();for(int i=0;i<2;i++)tasks.add(pool.submit(()->{gate.await();return service.submit(sales,id,1,q.token(),UUID.randomUUID().toString(),false).submitted();}));gate.countDown();for(var t:tasks)assertThat(t.get(30,TimeUnit.SECONDS)).isTrue();assertThat(count("SELECT COUNT(*) n FROM price_order_references WHERE order_reference=?","ORDER:"+id)).isEqualTo(1);}finally{pool.shutdownNow();}}
    @Test void staleDraftAndCreationKeyCannotOverwrite(){var input=input(0,line("2"));long id=service.save(sales,0,input);assertThat(service.save(sales,0,input)).isEqualTo(id);assertThatThrownBy(()->service.save(sales,0,new OrderService.Input(dealer,address,date.plusDays(2),0,input.creationKey(),List.of(line("3"))))).isInstanceOf(FieldValidationException.class);service.save(sales,id,input(1,line("3")));assertThatThrownBy(()->service.save(sales,id,input(1,line("4")))).isInstanceOf(FieldValidationException.class);}
    @Test void roleScopeAndHandoverOverrideOriginalOwnership(){long id=draft(),next=user("SALES");for(String role:List.of("ADMIN","WAREHOUSE","WAREHOUSE_MANAGER"))assertThatThrownBy(()->service.find(user(role),id)).isInstanceOf(SecurityException.class);
        assertThatThrownBy(()->service.find(next,id)).isInstanceOf(SecurityException.class);update("UPDATE dealers SET primary_staff_id=?,version=version+1 WHERE id=?",next,dealer);assertThatThrownBy(()->service.find(sales,id)).isInstanceOf(SecurityException.class);assertThat(service.find(next,id)).containsEntry("can_edit",false);assertThatThrownBy(()->service.quote(next,id)).isInstanceOf(SecurityException.class);service.takeover(manager,id,1,"Tiếp quản sau bàn giao");assertThat(service.find(manager,id)).containsEntry("can_edit",true);assertThat(Sql.id(service.find(manager,id).get("created_by"))).isEqualTo(sales);assertThatThrownBy(()->service.takeover(next,id,2,"Không có quyền")).isInstanceOf(SecurityException.class);}
    @Test void readonlyAccountingAndDirectorCannotWrite(){long id=draft();for(String role:List.of("ACCOUNTANT","DIRECTOR")){long actor=user(role);assertThat(service.find(actor,id)).containsEntry("can_edit",false);assertThatThrownBy(()->service.save(actor,0,input(0,line("2")))).isInstanceOf(SecurityException.class);}}
    @Test void lockedDealerBlocksNewButKeepsExistingDraft(){long id=draft();var q=service.quote(sales,id);long version=Sql.id(one("SELECT version FROM dealers WHERE id=?",dealer).get("version"));new DealerStatusService(source).change(manager,dealer,version,true,"Tạm khóa QA");assertThatThrownBy(this::draft).isInstanceOf(FieldValidationException.class);var changed=service.submit(sales,id,1,q.token(),UUID.randomUUID().toString(),false);assertThat(changed.submitted()).isFalse();assertThat(changed.quote().warning()).contains("bị khóa");assertThat(service.submit(sales,id,1,changed.quote().token(),UUID.randomUUID().toString(),true).submitted()).isTrue();}
    @Test void missingWarehousePriceOrDiscontinuedSkuRetainsDraft(){update("UPDATE dealers SET warehouse_id=NULL WHERE id=?",dealer);long id=draft();assertThat(service.quote(sales,id).errors()).containsKey("warehouse");update("UPDATE dealers SET warehouse_id=? WHERE id=?",warehouse,dealer);new PricingService(source).deleteItem(manager,priceVersion,Sql.id(one("SELECT id FROM price_items WHERE version_id=? AND product_id=?",priceVersion,product).get("id")));assertThat(service.quote(sales,id).errors()).containsKey("line0");update("UPDATE products SET status='DISCONTINUED' WHERE id=?",product);assertThat(service.quote(sales,id).errors().get("line0")).contains("ngừng bán");assertThat(service.find(sales,id)).containsEntry("status","DRAFT");}
    @Test void belowFloorAfterDiscountAndTinyRoundingNeverSubmit(){price("100","95");new DiscountService(source).save(manager,0,new DiscountService.Input("Giảm QA",product,null,group,"PERCENT",date,date,"ACTIVE",0,List.of(new DiscountService.TierInput(BigDecimal.ZERO,BigDecimal.TEN))));long id=service.save(sales,0,input(0,line("0.000001")));var q=service.quote(sales,id);assertThat(q.errors().get("line0")).contains("giá sàn");assertThat(service.submit(sales,id,1,UUID.randomUUID().toString(),UUID.randomUUID().toString(),true).submitted()).isFalse();}
    @Test void wrongDealerAddressOrWarehouseUnitCannotBeSaved(){long other=warehouse(manager),badUnit=insert("INSERT INTO product_units(product_id,name,factor,warehouse_id) VALUES(?,'Thùng sai',12,?)",product,other);assertThatThrownBy(()->service.save(sales,0,input(0,new OrderService.LineInput(product,badUnit,BigDecimal.ONE)))).isInstanceOf(FieldValidationException.class);assertThatThrownBy(()->service.save(sales,0,new OrderService.Input(dealer,address+100000,date,0,UUID.randomUUID().toString(),List.of(line("1"))))).isInstanceOf(FieldValidationException.class);}
    @Test void auditFailureRollsBackStatusSnapshotsAndMoney(){long id=draft();var q=service.quote(sales,id);failAudit();assertThatThrownBy(()->service.submit(sales,id,1,q.token(),UUID.randomUUID().toString(),false)).isInstanceOf(IllegalStateException.class);assertThat(service.find(sales,id)).containsEntry("status","DRAFT");assertThat(count("SELECT COUNT(*) n FROM price_order_references WHERE order_reference=?","ORDER:"+id)).isZero();assertThat(count("SELECT COUNT(*) n FROM conversion_snapshots WHERE reference_id LIKE ?","ORDER:"+id+":%")).isZero();}
    @Test void vietnamMidnightAndExpiredQuoteRequireNewAcknowledgement(){long id=draft();var q=service.quote(sales,id);var midnight=new OrderService(source,Clock.fixed(Instant.parse("2030-01-01T17:00:00Z"),ZoneOffset.UTC));var changed=midnight.submit(sales,id,1,q.token(),UUID.randomUUID().toString(),false);assertThat(changed.submitted()).isFalse();assertThat(changed.quote().date()).isEqualTo(date.plusDays(1));assertThat(midnight.submit(sales,id,1,changed.quote().token(),UUID.randomUUID().toString(),true).submitted()).isTrue();}
    @Test void paginationSharesAssignedScopeAndStableOrder(){for(int i=0;i<21;i++)draft();var first=service.search(sales,"","DRAFT",dealer,new PageRequest(1,20));assertThat(first.totalItems()).isEqualTo(21);assertThat(first.items()).hasSize(20);assertThat(service.search(sales,"","DRAFT",dealer,new PageRequest(2,20)).items()).hasSize(1);assertThat(service.search(user("SALES"),"","DRAFT",dealer,new PageRequest(1,20)).totalItems()).isZero();}
    @Test void revokedPermissionOrLockedActorCannotSend(){long id=draft();var q=service.quote(sales,id);update("DELETE FROM user_roles WHERE user_id=?",sales);assertThatThrownBy(()->service.submit(sales,id,1,q.token(),UUID.randomUUID().toString(),true)).isInstanceOf(SecurityException.class);update("INSERT INTO user_roles(user_id,role_id) SELECT ?,id FROM roles WHERE code='SALES'",sales);update("UPDATE users SET status='ADMIN_LOCKED' WHERE id=?",sales);assertThatThrownBy(()->service.submit(sales,id,1,q.token(),UUID.randomUUID().toString(),true)).isInstanceOf(SecurityException.class);assertThat(service.find(manager,id)).containsEntry("status","DRAFT");}
    @Test void addressChangeRequiresRequoteAndSnapshotsSurviveLaterEdits(){long id=draft();var q=service.quote(sales,id);update("UPDATE dealer_addresses SET address='Địa chỉ mới',version=version+1 WHERE id=?",address);var changed=service.submit(sales,id,1,q.token(),UUID.randomUUID().toString(),false);assertThat(changed.submitted()).isFalse();assertThat(service.submit(sales,id,1,changed.quote().token(),UUID.randomUUID().toString(),true).submitted()).isTrue();update("UPDATE dealer_addresses SET address='Địa chỉ sau gửi',version=version+1 WHERE id=?",address);update("UPDATE products SET name='Tên sau gửi',version=version+1 WHERE id=?",product);assertThat(service.find(sales,id)).containsEntry("address_snapshot","Địa chỉ mới");@SuppressWarnings("unchecked")var rows=(List<Map<String,Object>>)service.find(sales,id).get("lines");assertThat(rows.get(0)).containsEntry("name_snapshot","Sản phẩm thử");}
    @Test void draftReferencesPreventHardDeletionAndReusedSubmitKeyIsFieldError(){long first=draft(),second=draft();assertThatThrownBy(()->new ProductService(source).delete(manager,product)).isInstanceOf(IllegalArgumentException.class);var q1=service.quote(sales,first);var q2=service.quote(sales,second);String key=UUID.randomUUID().toString();service.submit(sales,first,1,q1.token(),key,false);assertThatThrownBy(()->service.submit(sales,second,1,q2.token(),key,false)).isInstanceOfSatisfying(FieldValidationException.class,e->assertThat(e.errors()).containsKey("submitKey"));assertThat(service.find(sales,second)).containsEntry("status","DRAFT");}
}
