package vn.codegym.salesinventory.dao;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.*;
import org.mockito.ArgumentCaptor;
import vn.codegym.salesinventory.dto.*;
import vn.codegym.salesinventory.security.*;
import vn.codegym.salesinventory.service.*;
import vn.codegym.salesinventory.validation.FieldValidationException;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
class PortalAcceptanceIT extends StoryDatabaseSupport {
    static final AtomicInteger phones=new AtomicInteger(10000000);long manager,sales,dealer,second,address,product,unit,group,warehouse;PortalAccountService accounts;MailService mail;ActivationService activation;String username;Clock clock;
    @BeforeEach void fixture(){manager=user("SALES_MANAGER");sales=user("SALES");group=Sql.id(one("SELECT id FROM customer_groups LIMIT 1").get("id"));warehouse=warehouse(manager);long territory=insert("INSERT INTO territories(code,name) VALUES(?,'Khu vực QA')","T-"+UUID.randomUUID());var dealers=new DealerService(source);dealer=dealers.save(manager,0,new DealerService.Input("DL-"+UUID.randomUUID(),"Đại lý một","","0912345678",group,territory,sales,warehouse,"ACTIVE",0));second=dealers.save(manager,0,new DealerService.Input("DL-"+UUID.randomUUID(),"Đại lý hai","","0912345678",group,territory,sales,warehouse,"ACTIVE",0));address=new DealerAddressService(source).save(manager,dealer,0,new DealerAddressService.Input("123 QA","Người nhận","0912345678","",true,"ACTIVE",0,1));product=product(manager);unit=Sql.id(one("SELECT id FROM product_units WHERE product_id=? AND is_base=1",product).get("id"));LocalDate today=LocalDate.now(vn.codegym.salesinventory.config.VietnamTime.ZONE);var pricing=new PricingService(source);long version=pricing.create(manager,group,"Giá cổng QA",today,today.plusDays(1),null);pricing.saveItem(manager,version,product,new BigDecimal("100"),new BigDecimal("50"));
        clock=Clock.systemUTC();mail=mock(MailService.class);activation=new ActivationService(source,clock,"http://qa.local",mail);PasswordHasher hasher=mock(PasswordHasher.class);when(hasher.hash(anyString())).thenReturn("qa-hash-not-a-secret");accounts=new PortalAccountService(source,activation,hasher,clock);username="portal-"+UUID.randomUUID();}
    long create(){return accounts.create(manager,dealer,username,username+"@qa.local","Đại lý QA","09"+phones.getAndIncrement());}
    long active(){long id=create();update("UPDATE users SET status='ACTIVE',must_change_password=0 WHERE id=?",id);return id;}
    OrderService.Input input(long version){return new OrderService.Input(dealer,address,LocalDate.now(vn.codegym.salesinventory.config.VietnamTime.ZONE).plusDays(2),version,UUID.randomUUID().toString(),List.of(new OrderService.LineInput(product,unit,BigDecimal.ONE)));}
    @Test void salesManagerIssuesOnlyDealerAccountWithoutUserManageAndActivationIsReused(){assertThat(new AccessService(source).load(manager).allows("USER_MANAGE")).isFalse();long id=create();assertThat(one("SELECT account_kind,status FROM users WHERE id=?",id)).containsEntry("account_kind","DEALER").containsEntry("status","PENDING_ACTIVATION");assertThat(query("SELECT r.code FROM roles r JOIN user_roles ur ON ur.role_id=r.id WHERE ur.user_id=?",id)).hasSize(1).first().isEqualTo(Map.of("code","DEALER"));var url=ArgumentCaptor.forClass(String.class);verify(mail).sendActivation(anyString(),anyString(),anyString(),anyString(),url.capture());assertThat(activation.activate(url.getValue().split("token=")[1])).isTrue();assertThat(accounts.profile(id)).containsEntry("name","Đại lý một");assertThat(count("SELECT COUNT(*) n FROM portal_mail_attempts WHERE username_normalized=? AND state='SUCCEEDED'",username)).isEqualTo(1);assertThat(query("SELECT * FROM portal_mail_attempts WHERE username_normalized=?",username).toString()).doesNotContain("password","token");}
    @Test void multiplePortalAccountsCanLinkSameDealerAndOnlyManagerCanManage(){long first=create();username="portal-"+UUID.randomUUID();long next=create();assertThat(first).isNotEqualTo(next);assertThat(count("SELECT COUNT(*) n FROM dealer_accounts WHERE dealer_id=?",dealer)).isEqualTo(2);for(String role:List.of("ADMIN","SALES","ACCOUNTANT","DIRECTOR","WAREHOUSE_MANAGER"))assertThatThrownBy(()->accounts.search(user(role),"",null,new PageRequest(1,20))).isInstanceOf(SecurityException.class);}
    @Test void portalQuotesAndSubmitsWithoutGeneralPriceCatalogPermissions(){long actor=active();var a=new AccessService(source).load(actor);assertThat(a.permissions()).doesNotContain("PRICE_READ","CATALOG_READ","USER_MANAGE","COST_READ","ORDER_READ");var service=new OrderService(source);long id=service.save(actor,0,input(0));var q=service.quote(actor,id);assertThat(q.net()).isEqualByComparingTo("100");assertThat(service.submit(actor,id,1,q.token(),UUID.randomUUID().toString(),false).submitted()).isTrue();var row=service.find(actor,id);assertThat(row).doesNotContainKeys("owner_id","created_by","creation_key","creation_hash","submit_key","floor_price","cost_price");assertThat(row).containsEntry("can_edit",false);assertThat(q.display().toString()).doesNotContain("floor","cost","staff");}
    @Test void differentDealersCannotReadCountSuggestQuoteOrMutateEachOther(){long actor=active();var orders=new OrderService(source);long id=orders.save(actor,0,input(0));username="portal-"+UUID.randomUUID();long other=accounts.create(manager,second,username,username+"@qa.local","Đại lý khác","09"+phones.getAndIncrement());update("UPDATE users SET status='ACTIVE' WHERE id=?",other);assertThatThrownBy(()->orders.find(other,id)).isInstanceOf(SecurityException.class);assertThatThrownBy(()->orders.quote(other,id)).isInstanceOf(SecurityException.class);assertThatThrownBy(()->orders.preview(other,input(0))).isInstanceOf(SecurityException.class);assertThatThrownBy(()->orders.addresses(other,dealer)).isInstanceOf(SecurityException.class);assertThat(orders.search(other,"","",dealer,new PageRequest(1,20)).totalItems()).isZero();assertThatThrownBy(()->new LookupService(source).search(actor,"users","qa")).isInstanceOf(SecurityException.class);assertThatThrownBy(()->new LookupService(source).search(actor,"dealers","qa")).isInstanceOf(SecurityException.class);}
    @Test void relinkRevokesSessionsAndKeepsOldOrderDealerAndOwnership(){long actor=active();var orders=new OrderService(source);long id=orders.save(actor,0,input(0));update("INSERT INTO user_sessions(id,user_id,token_hash,created_at,last_activity_at,expires_at,ip_address,user_agent) VALUES(?,?,?,NOW(),NOW(),DATE_ADD(NOW(),INTERVAL 1 DAY),'127.0.0.1','QA')",UUID.randomUUID().toString(),actor,TokenHashing.sha256(UUID.randomUUID().toString()));
        accounts.relink(manager,actor,1,second,"Đổi đơn vị giao dịch");assertThat(count("SELECT COUNT(*) n FROM user_sessions WHERE user_id=? AND revoked_at IS NULL",actor)).isZero();assertThatThrownBy(()->orders.find(actor,id)).isInstanceOf(SecurityException.class);assertThat(Sql.id(one("SELECT dealer_id,owner_id FROM orders WHERE id=?",id).get("dealer_id"))).isEqualTo(dealer);assertThat(Sql.id(one("SELECT owner_id FROM orders WHERE id=?",id).get("owner_id"))).isEqualTo(actor);assertThat(accounts.linkHistory(manager,actor,new PageRequest(1,20)).totalItems()).isEqualTo(1);assertThatThrownBy(()->accounts.relink(manager,actor,1,dealer,"Cũ")).isInstanceOf(FieldValidationException.class);}
    @Test void roleAndPermissionBoundariesAreEnforcedByServicesAndDatabase(){long actor=active();assertThatThrownBy(()->new AssignmentService(source).assign(user("ADMIN"),actor,Set.of("SALES"),Set.of(),Set.of())).isInstanceOf(SecurityException.class);assertThatThrownBy(()->update("INSERT INTO user_roles(user_id,role_id) SELECT ?,id FROM roles WHERE code='ADMIN'",actor)).isInstanceOf(IllegalStateException.class);assertThatThrownBy(()->update("INSERT INTO user_roles(user_id,role_id) SELECT ?,id FROM roles WHERE code='DEALER'",manager)).isInstanceOf(IllegalStateException.class);assertThatThrownBy(()->update("INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='DEALER' AND p.code='USER_MANAGE'")).isInstanceOf(IllegalStateException.class);assertThatThrownBy(()->update("UPDATE users SET account_kind='INTERNAL' WHERE id=?",actor)).isInstanceOf(IllegalStateException.class);}
    @Test void portalCannotEditAnotherOwnersDraftOrTakeOverButManagerCan(){long actor=active();var orders=new OrderService(source);long id=orders.save(sales,0,input(0));assertThat(orders.find(actor,id)).containsEntry("can_edit",false).containsEntry("can_takeover",false);assertThatThrownBy(()->orders.save(actor,id,input(1))).isInstanceOf(SecurityException.class);assertThatThrownBy(()->orders.takeover(actor,id,1,"Giả mạo")).isInstanceOf(SecurityException.class);}
    @Test void accountLockBlocksPortalAndRestoresPendingStatus(){long actor=create();accounts.status(manager,actor,1,true,"Khóa QA");assertThatThrownBy(()->accounts.profile(actor)).isInstanceOf(SecurityException.class);accounts.status(manager,actor,2,false,"Mở QA");assertThat(one("SELECT status FROM users WHERE id=?",actor)).containsEntry("status","PENDING_ACTIVATION");}
    @Test void portalCatalogHasOnlySaleableGroupOffersNoSensitiveProjection(){long actor=active();var catalog=new PortalCatalogService(source);String sku=Sql.text(one("SELECT sku FROM products WHERE id=?",product).get("sku"));var results=catalog.suggest(actor,sku);assertThat(results).hasSize(1);assertThat(results.get(0)).containsOnlyKeys("id","code","name");assertThat(catalog.search(actor,sku,new PageRequest(1,20)).totalItems()).isEqualTo(1);long unpriced=product(manager);String hidden=Sql.text(one("SELECT sku FROM products WHERE id=?",unpriced).get("sku"));assertThat(catalog.suggest(actor,hidden)).isEmpty();assertThatThrownBy(()->catalog.search(manager,"",new PageRequest(1,20))).isInstanceOf(SecurityException.class);}
    @Test void ambiguousMailLeavesDurableReviewAndNeverAutomaticallyResends(){doThrow(new MailDeliveryFailure(false,new java.net.SocketTimeoutException())).when(mail).sendActivation(anyString(),anyString(),anyString(),anyString(),anyString());assertThatThrownBy(this::create).isInstanceOf(FieldValidationException.class);assertThat(count("SELECT COUNT(*) n FROM users WHERE username_normalized=?",username)).isZero();assertThat(count("SELECT COUNT(*) n FROM portal_mail_attempts WHERE username_normalized=? AND state='REVIEW'",username)).isEqualTo(1);assertThatThrownBy(this::create).isInstanceOf(FieldValidationException.class);verify(mail,times(1)).sendActivation(anyString(),anyString(),anyString(),anyString(),anyString());}
    @Test void definitiveMailFailureRollsBackDataAndAllowsExplicitRetry(){doThrow(new MailDeliveryFailure(true,new IllegalStateException("rejected"))).when(mail).sendActivation(anyString(),anyString(),anyString(),anyString(),anyString());assertThatThrownBy(this::create).isInstanceOf(FieldValidationException.class);assertThat(count("SELECT COUNT(*) n FROM users WHERE username_normalized=?",username)).isZero();assertThat(count("SELECT COUNT(*) n FROM portal_mail_attempts WHERE username_normalized=? AND state='FAILED'",username)).isEqualTo(1);doNothing().when(mail).sendActivation(anyString(),anyString(),anyString(),anyString(),anyString());assertThat(create()).isPositive();}
    @Test void relinkAuditFailureRollsBackLinkAndSessionRevocation(){long actor=active();failAudit();assertThatThrownBy(()->accounts.relink(manager,actor,1,second,"Không commit")).isInstanceOf(IllegalStateException.class);assertThat(Sql.id(one("SELECT dealer_id FROM dealer_accounts WHERE user_id=?",actor).get("dealer_id"))).isEqualTo(dealer);assertThat(accounts.linkHistory(manager,actor,new PageRequest(1,20)).totalItems()).isZero();}
}
