package vn.codegym.salesinventory.dao;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.*;
import org.junit.jupiter.api.*;
import vn.codegym.salesinventory.dto.PageRequest;
import vn.codegym.salesinventory.service.*;
import static org.assertj.core.api.Assertions.*;
class PriceHistoryAcceptanceIT extends StoryDatabaseSupport {
    long manager,product,group,version;PricingService prices;PriceHistoryService history;LocalDate day=LocalDate.of(2031,1,1);
    @BeforeEach void fixture(){manager=user("SALES_MANAGER");product=product(manager);group=Sql.id(one("SELECT id FROM customer_groups LIMIT 1").get("id"));prices=new PricingService(source);history=new PriceHistoryService(source);version=prices.create(manager,group,"Giá QA",day,day,null);}
    PriceHistoryService.Filter filter(){return new PriceHistoryService.Filter("",product,group,null,null);}
    @Test void createUpdatePeriodAndDeleteRecordBeforeAfterOnSameTransaction(){prices.saveItem(manager,version,product,new BigDecimal("100.1234"),new BigDecimal("50"));prices.saveItem(manager,version,product,new BigDecimal("120.5678"),new BigDecimal("60"));prices.edit(manager,version,3,"Giá đổi hiệu lực",day,day.plusDays(1));long item=Sql.id(one("SELECT id FROM price_items WHERE version_id=? AND product_id=?",version,product).get("id"));prices.deleteItem(manager,version,item,4);var rows=history.search(manager,filter(),new PageRequest(1,20));assertThat(rows.totalItems()).isEqualTo(4);assertThat(rows.items()).extracting(r->r.get("event_type")).containsExactly("ITEM_DELETED","VERSION_CHANGED","ITEM_UPDATED","ITEM_CREATED");assertThat(rows.items().get(0).get("new_selling")).isNull();assertThat((BigDecimal)rows.items().get(2).get("old_selling")).isEqualByComparingTo("100.1234");assertThat(rows.items().get(1).get("new_to").toString()).isEqualTo(day.plusDays(1).toString());assertThat(rows.items().get(3).get("old_selling")).isNull();assertThat(query("SELECT id FROM price_items WHERE id=?",item)).isEmpty();assertThatThrownBy(()->new ProductService(source).delete(manager,product)).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("lịch sử giá");}
    @Test void actorProductAndGroupNamesRemainSnapshotsAndNoCostFieldAppears(){prices.saveItem(manager,version,product,new BigDecimal("100"),new BigDecimal("50"));update("UPDATE users SET full_name='Tên đã đổi' WHERE id=?",manager);update("UPDATE products SET name='Tên SKU đã đổi' WHERE id=?",product);var row=history.search(user("SALES"),filter(),new PageRequest(1,20)).items().get(0);assertThat(row).containsEntry("actor_name_snapshot","Người thử").containsEntry("product_name_snapshot","Sản phẩm thử");assertThat(row.toString()).doesNotContain("cost_price","password_hash");assertThat(row.get("display_time").toString()).matches("[0-9]{2}/[0-9]{2}/[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2}");}
    @Test void inheritanceHasVerifiedOldPricesAndNewApplyWindow(){prices.saveItem(manager,version,product,new BigDecimal("100"),new BigDecimal("50"));long next=prices.create(manager,group,"Kế thừa",day.plusDays(1),day.plusDays(2),version);var row=history.search(manager,filter(),new PageRequest(1,20)).items().get(0);assertThat(row.get("event_type")).isEqualTo("ITEM_INHERITED");assertThat(Sql.id(row.get("version_id"))).isEqualTo(next);assertThat((BigDecimal)row.get("old_selling")).isEqualByComparingTo("100");assertThat(row.get("old_from").toString()).isEqualTo(day.toString());assertThat(row.get("new_from").toString()).isEqualTo(day.plusDays(1).toString());}
    @Test void failedAuditRollsBackBusinessPriceAndHistory(){failAudit();assertThatThrownBy(()->prices.saveItem(manager,version,product,new BigDecimal("100"),new BigDecimal("50"))).isInstanceOf(IllegalStateException.class);assertThat(history.search(manager,filter(),new PageRequest(1,20)).totalItems()).isZero();assertThat(query("SELECT id FROM price_items WHERE version_id=?",version)).isEmpty();}
    @Test void pagingFiltersAndMalformedDatesAreSafe(){for(int i=0;i<21;i++)prices.saveItem(manager,version,product,new BigDecimal(100+i),new BigDecimal("50"));var p=history.search(manager,filter(),new PageRequest(999,20));assertThat(p.page()).isEqualTo(2);assertThat(p.items()).hasSize(1);assertThat(p.totalItems()).isEqualTo(21);assertThat(history.search(manager,new PriceHistoryService.Filter("",product,group,LocalDate.of(9999,12,31),LocalDate.of(9999,12,31)),new PageRequest(1,20)).totalItems()).isZero();assertThatThrownBy(()->history.search(manager,new PriceHistoryService.Filter("",product,group,LocalDate.of(999999,1,1),null),new PageRequest(1,20))).isInstanceOf(IllegalArgumentException.class);}
}
