package vn.codegym.salesinventory.dao;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import vn.codegym.salesinventory.service.*;
import vn.codegym.salesinventory.validation.FieldValidationException;
import static org.assertj.core.api.Assertions.*;
class PricingAcceptanceIT extends StoryDatabaseSupport {
    long manager,product,group;PricingService pricing;final LocalDate from=LocalDate.of(2027,1,1),to=from.plusDays(30);
    @BeforeEach void fixture(){manager=user("SALES_MANAGER");product=product(manager);pricing=new PricingService(source);group=Sql.id(pricing.groups().get(0).get("id"));}
    long version(){return pricing.create(manager,group," Giá thử ",from,to,null);}
    @Test void threeGroupsInclusiveDatesAndSeparatedPrices(){assertThat(pricing.groups().stream().map(r->r.get("code"))).containsExactly("DEALER_1","DEALER_2","RETAIL");for(var g:pricing.groups()){long id=Sql.id(g.get("id")),v=pricing.create(manager,id,"Giá nhóm",from,to,null);pricing.saveItem(manager,v,product,new BigDecimal("100"),new BigDecimal("90"),1);assertThat(pricing.quote(manager,id,product,from).sellingPrice()).isEqualByComparingTo("100");assertThat(pricing.quote(manager,id,product,to).floorPrice()).isEqualByComparingTo("90");assertThatThrownBy(()->pricing.quote(manager,id,product,from.minusDays(1))).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->pricing.quote(manager,id,product,to.plusDays(1))).isInstanceOf(IllegalArgumentException.class);}}
    @Test void inclusiveOverlapRejectedAndAdjacentDatesAllowed(){long v=version();pricing.saveItem(manager,v,product,BigDecimal.TEN,BigDecimal.ONE,1);long overlap=pricing.create(manager,group,"Chồng",to,to.plusDays(2),null);assertThatThrownBy(()->pricing.saveItem(manager,overlap,product,BigDecimal.TEN,BigDecimal.ONE,1)).isInstanceOf(FieldValidationException.class);long next=pricing.create(manager,group,"Kế tiếp",to.plusDays(1),to.plusDays(2),null);pricing.saveItem(manager,next,product,BigDecimal.TEN,BigDecimal.ONE,1);}
    @Test void staleItemAndDeleteRevisionsCannotOverwrite(){long v=version();pricing.saveItem(manager,v,product,BigDecimal.TEN,BigDecimal.ONE,1);long item=Sql.id(pricing.items(manager,v).get(0).get("id"));assertThatThrownBy(()->pricing.saveItem(manager,v,product,new BigDecimal("20"),BigDecimal.ONE,1)).hasMessageContaining("thay đổi");assertThatThrownBy(()->pricing.deleteItem(manager,v,item,1)).hasMessageContaining("thay đổi");pricing.deleteItem(manager,v,item,2);assertThat(pricing.items(manager,v)).isEmpty();}
    @Test void sameRevisionConcurrentUpdatesHaveOneWinner()throws Exception{long v=version();var gate=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(2);try{Callable<Boolean> call=()->{gate.await();try{pricing.saveItem(manager,v,product,BigDecimal.TEN,BigDecimal.ONE,1);return true;}catch(FieldValidationException stale){return false;}};var a=pool.submit(call);var b=pool.submit(call);gate.countDown();assertThat(List.of(a.get(30,TimeUnit.SECONDS),b.get(30,TimeUnit.SECONDS))).containsExactlyInAnyOrder(true,false);assertThat(Sql.id(one("SELECT revision FROM price_versions WHERE id=?",v).get("revision"))).isEqualTo(2);}finally{pool.shutdownNow();}}
    @Test void usedVersionIsImmutableAndInheritedSnapshotStaysUnchanged(){long v=version();pricing.saveItem(manager,v,product,new BigDecimal("100"),new BigDecimal("90"),1);long snap=Sql.transaction(source,c->PricingService.snapshot(c,"ORDER-"+UUID.randomUUID(),PricingService.quote(c,new AccessService(source).load(manager),group,product,from)));var before=one("SELECT * FROM price_order_references WHERE id=?",snap);long item=Sql.id(pricing.items(manager,v).get(0).get("id"));assertThatThrownBy(()->pricing.saveItem(manager,v,product,new BigDecimal("110"),BigDecimal.ONE,2)).hasMessageContaining("đã được dùng");assertThatThrownBy(()->pricing.edit(manager,v,2,"Đổi",from,to)).isInstanceOf(FieldValidationException.class);assertThatThrownBy(()->pricing.deleteItem(manager,v,item,2)).isInstanceOf(FieldValidationException.class);long next=pricing.create(manager,group,"Kế thừa",to.plusDays(1),to.plusDays(30),v);pricing.saveItem(manager,next,product,new BigDecimal("120"),new BigDecimal("95"),1);assertThat(one("SELECT * FROM price_order_references WHERE id=?",snap)).isEqualTo(before);assertThat(pricing.quote(manager,group,product,to).sellingPrice()).isEqualByComparingTo("100");assertThat(pricing.quote(manager,group,product,to.plusDays(1)).sellingPrice()).isEqualByComparingTo("120");}
    @Test void inheritWrongGroupAndInvalidNumbersRejected(){long v=version();long other=Sql.id(pricing.groups().get(1).get("id"));assertThatThrownBy(()->pricing.create(manager,other,"Sai nhóm",from,to,v)).isInstanceOf(FieldValidationException.class);for(BigDecimal selling:new BigDecimal[]{new BigDecimal("-1"),new BigDecimal("0.9999"),new BigDecimal("1.00001"),new BigDecimal("1E999999999")})assertThatThrownBy(()->pricing.saveItem(manager,v,product,selling,BigDecimal.ONE,1)).isInstanceOf(FieldValidationException.class);pricing.saveItem(manager,v,product,BigDecimal.ONE,BigDecimal.ONE,1);assertThat(pricing.quote(manager,group,product,from).requiresApproval(BigDecimal.ONE)).isFalse();}
    @Test void auditFailuresRollbackCreateEditItemAndDelete(){long v=version();pricing.saveItem(manager,v,product,BigDecimal.TEN,BigDecimal.ONE,1);long item=Sql.id(pricing.items(manager,v).get(0).get("id"));var before=one("SELECT * FROM price_versions WHERE id=?",v);var oldItems=pricing.items(manager,v);long total=count("SELECT COUNT(*) n FROM price_versions");failAudit();assertThatThrownBy(()->pricing.create(manager,group,"Không lưu",from,to,null)).isInstanceOf(IllegalStateException.class);assertThat(count("SELECT COUNT(*) n FROM price_versions")).isEqualTo(total);assertThatThrownBy(()->pricing.edit(manager,v,2,"Không sửa",from,to)).isInstanceOf(IllegalStateException.class);assertThatThrownBy(()->pricing.saveItem(manager,v,product,new BigDecimal("20"),BigDecimal.ONE,2)).isInstanceOf(IllegalStateException.class);assertThatThrownBy(()->pricing.deleteItem(manager,v,item,2)).isInstanceOf(IllegalStateException.class);assertThat(one("SELECT * FROM price_versions WHERE id=?",v)).isEqualTo(before);assertThat(pricing.items(manager,v)).isEqualTo(oldItems);}
    @Test void nonManagersAcrossSevenRolesCannotWrite(){for(String role:new String[]{"ADMIN","SALES","WAREHOUSE","WAREHOUSE_MANAGER","ACCOUNTANT","DIRECTOR"})assertThatThrownBy(()->pricing.create(user(role),group,"Giá",from,to,null)).isInstanceOf(SecurityException.class);}
}
