package vn.codegym.salesinventory.dao;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
import vn.codegym.salesinventory.service.*;
import static org.assertj.core.api.Assertions.*;
class ProductImportAcceptanceIT extends StoryDatabaseSupport {
    long manager,cat;String code;ProductImportService imports;
    @BeforeEach void fixture(){manager=user("SALES_MANAGER");cat=category(manager);code=Sql.text(one("SELECT code FROM categories WHERE id=?",cat).get("code"));imports=new ProductImportService(source);}
    List<String> line(String sku,String name){return List.of(sku,name,code,"Lon","","ACTIVE","100.1234");}
    ImportPreview preview(List<String>...lines){var rows=new ArrayList<List<String>>();rows.add(ProductImportService.headers(new AccessService(source).load(manager)));rows.addAll(List.of(lines));return imports.preview(manager,Xlsx.write(rows));}
    @Test void mixedRowsCreateUpdateAndCaseDuplicates(){long id=product(manager);String sku=Sql.text(one("SELECT sku FROM products WHERE id=?",id).get("sku"));String next="I-"+UUID.randomUUID();var p=preview(line(sku,"Cập nhật"),line(next,"Tạo mới"),line(next.toLowerCase(Locale.ROOT),"Trùng"),List.of("INVALID","Sai","MISSING","Lon","","ACTIVE","1"));assertThat(p.getLines().stream().map(ImportPreview.Line::operation)).containsExactly("Cập nhật","Tạo mới","Tạo mới","Tạo mới");var report=imports.confirm(manager,p,p.getToken());assertThat(report.stream().filter(ImportPreview.Line::isValid).count()).isEqualTo(2);assertThat(one("SELECT name FROM products WHERE id=?",id)).containsEntry("name","Cập nhật");assertThatThrownBy(()->imports.confirm(manager,p,p.getToken())).isInstanceOf(IllegalArgumentException.class);}
    @Test void staleVersionIsRejectedWithoutOverwriting(){long id=product(manager);var old=one("SELECT * FROM products WHERE id=?",id);var p=preview(line(Sql.text(old.get("sku")),"Không ghi đè"));new ProductService(source).save(manager,id,new ProductService.Input(Sql.text(old.get("sku")),"Đã sửa sau preview",Sql.id(old.get("category_id")),"Lon","",null,null,"ACTIVE",1));assertThat(imports.confirm(manager,p,p.getToken()).get(0).error()).contains("thay đổi");assertThat(one("SELECT name FROM products WHERE id=?",id)).containsEntry("name","Đã sửa sau preview");}
    @Test void replacedProductAndCreatedSkuAreRejected(){long id=product(manager);String sku=Sql.text(one("SELECT sku FROM products WHERE id=?",id).get("sku"));var p=preview(line(sku,"Ghi đè"));new ProductService(source).delete(manager,id);new ProductService(source).save(manager,0,new ProductService.Input(sku,"Bản thay thế",cat,"Lon","",null,null,"ACTIVE",0));assertThat(imports.confirm(manager,p,p.getToken()).get(0).error()).contains("thay đổi");String next="I-"+UUID.randomUUID();var create=preview(line(next,"Tạo"));new ProductService(source).save(manager,0,new ProductService.Input(next,"Tạo sau preview",cat,"Lon","",null,null,"ACTIVE",0));assertThat(imports.confirm(manager,create,create.getToken()).get(0).error()).contains("thay đổi");}
    @Test void ownerExpiryAndRevokedPermission(){var p=preview(line("I-"+UUID.randomUUID(),"Tên"));assertThatThrownBy(()->imports.confirm(user("SALES_MANAGER"),p,p.getToken())).isInstanceOf(IllegalArgumentException.class);var expired=new ImportPreview(manager,p.getLines(),Instant.now().minusSeconds(1800),Map.of(2,p.productState(2)),true);assertThatThrownBy(()->imports.confirm(manager,expired,expired.getToken())).isInstanceOf(IllegalArgumentException.class);update("DELETE FROM user_roles WHERE user_id=?",manager);assertThatThrownBy(()->imports.confirm(manager,p,p.getToken())).isInstanceOf(SecurityException.class);}
    @Test void costPermissionCannotBeBypassedOrLeaked(){long restricted=user("WAREHOUSE");long role=insert("INSERT INTO roles(code,name) VALUES(?,'Nhập không giá vốn')","R-"+UUID.randomUUID());update("INSERT INTO role_permissions(role_id,permission_id) SELECT ?,id FROM permissions WHERE code IN ('PRODUCT_MANAGE','CATALOG_READ')",role);update("INSERT INTO user_roles(user_id,role_id) VALUES(?,?)",restricted,role);assertThatThrownBy(()->imports.preview(restricted,Xlsx.write(List.of(ProductImportService.headers(new AccessService(source).load(manager)),line("I-X","Tên"))))).isInstanceOf(SecurityException.class);assertThatThrownBy(()->imports.preview(restricted,Xlsx.write(List.of(ProductImportService.HEADERS,line("I-X","Tên"))))).isInstanceOf(SecurityException.class);var plain=imports.preview(restricted,Xlsx.write(List.of(ProductImportService.HEADERS,List.of("I-"+UUID.randomUUID(),"Tên",code,"Lon","","ACTIVE"))));assertThat(imports.confirm(restricted,plain,plain.getToken()).get(0).isValid()).isTrue();update("INSERT INTO user_roles(user_id,role_id) SELECT ?,id FROM roles WHERE code='SALES_MANAGER'",restricted);var p=imports.preview(restricted,Xlsx.write(List.of(ProductImportService.headers(new AccessService(source).load(restricted)),line("I-"+UUID.randomUUID(),"Tên"))));update("DELETE ur FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=? AND r.code='SALES_MANAGER'",restricted);assertThatThrownBy(()->imports.confirm(restricted,p,p.getToken())).isInstanceOf(SecurityException.class);}
    @Test void auditFailurePropagatesAndRollsBackInsteadOfBecomingInputError(){String sku="I-"+UUID.randomUUID();var p=preview(line(sku,"Không lưu"));failAudit();assertThatThrownBy(()->imports.confirm(manager,p,p.getToken())).isInstanceOf(IllegalStateException.class);assertThat(query("SELECT id FROM products WHERE sku=?",sku)).isEmpty();assertThatThrownBy(()->imports.confirm(manager,p,p.getToken())).isInstanceOf(IllegalArgumentException.class);}
    @Test void rejectsEmptyBadHeadersMalformedAndOversizedFiles(){assertThatThrownBy(()->imports.preview(manager,Xlsx.write(List.of(ProductImportService.HEADERS)))).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->imports.preview(manager,Xlsx.write(List.of(List.of("BAD"),List.of("X"))))).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->imports.preview(manager,"bad".getBytes())).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->imports.preview(manager,new byte[Xlsx.MAX_BYTES+1])).isInstanceOf(IllegalArgumentException.class);}
    @Test void fiveThousandSkusPersistWithIndividualAudits(){String prefix="B-"+UUID.randomUUID()+"-";var rows=new ArrayList<List<String>>();rows.add(ProductImportService.headers(new AccessService(source).load(manager)));for(int i=0;i<5000;i++)rows.add(line(prefix+i,"Sản phẩm "+i));var p=imports.preview(manager,Xlsx.write(rows));assertThat(p.getLines()).hasSize(5000);assertThat(imports.confirm(manager,p,p.getToken()).stream().filter(ImportPreview.Line::isValid).count()).isEqualTo(5000);assertThat(count("SELECT COUNT(*) n FROM products WHERE sku LIKE ?",prefix+"%")).isEqualTo(5000);assertThat(count("SELECT COUNT(*) n FROM audit_logs a JOIN products p ON p.id=a.object_id WHERE a.object_type='PRODUCT' AND p.sku LIKE ?",prefix+"%")).isEqualTo(5000);}
}
