package vn.codegym.salesinventory.dao;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import vn.codegym.salesinventory.service.*;
import vn.codegym.salesinventory.validation.FieldValidationException;
import static org.assertj.core.api.Assertions.*;
class SupplierAcceptanceIT extends StoryDatabaseSupport {
    @Test void readOnlyWarehouseManagerCannotReadSuppliersOutsideAssignment() {
        long own=save(),other=user("WAREHOUSE_MANAGER"),otherWarehouse=warehouse(other);
        long foreign=suppliers.save(other,0,input("FOREIGN-"+UUID.randomUUID(),otherWarehouse,0,"ACTIVE"));
        var grant=one("SELECT rp.role_id,rp.permission_id FROM role_permissions rp JOIN roles r ON r.id=rp.role_id JOIN permissions p ON p.id=rp.permission_id WHERE r.code='WAREHOUSE_MANAGER' AND p.code='WAREHOUSE_MANAGE'");
        update("DELETE FROM role_permissions WHERE role_id=? AND permission_id=?",grant.get("role_id"),grant.get("permission_id"));
        try {
            assertThat(new AccessService(source).load(manager).allows("WAREHOUSE_MANAGE")).isFalse();
            assertThat(suppliers.list(manager,"")).anyMatch(r->Sql.id(r.get("id"))==own).noneMatch(r->Sql.id(r.get("id"))==foreign);
            assertThatThrownBy(()->suppliers.find(manager,foreign)).isInstanceOf(SecurityException.class);
        } finally {update("INSERT INTO role_permissions(role_id,permission_id) VALUES(?,?)",grant.get("role_id"),grant.get("permission_id"));}
    }
    long manager,wh;SupplierService suppliers;
    @BeforeEach void fixture(){manager=user("WAREHOUSE_MANAGER");wh=warehouse(manager);suppliers=new SupplierService(source);}
    SupplierService.Input input(String code,long warehouse,long version,String status){return new SupplierService.Input(code," Nhà cung cấp O'An ","0123456789-001"," Liên hệ ","+84912345678"," Trả ngay ",warehouse,status,version);}
    long save(){return suppliers.save(manager,0,input("S-"+UUID.randomUUID(),wh,0,"ACTIVE"));}
    @Test void normalizedValuesAndAuditBeforeAfter(){long id=save();var row=one("SELECT * FROM suppliers WHERE id=?",id);assertThat(row).containsEntry("name","Nhà cung cấp O'An").containsEntry("contact_phone","0912345678").containsEntry("payment_terms","Trả ngay");suppliers.save(manager,id,input(Sql.text(row.get("code")),wh,1,"DISCONTINUED"));var audit=one("SELECT actor_user_id,before_values,after_values FROM audit_logs WHERE object_type='SUPPLIER' AND object_id=? ORDER BY id DESC LIMIT 1",id);assertThat(Sql.id(audit.get("actor_user_id"))).isEqualTo(manager);assertThat(audit.get("before_values").toString()).contains("ACTIVE");assertThat(audit.get("after_values").toString()).contains("DISCONTINUED");}
    @Test void pagingCountLookupAndForeignWarehouseShareOneScope(){String prefix="PAGE-"+UUID.randomUUID();var first=new vn.codegym.salesinventory.dto.PageRequest(1,20);assertThat(suppliers.search(manager,prefix,first).totalItems()).isZero();long id=suppliers.save(manager,0,input(prefix+"-00",wh,0,"ACTIVE"));assertThat(suppliers.search(manager,prefix,first).totalItems()).isEqualTo(1);
        for(int i=1;i<21;i++)suppliers.save(manager,0,input(prefix+"-"+String.format("%02d",i),wh,0,"ACTIVE"));long other=user("WAREHOUSE_MANAGER"),foreign=warehouse(other);suppliers.save(other,0,input(prefix+"-FOREIGN",foreign,0,"ACTIVE"));
        var page=suppliers.search(manager,prefix,first);var last=suppliers.search(manager,prefix,new vn.codegym.salesinventory.dto.PageRequest(Integer.MAX_VALUE,20));assertThat(page.totalItems()).isEqualTo(21);assertThat(page.items()).hasSize(20);assertThat(last.page()).isEqualTo(2);assertThat(last.items()).hasSize(1);assertThat(page.items().stream().map(x->x.get("id"))).doesNotContain(last.items().get(0).get("id"));
        var suggestions=suppliers.suggest(manager,prefix+"-00");assertThat(suggestions).hasSize(1);assertThat(Sql.id(suggestions.get(0).get("id"))).isEqualTo(id);assertThat(suppliers.suggest(manager,prefix+"-FOREIGN")).isEmpty();assertThat(suppliers.search(manager,"cung cap",first).totalItems()).isGreaterThanOrEqualTo(21);assertThat(suppliers.suggest(manager,"P")).isEmpty();assertThat(suppliers.suggest(manager,prefix)).hasSize(10);
        update("DELETE FROM user_warehouses WHERE user_id=?",manager);assertThat(suppliers.search(manager,prefix,first).totalItems()).isZero();assertThat(suppliers.suggest(manager,prefix)).isEmpty();assertThatThrownBy(()->suppliers.find(manager,id)).isInstanceOf(SecurityException.class);assertThatThrownBy(()->suppliers.delete(manager,id)).isInstanceOf(SecurityException.class);
    }
    @Test void lockedActorCannotListCountSuggestOrWrite(){long id=save();update("UPDATE users SET status='ADMIN_LOCKED' WHERE id=?",manager);assertThatThrownBy(()->suppliers.search(manager,"",new vn.codegym.salesinventory.dto.PageRequest(1,20))).isInstanceOf(SecurityException.class);assertThatThrownBy(()->suppliers.suggest(manager,"SUP")).isInstanceOf(SecurityException.class);assertThatThrownBy(()->suppliers.find(manager,id)).isInstanceOf(SecurityException.class);assertThatThrownBy(()->suppliers.save(manager,id,input("LOCKED",wh,1,"ACTIVE"))).isInstanceOf(SecurityException.class);assertThatThrownBy(()->suppliers.delete(manager,id)).isInstanceOf(SecurityException.class);}
    @Test void twoWarehousesAndForgedIdsAreDenied(){long id=save(),other=user("WAREHOUSE_MANAGER"),otherWh=warehouse(other);assertThat(suppliers.list(other,"")).noneMatch(r->Sql.id(r.get("id"))==id);assertThatThrownBy(()->suppliers.find(other,id)).isInstanceOf(SecurityException.class);assertThatThrownBy(()->suppliers.save(other,id,input("OTHER",otherWh,1,"ACTIVE"))).isInstanceOf(SecurityException.class);assertThatThrownBy(()->suppliers.save(manager,id,input("OTHER",otherWh,1,"ACTIVE"))).isInstanceOf(SecurityException.class);assertThatThrownBy(()->suppliers.delete(other,id)).isInstanceOf(SecurityException.class);}
    @Test void ownWarehouseTransferAndStaleVersion(){long id=save(),next=warehouse(manager);String code=Sql.text(one("SELECT code FROM suppliers WHERE id=?",id).get("code"));suppliers.save(manager,id,input(code,next,1,"ACTIVE"));assertThat(Sql.id(suppliers.find(manager,id).get("warehouse_id"))).isEqualTo(next);assertThatThrownBy(()->suppliers.save(manager,id,input(code,wh,1,"ACTIVE"))).hasMessageContaining("thay đổi");}
    @Test void receiptReferenceBlocksDeleteButAllowsDiscontinue(){long id=save();update("INSERT INTO supplier_receipt_references(supplier_id,receipt_reference) VALUES(?,'TEST')",id);assertThatThrownBy(()->suppliers.delete(manager,id)).isInstanceOf(FieldValidationException.class);suppliers.save(manager,id,input(Sql.text(suppliers.find(manager,id).get("code")),wh,1,"DISCONTINUED"));assertThat(suppliers.find(manager,id)).containsEntry("status","DISCONTINUED");}
    @Test void duplicateCodeAcrossWarehousesRejected(){long id=save();String code=Sql.text(suppliers.find(manager,id).get("code"));assertThatThrownBy(()->suppliers.save(manager,0,input(code.toLowerCase(Locale.ROOT),warehouse(manager),0,"ACTIVE"))).isInstanceOf(FieldValidationException.class);}
    @Test void concurrentDuplicateCodeHasOneWinner()throws Exception{String code="S-"+UUID.randomUUID();var gate=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(2);try{Callable<Boolean> call=()->{gate.await();try{suppliers.save(manager,0,input(code,wh,0,"ACTIVE"));return true;}catch(FieldValidationException duplicate){return false;}};var a=pool.submit(call);var b=pool.submit(call);gate.countDown();assertThat(List.of(a.get(30,TimeUnit.SECONDS),b.get(30,TimeUnit.SECONDS))).containsExactlyInAnyOrder(true,false);assertThat(count("SELECT COUNT(*) n FROM suppliers WHERE code=?",code)).isEqualTo(1);}finally{pool.shutdownNow();}}
    @Test void simultaneousEditsHaveOneWinner()throws Exception{long id=save();String code=Sql.text(suppliers.find(manager,id).get("code"));var gate=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(2);try{Callable<Boolean> call=()->{gate.await();try{suppliers.save(manager,id,input(code,wh,1,"DISCONTINUED"));return true;}catch(FieldValidationException stale){return false;}};var a=pool.submit(call);var b=pool.submit(call);gate.countDown();assertThat(List.of(a.get(30,TimeUnit.SECONDS),b.get(30,TimeUnit.SECONDS))).containsExactlyInAnyOrder(true,false);}finally{pool.shutdownNow();}}
    @Test void auditRollbackAndSevenRoleProtection(){long id=save();String code=Sql.text(suppliers.find(manager,id).get("code"));failAudit();assertThatThrownBy(()->suppliers.save(manager,id,input(code,wh,1,"DISCONTINUED"))).isInstanceOf(IllegalStateException.class);assertThat(suppliers.find(manager,id)).containsEntry("status","ACTIVE");assertThatThrownBy(()->suppliers.delete(manager,id)).isInstanceOf(IllegalStateException.class);assertThat(suppliers.find(manager,id)).isNotEmpty();assertThatThrownBy(()->suppliers.save(manager,0,input("ROLLBACK",wh,0,"ACTIVE"))).isInstanceOf(IllegalStateException.class);assertThat(query("SELECT id FROM suppliers WHERE code='ROLLBACK'")).isEmpty();for(String role:new String[]{"ADMIN","SALES","SALES_MANAGER","WAREHOUSE","ACCOUNTANT","DIRECTOR"})assertThatThrownBy(()->suppliers.save(user(role),0,input("DENIED",wh,0,"ACTIVE"))).isInstanceOf(SecurityException.class);}
}
