package vn.codegym.salesinventory.dao;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import vn.codegym.salesinventory.service.*;
import vn.codegym.salesinventory.validation.FieldValidationException;
import static org.assertj.core.api.Assertions.*;
class SupplierAcceptanceIT extends StoryDatabaseSupport {
    long manager,wh;SupplierService suppliers;
    @BeforeEach void fixture(){manager=user("WAREHOUSE_MANAGER");wh=warehouse(manager);suppliers=new SupplierService(source);}
    SupplierService.Input input(String code,long warehouse,long version,String status){return new SupplierService.Input(code," Nhà cung cấp O'An ","0123456789-001"," Liên hệ ","+84912345678"," Trả ngay ",warehouse,status,version);}
    long save(){return suppliers.save(manager,0,input("S-"+UUID.randomUUID(),wh,0,"ACTIVE"));}
    @Test void normalizedValuesAndAuditBeforeAfter(){long id=save();var row=one("SELECT * FROM suppliers WHERE id=?",id);assertThat(row).containsEntry("name","Nhà cung cấp O'An").containsEntry("contact_phone","0912345678").containsEntry("payment_terms","Trả ngay");suppliers.save(manager,id,input(Sql.text(row.get("code")),wh,1,"DISCONTINUED"));var audit=one("SELECT actor_user_id,before_values,after_values FROM audit_logs WHERE object_type='SUPPLIER' AND object_id=? ORDER BY id DESC LIMIT 1",id);assertThat(Sql.id(audit.get("actor_user_id"))).isEqualTo(manager);assertThat(audit.get("before_values").toString()).contains("ACTIVE");assertThat(audit.get("after_values").toString()).contains("DISCONTINUED");}
    @Test void twoWarehousesAndForgedIdsAreDenied(){long id=save(),other=user("WAREHOUSE_MANAGER"),otherWh=warehouse(other);assertThat(suppliers.list(other,"")).noneMatch(r->Sql.id(r.get("id"))==id);assertThatThrownBy(()->suppliers.find(other,id)).isInstanceOf(SecurityException.class);assertThatThrownBy(()->suppliers.save(other,id,input("OTHER",otherWh,1,"ACTIVE"))).isInstanceOf(SecurityException.class);assertThatThrownBy(()->suppliers.save(manager,id,input("OTHER",otherWh,1,"ACTIVE"))).isInstanceOf(SecurityException.class);assertThatThrownBy(()->suppliers.delete(other,id)).isInstanceOf(SecurityException.class);}
    @Test void ownWarehouseTransferAndStaleVersion(){long id=save(),next=warehouse(manager);String code=Sql.text(one("SELECT code FROM suppliers WHERE id=?",id).get("code"));suppliers.save(manager,id,input(code,next,1,"ACTIVE"));assertThat(Sql.id(suppliers.find(manager,id).get("warehouse_id"))).isEqualTo(next);assertThatThrownBy(()->suppliers.save(manager,id,input(code,wh,1,"ACTIVE"))).hasMessageContaining("thay đổi");}
    @Test void receiptReferenceBlocksDeleteButAllowsDiscontinue(){long id=save();update("INSERT INTO supplier_receipt_references(supplier_id,receipt_reference) VALUES(?,'TEST')",id);assertThatThrownBy(()->suppliers.delete(manager,id)).isInstanceOf(FieldValidationException.class);suppliers.save(manager,id,input(Sql.text(suppliers.find(manager,id).get("code")),wh,1,"DISCONTINUED"));assertThat(suppliers.find(manager,id)).containsEntry("status","DISCONTINUED");}
    @Test void duplicateCodeAcrossWarehousesRejected(){long id=save();String code=Sql.text(suppliers.find(manager,id).get("code"));assertThatThrownBy(()->suppliers.save(manager,0,input(code.toLowerCase(Locale.ROOT),warehouse(manager),0,"ACTIVE"))).isInstanceOf(FieldValidationException.class);}
    @Test void concurrentDuplicateCodeHasOneWinner()throws Exception{String code="S-"+UUID.randomUUID();var gate=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(2);try{Callable<Boolean> call=()->{gate.await();try{suppliers.save(manager,0,input(code,wh,0,"ACTIVE"));return true;}catch(FieldValidationException duplicate){return false;}};var a=pool.submit(call);var b=pool.submit(call);gate.countDown();assertThat(List.of(a.get(30,TimeUnit.SECONDS),b.get(30,TimeUnit.SECONDS))).containsExactlyInAnyOrder(true,false);assertThat(count("SELECT COUNT(*) n FROM suppliers WHERE code=?",code)).isEqualTo(1);}finally{pool.shutdownNow();}}
    @Test void simultaneousEditsHaveOneWinner()throws Exception{long id=save();String code=Sql.text(suppliers.find(manager,id).get("code"));var gate=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(2);try{Callable<Boolean> call=()->{gate.await();try{suppliers.save(manager,id,input(code,wh,1,"DISCONTINUED"));return true;}catch(FieldValidationException stale){return false;}};var a=pool.submit(call);var b=pool.submit(call);gate.countDown();assertThat(List.of(a.get(30,TimeUnit.SECONDS),b.get(30,TimeUnit.SECONDS))).containsExactlyInAnyOrder(true,false);}finally{pool.shutdownNow();}}
    @Test void auditRollbackAndSevenRoleProtection(){long id=save();String code=Sql.text(suppliers.find(manager,id).get("code"));failAudit();assertThatThrownBy(()->suppliers.save(manager,id,input(code,wh,1,"DISCONTINUED"))).isInstanceOf(IllegalStateException.class);assertThat(suppliers.find(manager,id)).containsEntry("status","ACTIVE");assertThatThrownBy(()->suppliers.delete(manager,id)).isInstanceOf(IllegalStateException.class);assertThat(suppliers.find(manager,id)).isNotEmpty();assertThatThrownBy(()->suppliers.save(manager,0,input("ROLLBACK",wh,0,"ACTIVE"))).isInstanceOf(IllegalStateException.class);assertThat(query("SELECT id FROM suppliers WHERE code='ROLLBACK'")).isEmpty();for(String role:new String[]{"ADMIN","SALES","SALES_MANAGER","WAREHOUSE","ACCOUNTANT","DIRECTOR"})assertThatThrownBy(()->suppliers.save(user(role),0,input("DENIED",wh,0,"ACTIVE"))).isInstanceOf(SecurityException.class);}
}
