<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html><html lang="vi"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nhà cung cấp</title><%@ include file="../fragments/assets.jspf" %></head><body class="app-page"><%@ include file="../fragments/sidebar.jspf" %>
<%@ include file="../fragments/topbar.jspf" %>
<main class="page-body app-content catalog-page"><h1>Nhà cung cấp</h1>
<c:if test="${param.notice == 'saved'}"><p class="alert alert-success" role="status">Đã lưu nhà cung cấp.</p></c:if>
<c:if test="${not empty errors.form}"><p class="alert alert-error" role="alert"><c:out value="${errors.form}"/></p></c:if>
<form method="get"><label>Tìm mã/tên <input name="q" value="<c:out value='${param.q}'/>"></label><button class="button">Tìm</button></form>
<c:if test="${access.allows('WAREHOUSE_MANAGE')}"><section class="content-panel"><h2>${empty edit.id ? 'Thêm nhà cung cấp' : 'Sửa nhà cung cấp'}</h2>
<form method="post" class="account-form">
<input type="hidden" name="_csrf" value="<c:out value='${csrfToken}'/>"><input type="hidden" name="id" value="<c:out value='${edit.id}'/>"><input type="hidden" name="version" value="<c:out value='${edit.version}'/>">
<label class="field">Mã <input name="code" required maxlength="50" value="<c:out value='${edit.code}'/>" aria-describedby="code-error" aria-invalid="${not empty errors.code}"><span id="code-error" class="field-error"><c:out value="${errors.code}"/></span></label>
<label class="field">Tên <input name="name" required maxlength="200" value="<c:out value='${edit.name}'/>" aria-describedby="name-error" aria-invalid="${not empty errors.name}"><span id="name-error" class="field-error"><c:out value="${errors.name}"/></span></label>
<label class="field">Mã số thuế <input name="taxCode" required maxlength="14" value="<c:out value='${edit.tax_code}'/>" aria-describedby="taxCode-error" aria-invalid="${not empty errors.taxCode}"><span id="taxCode-error" class="field-error"><c:out value="${errors.taxCode}"/></span></label>
<label class="field">Người liên hệ <input name="contact" required maxlength="150" value="<c:out value='${edit.contact_name}'/>" aria-describedby="contact-error" aria-invalid="${not empty errors.contact}"><span id="contact-error" class="field-error"><c:out value="${errors.contact}"/></span></label>
<label class="field">Điện thoại <input name="phone" required maxlength="20" value="<c:out value='${edit.contact_phone}'/>" aria-describedby="phone-error" aria-invalid="${not empty errors.phone}"><span id="phone-error" class="field-error"><c:out value="${errors.phone}"/></span></label>
<label class="field">Điều khoản thanh toán <input name="terms" required maxlength="250" value="<c:out value='${edit.payment_terms}'/>" aria-describedby="terms-error" aria-invalid="${not empty errors.terms}"><span id="terms-error" class="field-error"><c:out value="${errors.terms}"/></span></label>
<label class="field">Kho <select name="warehouse" required aria-describedby="warehouse-error"><c:forEach items="${warehouses}" var="w"><option value="${w.id}" ${edit.warehouse_id == w.id.toString() ? 'selected' : ''}><c:out value="${w.name}"/></option></c:forEach></select><span id="warehouse-error" class="field-error"><c:out value="${errors.warehouse}"/></span></label>
<label class="field">Trạng thái <select name="status" aria-describedby="status-error"><c:if test="${not empty edit.status and edit.status != 'ACTIVE' and edit.status != 'DISCONTINUED'}"><option selected value="<c:out value='${edit.status}'/>"><c:out value="${edit.status}"/></option></c:if><option value="ACTIVE">Đang giao dịch</option><option value="DISCONTINUED" ${edit.status == 'DISCONTINUED' ? 'selected' : ''}>Ngừng giao dịch</option></select><span id="status-error" class="field-error"><c:out value="${errors.status}"/></span></label>
<button class="button button-primary">Lưu nhà cung cấp</button></form></section></c:if>
<div class="table-wrap"><table><thead><tr><th>Mã</th><th>Tên</th><th>Mã số thuế</th><th>Liên hệ</th><th>Thanh toán</th><th>Kho</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>
<c:forEach items="${suppliers}" var="p"><tr><td><c:out value="${p.code}"/></td><td><c:out value="${p.name}"/></td><td><c:out value="${p.tax_code}"/></td><td><c:out value="${p.contact_name}"/> / <c:out value="${p.contact_phone}"/></td><td><c:out value="${p.payment_terms}"/></td><td><c:out value="${p.warehouse_name}"/></td><td>${p.status == 'ACTIVE' ? 'Đang giao dịch' : 'Ngừng giao dịch'}</td><td><c:if test="${access.allows('WAREHOUSE_MANAGE')}"><a href="?id=${p.id}">Sửa / ngừng giao dịch</a><form method="post"><input type="hidden" name="_csrf" value="<c:out value='${csrfToken}'/>"><input type="hidden" name="id" value="${p.id}"><input type="hidden" name="action" value="delete"><button class="button">Xóa</button></form></c:if></td></tr></c:forEach>
</tbody></table></div></main></body></html>

