<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html><html lang="vi"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Đơn vị quy đổi</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/app.css?v=s207"></head>
<body class="app-page"><%@ include file="../fragments/sidebar.jspf" %><main class="page-body app-content catalog-page units-page"><h1>Đơn vị quy đổi</h1>
<form method="get" class="filter-form"><label>Tìm SKU <input name="q" value="<c:out value='${param.q}'/>"></label><button class="button">Tìm</button></form>
<form method="get" class="filter-form"><label>Sản phẩm <select name="product"><c:forEach items="${products}" var="p"><option value="${p.id}" ${p.id == productId ? 'selected' : ''}><c:out value="${p.sku}"/> — <c:out value="${p.name}"/></option></c:forEach></select></label><button class="button">Xem đơn vị</button></form>
<c:if test="${param.notice == 'saved'}"><p class="alert" role="status">Đã lưu thay đổi đơn vị.</p></c:if>
<c:if test="${not empty conversion}"><p class="alert" role="status"><c:out value="${conversion}"/></p></c:if>
<c:if test="${not empty errors.form}"><p class="field-error" role="alert"><c:out value="${errors.form}"/></p></c:if>
<c:if test="${productId > 0 and access.allows('WAREHOUSE_MANAGE')}"><section class="content-panel"><h2>${empty edit.id ? 'Thêm đơn vị' : 'Sửa đơn vị'}</h2>
<form method="post" class="account-form"><input type="hidden" name="_csrf" value="<c:out value='${csrfToken}'/>"><input type="hidden" name="product" value="${productId}"><input type="hidden" name="id" value="<c:out value='${edit.id}'/>"><input type="hidden" name="version" value="<c:out value='${edit.version}'/>">
<label class="field">Tên đơn vị <input name="name" maxlength="50" required value="<c:out value='${edit.name}'/>" aria-invalid="${not empty errors.name}" aria-describedby="unit-name-error"><small id="unit-name-error" class="field-error"><c:out value="${errors.name}"/></small></label>
<label class="field">Hệ số <input name="factor" inputmode="decimal" required value="<c:out value='${edit.factor}'/>" aria-invalid="${not empty errors.factor}" aria-describedby="unit-factor-error"><small id="unit-factor-error" class="field-error"><c:out value="${errors.factor}"/></small></label>
<label class="field">Kho phụ trách <select name="warehouse" required><c:forEach items="${warehouses}" var="w"><option value="${w.id}" ${not empty edit.warehouse_id and w.id.toString() == edit.warehouse_id.toString() ? 'selected' : ''}><c:out value="${w.name}"/></option></c:forEach></select></label>
<button class="button button-primary">Lưu đơn vị</button></form></section></c:if>
<div class="table-wrap"><table><thead><tr><th>Đơn vị</th><th>Hệ số</th><th>Phiên bản</th><th>Kho</th><th>Thao tác</th></tr></thead><tbody><c:forEach items="${units}" var="u"><tr><td><c:out value="${u.name}"/></td><td><c:out value="${u.factor}"/></td><td><c:out value="${u.version}"/></td><td><c:choose><c:when test="${empty u.warehouse_id}">Dùng chung</c:when><c:otherwise><c:out value="${u.warehouse_name}"/></c:otherwise></c:choose></td><td>
<c:if test="${not empty u.warehouse_id and access.allows('WAREHOUSE_MANAGE')}"><a href="?product=${productId}&amp;edit=${u.id}">Sửa</a><form method="post"><input type="hidden" name="_csrf" value="<c:out value='${csrfToken}'/>"><input type="hidden" name="id" value="${u.id}"><input type="hidden" name="product" value="${productId}"><button class="button" name="action" value="delete">Xóa</button></form></c:if>
<form method="get"><input type="hidden" name="id" value="${u.id}"><input type="hidden" name="product" value="${productId}"><input type="hidden" name="action" value="convert"><label>Số lượng <input name="quantity" inputmode="decimal" required value="<c:if test='${param.id == u.id.toString()}'><c:out value='${param.quantity}'/></c:if>"><c:if test="${param.id == u.id.toString()}"><small class="field-error" role="alert"><c:out value="${errors.quantity}"/></small></c:if></label><button class="button">Quy đổi</button></form>
</td></tr></c:forEach></tbody></table></div></main></body></html>

