<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html><html lang="vi"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Đơn vị quy đổi</title><%@ include file="../fragments/assets.jspf" %></head>
<body class="app-page"><%@ include file="../fragments/sidebar.jspf" %>
<%@ include file="../fragments/topbar.jspf" %><main class="page-body app-content catalog-page units-page"><div class="page-heading"><div><h1>Đơn vị quy đổi</h1><p>Tra cứu và quy đổi theo đơn vị cơ sở của sản phẩm.</p></div><c:if test="${access.allows('WAREHOUSE_MANAGE') and productId > 0}"><a class="button button-primary" href="?new=1&amp;product=${productId}#editor" data-editor="editor">＋ Thêm mới</a></c:if></div>
<form method="get" class="filter-form"><label>Tìm SKU <input name="q" value="<c:out value='${param.q}'/>"></label><button class="button button-primary">Tìm</button><a class="button button-secondary" href="${pageContext.request.contextPath}/catalog/units">Bỏ bộ lọc</a></form>
<form method="get" class="filter-form"><label>Sản phẩm <select name="product"><c:forEach items="${products}" var="p"><option value="${p.id}" ${p.id == productId ? 'selected' : ''}><c:out value="${p.sku}"/> — <c:out value="${p.name}"/></option></c:forEach></select></label><button class="button">Xem đơn vị</button></form>
<c:if test="${param.notice == 'saved'}"><p class="alert" role="status">Đã lưu thay đổi đơn vị.</p></c:if>
<c:if test="${not empty conversion}"><p class="alert" role="status"><c:out value="${conversion}"/></p></c:if>
<c:if test="${not empty errors.form}"><p class="field-error" role="alert"><c:out value="${errors.form}"/></p></c:if>
<c:if test="${productId > 0 and access.allows('WAREHOUSE_MANAGE')}"><details id="editor" class="content-panel disclosure editor" ${not empty edit.id or not empty errors or param['new'] == '1' ? 'open' : ''}><summary>${empty edit.id ? 'Thêm đơn vị' : 'Sửa đơn vị'}</summary>
<form method="post" class="account-form"><input type="hidden" name="_csrf" value="<c:out value='${csrfToken}'/>"><input type="hidden" name="product" value="${productId}"><input type="hidden" name="id" value="<c:out value='${edit.id}'/>"><input type="hidden" name="version" value="<c:out value='${edit.version}'/>">
<label class="field">Tên đơn vị <input name="name" maxlength="50" required value="<c:out value='${edit.name}'/>" aria-invalid="${not empty errors.name}" aria-describedby="unit-name-error"><small id="unit-name-error" class="field-error"><c:out value="${errors.name}"/></small></label>
<label class="field">Hệ số <input name="factor" inputmode="decimal" required value="<c:out value='${edit.factor}'/>" aria-invalid="${not empty errors.factor}" aria-describedby="unit-factor-error"><small id="unit-factor-error" class="field-error"><c:out value="${errors.factor}"/></small></label>
<label class="field">Kho phụ trách <select name="warehouse" required><c:forEach items="${warehouses}" var="w"><option value="${w.id}" ${not empty edit.warehouse_id and w.id.toString() == edit.warehouse_id.toString() ? 'selected' : ''}><c:out value="${w.name}"/></option></c:forEach></select></label>
<button class="button button-primary">Lưu đơn vị</button><a class="button button-secondary" href="${pageContext.request.contextPath}/catalog/units?product=${productId}">Hủy</a></form></details></c:if>
<div class="table-wrap"><table><thead><tr><th>Đơn vị</th><th>Hệ số</th><th>Phiên bản</th><th>Kho</th><th>Thao tác</th></tr></thead><tbody><c:forEach items="${units}" var="u"><tr><td><c:out value="${u.name}"/></td><td><c:out value="${u.factor}"/></td><td><c:out value="${u.version}"/></td><td><c:choose><c:when test="${empty u.warehouse_id}">Dùng chung</c:when><c:otherwise><c:out value="${u.warehouse_name}"/></c:otherwise></c:choose></td><td>
<c:if test="${not empty u.warehouse_id and access.allows('WAREHOUSE_MANAGE')}"><a href="?product=${productId}&amp;edit=${u.id}">Sửa</a><form method="post" data-confirm="Bạn có chắc muốn xóa bản ghi này?"><input type="hidden" name="_csrf" value="<c:out value='${csrfToken}'/>"><input type="hidden" name="id" value="${u.id}"><input type="hidden" name="product" value="${productId}"><button class="button" name="action" value="delete">Xóa</button></form></c:if>
<form method="get"><input type="hidden" name="id" value="${u.id}"><input type="hidden" name="product" value="${productId}"><input type="hidden" name="action" value="convert"><label>Số lượng <input name="quantity" inputmode="decimal" required value="<c:if test='${param.id == u.id.toString()}'><c:out value='${param.quantity}'/></c:if>"><c:if test="${param.id == u.id.toString()}"><small class="field-error" role="alert"><c:out value="${errors.quantity}"/></small></c:if></label><button class="button">Quy đổi</button></form>
</td></tr></c:forEach><c:if test="${empty units}"><tr><td colspan="8" class="empty-state">Chưa có dữ liệu phù hợp.</td></tr></c:if></tbody></table></div></main></body></html>
