CREATE TABLE warehouses(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(50) NOT NULL UNIQUE,name VARCHAR(150) NOT NULL);
CREATE TABLE territories(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(50) NOT NULL UNIQUE,name VARCHAR(150) NOT NULL);
CREATE TABLE user_warehouses(user_id BIGINT UNSIGNED NOT NULL,warehouse_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(user_id,warehouse_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(warehouse_id) REFERENCES warehouses(id));
CREATE TABLE user_territories(user_id BIGINT UNSIGNED NOT NULL,territory_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(user_id,territory_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(territory_id) REFERENCES territories(id));
