ALTER TABLE users DROP CHECK chk_users_status;
ALTER TABLE users ADD CONSTRAINT chk_users_status CHECK(status IN ('ACTIVE','DISABLED','ADMIN_LOCKED','PENDING_ACTIVATION'));
CREATE TABLE activation_tokens(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,
 token_hash CHAR(64) NOT NULL UNIQUE,expires_at DATETIME(6) NOT NULL,used_at DATETIME(6),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,INDEX idx_activation_user(user_id));
