CREATE TABLE catalog_locks(name VARCHAR(50) PRIMARY KEY);
INSERT INTO catalog_locks VALUES('CATEGORY_TREE');
CREATE TABLE categories(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(50) NOT NULL UNIQUE,name VARCHAR(150) NOT NULL,parent_id BIGINT UNSIGNED NULL,version BIGINT NOT NULL DEFAULT 1,FOREIGN KEY(parent_id) REFERENCES categories(id));
