<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html><html lang="vi"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Phân công người dùng</title><%@ include file="../fragments/assets.jspf" %></head><body class="app-page"><%@ include file="../fragments/sidebar.jspf" %>
<%@ include file="../fragments/topbar.jspf" %><main class="page-body app-content assignments-page">
<div class="page-heading"><div><h1>Phân công người dùng</h1><p><c:out value="${target.full_name}"/> — <c:out value="${target.username}"/></p></div><a class="button button-secondary" href="${pageContext.request.contextPath}/admin/scopes">Danh mục kho và địa bàn</a></div>
<c:if test="${param.notice == 'saved'}"><div class="alert alert-success" role="status">Đã lưu phân công.</div></c:if><c:if test="${not empty formError}"><div class="alert alert-error" role="alert"><c:out value="${formError}"/></div></c:if>
<form class="content-panel account-form assignment-form" method="post"><input type="hidden" name="id" value="${target.id}"><input type="hidden" name="_csrf" value="<c:out value='${csrfToken}'/>">
<fieldset><legend>Vai trò</legend><p class="muted">Có thể chọn nhiều vai trò. Vai trò quyết định quyền; kho và địa bàn xác định phạm vi phụ trách.</p><div class="permission-grid">
<c:forEach var="item" items="${roles}"><c:set var="ownAdmin" value="${target.id == currentUser.id() and access.roles().contains('ADMIN') and item.code == 'ADMIN'}"/><label class="checkbox-field"><input type="checkbox" name="role" value="${item.code}" ${(ownAdmin or (not empty form ? form.roles.contains(item.code) : item.selected == 1)) ? 'checked' : ''} ${ownAdmin ? 'disabled' : ''}> <c:out value="${item.name}"/></label><c:if test="${ownAdmin}"><input type="hidden" name="role" value="ADMIN"></c:if></c:forEach></div>
<c:if test="${target.id == currentUser.id() and access.roles().contains('ADMIN')}"><p class="muted">Bạn không thể tự thu hồi vai trò quản trị của mình.</p></c:if></fieldset>
<div class="form-grid"><fieldset><legend>Kho phụ trách</legend><p class="muted" id="warehouse-assignment-help">Trưởng kho hoặc Nhân viên kho phải có ít nhất một kho. Địa bàn không thay thế kho.</p>
<c:forEach var="item" items="${warehouses}"><label class="checkbox-field scope-choice"><input type="checkbox" name="warehouse" value="${item.id}" aria-describedby="warehouse-assignment-help" ${(not empty form ? form.warehouses.contains(item.id.toString()) : item.selected == 1) ? 'checked' : ''}><span><strong><c:out value="${item.name}"/></strong><small><c:out value="${item.code}"/> · <c:choose><c:when test="${not empty item.address}"><c:out value="${item.address}"/></c:when><c:otherwise>Chưa bổ sung địa chỉ</c:otherwise></c:choose></small></span></label></c:forEach>
<c:if test="${empty warehouses}"><div class="alert alert-warning">Chưa có kho để phân công. <a href="${pageContext.request.contextPath}/admin/scopes?new=1&amp;kind=warehouse">Tạo kho kèm địa chỉ</a> trước khi gán vai trò kho.</div></c:if>
</fieldset><fieldset><legend>Địa bàn phụ trách</legend><p class="muted">Chọn khu vực kinh doanh được giao. Địa bàn không phải địa chỉ của kho.</p>
<c:forEach var="item" items="${territories}"><label class="checkbox-field scope-choice"><input type="checkbox" name="territory" value="${item.id}" ${(not empty form ? form.territories.contains(item.id.toString()) : item.selected == 1) ? 'checked' : ''}><span><strong><c:out value="${item.name}"/></strong><small><c:out value="${item.code}"/> · <c:choose><c:when test="${not empty item.address}"><c:out value="${item.address}"/></c:when><c:otherwise>Chưa bổ sung địa chỉ</c:otherwise></c:choose></small></span></label></c:forEach>
<c:if test="${empty territories}"><p class="muted">Chưa có địa bàn. <a href="${pageContext.request.contextPath}/admin/scopes?new=1&amp;kind=territory">Thêm địa bàn</a> nếu cần phân công khu vực.</p></c:if></fieldset></div>
<div class="form-actions"><button class="button button-primary">Lưu phân công</button><a class="button button-secondary" href="${pageContext.request.contextPath}/admin/users">Về danh sách</a></div></form>
</main></body></html>
